ï»¿/*
 Copyright (c) 2003-2019, CKSource - Frederico Knabben. All rights reserved.
 For licensing, see LICENSE.md or https://ckeditor.com/legal/ckeditor-oss-license
*/
CKEDITOR.plugins.setLang("a11yhelp","az",{title:"ÆlillÉrÉ dÉstÉk Ã¼zrÉ tÉlimat",contents:"KÃ¶mÉk. PÉncÉrÉni baÄlamaq Ã¼Ã§Ã¼n ESC basÄ±n.",legend:[{name:"Æsas",items:[{name:"DÃ¼zÉliÅ edÉnin alÉtlÉr Ã§ubuÄu",legend:"PanelÉ keÃ§mÉk Ã¼Ã§Ã¼n ${toolbarFocus} basÄ±n. NÃ¶vbÉti panelÉ TAB, ÉvvÉlki panelÉ isÉ SHIFT+TAB dÃ¼ymÉsi vasitÉsi ilÉ keÃ§É bilÉrsiz. PaneldÉki dÃ¼ymÉlÉr arasÄ±nda sol vÉ saÄ ox dÃ¼ymÉsi ilÉ keÃ§id edÉ bilÉrsiz. SeÃ§ilmiÅ dÃ¼ymÉsi SPACE vÉ ya ENTER ilÉ iÅlÉdÉ bilÉrsiniz."},{name:"Redaktorun pÉncÉrÉsi",legend:"PÉncÉrÉ iÃ§indÉ nÃ¶vbÉti element seÃ§mÉk Ã¼Ã§Ã¼n TAB dÃ¼ymÉni basÄ±n, ÉvvÉlki isÉ - SHIFT+TAB. TÉsdiq edilmÉsi Ã¼Ã§Ã¼n ENTER, imtina edilmÉsi isÉ ESC diymÉlÉri istifadÉ edin. PÉncÉrÉdÉ bir neÃ§É vÉrÉq olanda olnarÄ±n siyahÄ± ALT+F10 ilÉ aÃ§a bilÉrsiz. VÉrÉqlÉrin siyahÄ± fokus altÄ±nda olanda ox dÃ¼ymÉlÉr vasitÉsi ilÉ onlarÄ±n arasÄ±nda keÃ§id edÉ bilÉrsiz."},
{name:"Redaktorun seÃ§imlÉrin menyusu",legend:"SeÃ§imlÉri redaktÉ etmÉk Ã¼Ã§Ã¼n ${contextMenu} ya da APPLICATION KEY basÄ±n. NÃ¶vbÉti seÃ§imÉ keÃ§mÉk Ã¼Ã§Ã¼n TAB ya AÅAÄI OX dÃ¼ymÉsini basÄ±n, ÉvvÉlki isÉ - SHIFT+TAB ya YUXARI OX. SeÃ§imi arÄ±maq SPACE ya ENTER dÃ¼ymÉlÉri istifadÉ edin. Alt menyunu aÃ§maq Ã¼Ã§Ã¼n SPACE, ENTER ya SAÄA OX basÄ±n. ESC ya SOLA OX ilÉ geriyÉ qayÄ±da bilÉrsiz. BÃ¼tÃ¼n menyunu ESC ilÉ baÄlÄ±yÄ±n."},{name:"DÃ¼zÉliÅ edÉnin siyahÄ± qutusu",legend:"SiyahÄ± qutusu iÃ§indÉ nÃ¶vbÉti bÉnd seÃ§mÉk Ã¼Ã§Ã¼n TAB ya AÅAÄI OX, ÉvvÉlki isÉ SHIFT+TAB ya YUXARI OX basÄ±n. SeÃ§imi arÄ±maq SPACE ya ENTER dÃ¼ymÉlÉri istifadÉ edin. SiyahÄ± qutusu ESC ilÉ baÄlÄ±yÄ±n."},
{name:"Redaktor elementin cÄ±ÄÄ±r paneli",legend:"Elementin cÄ±ÄÄ±r paneli seÃ§mÉk Ã¼Ã§Ã¼n ${elementsPathFocus} basÄ±n. NÃ¶vbÉti element seÃ§mÉk Ã¼Ã§Ã¼n TAB ya SAÄA OX, ÉvvÉlki isÉ SHIFT+TAB ya SOLA OX istifadÉ edin. Elementi arÄ±maq SPACE ya ENTER dÃ¼ymÉlÉri mÃ¶vcuddur."}]},{name:"ÆmrlÉr",items:[{name:"Æmri geri qaytar",legend:"${undo} basÄ±n"},{name:"Geri Émri",legend:"${redo} basÄ±n"},{name:"QalÄ±n Émri",legend:"${bold}  basÄ±n"},{name:"Kursiv Émri",legend:"${italic} basÄ±n"},{name:"Altdan xÉtt Émri",legend:"${underline} basÄ±n"},
{name:"Link Émri",legend:"${link} basÄ±n"},{name:"Paneli gizlÉt Émri",legend:"${toolbarCollapse} basÄ±n"},{name:"ÆvvÉlki fokus sahÉsi seÃ§ ÉmrÄ±",legend:"Kursordan ÉvvÉl Én yaxÄ±n ÉlÃ§atmaz yerÉ dÉymÉk Ã¼Ã§Ã¼n ${accessPreviousSpace} basÄ±n, misal Ã¼Ã§Ã¼n: iki dal-badal HR teg. Uzaq yerlÉrÉ dÉymÉk Ã¼Ã§Ã¼n bir neÃ§É dÉfÉ basÄ±n."},{name:"NÃ¶vbÉti fokus sahÉsi seÃ§ ÉmrÄ±",legend:"Kursordan sonra Én yaxÄ±n ÉlÃ§atmaz yerÉ dÉymÉk Ã¼Ã§Ã¼n ${accessNextSpace} basÄ±n, misal Ã¼Ã§Ã¼n: iki dal-badal HR teg. Uzaq yerlÉrÉ dÉymÉk Ã¼Ã§Ã¼n bir neÃ§É dÉfÉ basÄ±n."},
{name:"HÉrtÉrÉfli KÃ¶mÉk",legend:"${a11yHelp} basÄ±n"},{name:"YalnÄ±z mÉtni ÉlavÉ et",legend:"${pastetext} basÄ±n",legendEdge:"ÃncÉ ${pastetext}, sonra ${paste} basÄ±n"}]}],tab:"Tab",pause:"Pause",capslock:"Caps Lock",escape:"Escape",pageUp:"Page Up",pageDown:"Page Down",leftArrow:"Sola ox iÅarÉsi",upArrow:"YuxarÄ± ox iÅarÉsi",rightArrow:"SaÄa ox iÅarÉsi",downArrow:"AÅaÄÄ± ox iÅarÉsi",insert:"Insert",leftWindowKey:"Soldaki Windows dÃ¼ymÉsi",rightWindowKey:"SaÄdaki Windows dÃ¼ymÉsi",selectKey:"DÃ¼ymÉni seÃ§in",
numpad0:"Numpad 0",numpad1:"Numpad 1",numpad2:"Numpad 2",numpad3:"Numpad 3",numpad4:"Numpad 4",numpad5:"Numpad 5",numpad6:"Numpad 6",numpad7:"Numpad 7",numpad8:"Numpad 8",numpad9:"Numpad 9",multiply:"Vurma",add:"ÆlavÉ et",subtract:"ÃÄ±xma",decimalPoint:"Onluq kÉsri tam ÉdÉddÉn ayÄ±ran nÃ¶qtÉ",divide:"BÃ¶lÃ¼ÅdÃ¼rmÉ",f1:"F1",f2:"F2",f3:"F3",f4:"F4",f5:"F5",f6:"F6",f7:"F7",f8:"F8",f9:"F9",f10:"F10",f11:"F11",f12:"F12",numLock:"Num Lock",scrollLock:"Scroll Lock",semiColon:"NÃ¶qtÉli verqÃ¼l",equalSign:"BarÉbÉrlik iÅarÉsi",
comma:"VergÃ¼l",dash:"Defis",period:"NÃ¶qtÉ",forwardSlash:"ÃÉp xÉtt",graveAccent:"VurÄu iÅarÉsi",openBracket:"AÃ§Ä±lan mÃ¶tÉrizÉ",backSlash:"TÉrs Ã§ÉpÉki xÉtt",closeBracket:"BaÄlanan mÃ¶tÉrizÉ",singleQuote:"TÉk dÄ±rnaq"});