ï»¿/*
 Copyright (c) 2003-2019, CKSource - Frederico Knabben. All rights reserved.
 For licensing, see LICENSE.md or https://ckeditor.com/legal/ckeditor-oss-license
*/
CKEDITOR.plugins.setLang("a11yhelp","cs",{title:"Instrukce pro pÅÃ­stupnost",contents:"Obsah nÃ¡povÄdy. Pro uzavÅenÃ­ tohoto dialogu stisknÄte klÃ¡vesu ESC.",legend:[{name:"ObecnÃ©",items:[{name:"Panel nÃ¡strojÅ¯ editoru",legend:"StisknÄte${toolbarFocus} k prochÃ¡zenÃ­ panelu nÃ¡strojÅ¯. PÅejdÄte na dalÅ¡Ã­ a pÅedchozÃ­ skupiny pomocÃ­ TAB a SHIFT+TAB. PÅechod na dalÅ¡Ã­ a pÅedchozÃ­ tlaÄÃ­tko panelu nÃ¡strojÅ¯ je pomocÃ­ Å IPKA VPRAVO nebo Å IPKA VLEVO. StisknutÃ­m mezernÃ­ku nebo klÃ¡vesy ENTER tlaÄÃ­tko aktivujete."},{name:"DialogovÃ© okno editoru",
legend:"UvnitÅ dialogovÃ©ho okna stisknÄte TAB pro pÅesunutÃ­ na dalÅ¡Ã­ prvek okna, stisknÄte SHIFT+TAB pro pÅesun na pÅedchozÃ­ prvek okna, stisknÄte ENTER pro odeslÃ¡nÃ­ dialogu, stisknÄte ESC pro jeho zruÅ¡enÃ­. Pro dialogovÃ¡ okna, kterÃ¡ majÃ­ mnoho karet stisknÄte ALT+F10 pro zamÄÅenÃ­ seznamu karet, nebo TAB, pro posun podle poÅadÃ­ karet.PÅi zamÄÅenÃ­ seznamu karet se mÅ¯Å¾ete jimi posouvat pomocÃ­ Å IPKY VPRAVO a VLEVO."},{name:"KontextovÃ© menu editoru",legend:"StisknÄte ${contextMenu} nebo klÃ¡vesu APPLICATION k otevÅenÃ­ kontextovÃ©ho menu. Pak se pÅesuÅte na dalÅ¡Ã­ moÅ¾nost menu pomocÃ­ TAB nebo Å IPKY DOLÅ®. PÅesuÅte se na pÅedchozÃ­ moÅ¾nost pomocÃ­  SHIFT+TAB nebo Å IPKY NAHORU. StisknÄte MEZERNÃK nebo ENTER pro zvolenÃ­ moÅ¾nosti menu. Podmenu souÄasnÃ© moÅ¾nosti otevÅete pomocÃ­ MEZERNÃKU nebo ENTER Äi Å IPKY DOLEVA. KontextovÃ© menu uzavÅete stiskem ESC."},
{name:"RÃ¡meÄek seznamu editoru",legend:"UvnitÅ rÃ¡meÄku seznamu se pÅesunete na dalÅ¡Ã­ poloÅ¾ku menu pomocÃ­ TAB nebo Å IPKA DOLÅ®. Na pÅedchozÃ­ poloÅ¾ku se pÅesunete SHIFT+TAB nebo Å IPKA NAHORU. StisknÄte MEZERNÃK nebo ENTER pro zvolenÃ­ moÅ¾nosti seznamu. StisknÄte ESC pro uzavÅenÃ­ seznamu."},{name:"LiÅ¡ta cesty prvku v editoru",legend:"StisknÄte ${elementsPathFocus} pro prochÃ¡zenÃ­ liÅ¡ty cesty prvku. Na dalÅ¡Ã­ tlaÄÃ­tko prvku se pÅesunete pomocÃ­ TAB nebo Å IPKA VPRAVO. Na pÅedchozÃ­ tlaÄÃ­tko se pÅesunete pomocÃ­ SHIFT+TAB nebo Å IPKA VLEVO. StisknÄte MEZERNÃK nebo ENTER pro vybrÃ¡nÃ­ prvku v editoru."}]},
{name:"PÅÃ­kazy",items:[{name:" PÅÃ­kaz ZpÄt",legend:"StisknÄte ${undo}"},{name:" PÅÃ­kaz Znovu",legend:"StisknÄte ${redo}"},{name:" PÅÃ­kaz TuÄnÃ©",legend:"StisknÄte ${bold}"},{name:" PÅÃ­kaz KurzÃ­va",legend:"StisknÄte ${italic}"},{name:" PÅÃ­kaz PodtrÅ¾enÃ­",legend:"StisknÄte ${underline}"},{name:" PÅÃ­kaz Odkaz",legend:"StisknÄte ${link}"},{name:" PÅÃ­kaz SkrÃ½t panel nÃ¡strojÅ¯",legend:"StisknÄte ${toolbarCollapse}"},{name:"PÅÃ­kaz pro pÅÃ­stup k pÅedchozÃ­mu prostoru zamÄÅenÃ­",legend:"StisknÄte ${accessPreviousSpace} pro pÅÃ­stup k nejbliÅ¾Å¡Ã­mu nedosaÅ¾itelnÃ©mu prostoru zamÄÅenÃ­ pÅed stÅÃ­Å¡kou, napÅÃ­klad: dva pÅilehlÃ© prvky HR. Pro dosaÅ¾enÃ­ vzdÃ¡lenÃ½ch prostorÅ¯ zamÄÅenÃ­ tuto kombinaci klÃ¡ves opakujte."},
{name:"PÅÃ­kaz pro pÅÃ­stup k dalÅ¡Ã­mu prostoru zamÄÅenÃ­",legend:"StisknÄte ${accessNextSpace} pro pÅÃ­stup k nejbliÅ¾Å¡Ã­mu nedosaÅ¾itelnÃ©mu prostoru zamÄÅenÃ­ po stÅÃ­Å¡ce, napÅÃ­klad: dva pÅilehlÃ© prvky HR. Pro dosaÅ¾enÃ­ vzdÃ¡lenÃ½ch prostorÅ¯ zamÄÅenÃ­ tuto kombinaci klÃ¡ves opakujte."},{name:" NÃ¡povÄda pÅÃ­stupnosti",legend:"StisknÄte ${a11yHelp}"},{name:"VloÅ¾it jako ÄistÃ½ text",legend:"StisknÄte ${pastetext}",legendEdge:"StisknÄte ${pastetext} a pak ${paste}"}]}],tab:"TabulÃ¡tor",pause:"Pauza",capslock:"Caps lock",
escape:"Escape",pageUp:"StrÃ¡nka nahoru",pageDown:"StrÃ¡nka dolÅ¯",leftArrow:"Å ipka vlevo",upArrow:"Å ipka nahoru",rightArrow:"Å ipka vpravo",downArrow:"Å ipka dolÅ¯",insert:"VloÅ¾it",leftWindowKey:"LevÃ¡ klÃ¡vesa Windows",rightWindowKey:"PravÃ¡ klÃ¡vesa Windows",selectKey:"Vyberte klÃ¡vesu",numpad0:"NumerickÃ¡ klÃ¡vesa 0",numpad1:"NumerickÃ¡ klÃ¡vesa 1",numpad2:"NumerickÃ¡ klÃ¡vesa 2",numpad3:"NumerickÃ¡ klÃ¡vesa 3",numpad4:"NumerickÃ¡ klÃ¡vesa 4",numpad5:"NumerickÃ¡ klÃ¡vesa 5",numpad6:"NumerickÃ¡ klÃ¡vesa 6",numpad7:"NumerickÃ¡ klÃ¡vesa 7",
numpad8:"NumerickÃ¡ klÃ¡vesa 8",numpad9:"NumerickÃ¡ klÃ¡vesa 9",multiply:"NumerickÃ¡ klÃ¡vesa nÃ¡sobenÃ­",add:"PÅidat",subtract:"NumerickÃ¡ klÃ¡vesa odeÄÃ­tÃ¡nÃ­",decimalPoint:"DesetinnÃ¡ teÄka",divide:"NumerickÃ¡ klÃ¡vesa dÄlenÃ­",f1:"F1",f2:"F2",f3:"F3",f4:"F4",f5:"F5",f6:"F6",f7:"F7",f8:"F8",f9:"F9",f10:"F10",f11:"F11",f12:"F12",numLock:"Num lock",scrollLock:"Scroll lock",semiColon:"StÅednÃ­k",equalSign:"RovnÃ­tko",comma:"ÄÃ¡rka",dash:"PomlÄka",period:"TeÄka",forwardSlash:"LomÃ­tko",graveAccent:"PÅÃ­zvuk",openBracket:"OtevÅenÃ¡ hranatÃ¡ zÃ¡vorka",
backSlash:"ObrÃ¡cenÃ© lomÃ­tko",closeBracket:"UzavÅenÃ¡ hranatÃ¡ zÃ¡vorka",singleQuote:"JednoduchÃ¡ uvozovka"});