ï»¿/*
 Copyright (c) 2003-2019, CKSource - Frederico Knabben. All rights reserved.
 For licensing, see LICENSE.md or https://ckeditor.com/legal/ckeditor-oss-license
*/
CKEDITOR.plugins.setLang("a11yhelp","de-ch",{title:"Barrierefreiheitinformationen",contents:"Hilfeinhalt. Um den Dialog zu schliessen die Taste ESC drÃ¼cken.",legend:[{name:"Allgemein",items:[{name:"Editorwerkzeugleiste",legend:"DrÃ¼cken Sie ${toolbarFocus} auf der Symbolleiste. Gehen Sie zur nÃ¤chsten oder vorherigen Symbolleistengruppe mit TAB und SHIFT+TAB. Gehen Sie zur nÃ¤chsten oder vorherigen Symbolleiste auf die SchaltflÃ¤che mit dem RECHTS- oder LINKS-Pfeil. DrÃ¼cken Sie die Leertaste oder Eingabetaste, um die SchaltflÃ¤che in der Symbolleiste aktivieren."},
{name:"Editordialog",legend:"Inside a dialog, press TAB to navigate to the next dialog element, press SHIFT+TAB to move to the previous dialog element, press ENTER to submit the dialog, press ESC to cancel the dialog. When a dialog has multiple tabs, the tab list can be reached either with ALT+F10 or with TAB as part of the dialog tabbing order. With tab list focused, move to the next and previous tab with RIGHT and LEFT ARROW, respectively."},{name:"Editor-KontextmenÃ¼",legend:"DÃ¼rcken Sie ${contextMenu} oder die Anwendungstaste um das KontextmenÃ¼ zu Ã¶ffnen. Man kann die Pfeiltasten zum Wechsel benutzen. Mit der Leertaste oder der Enter-Taste kann man den MenÃ¼punkt aufrufen. Schliessen Sie das KontextmenÃ¼ mit der ESC-Taste."},
{name:"Editor-Listenbox",legend:"Innerhalb einer Listenbox kann man mit der TAB-Taste oder den Pfeilrunter-Taste den nÃ¤chsten MenÃ¼eintrag wÃ¤hlen. Mit der SHIFT+TAB Tastenkombination oder der Pfeilhoch-Taste gelangt man zum vorherigen MenÃ¼punkt. Mit der Leertaste oder Enter kann man den MenÃ¼punkt auswÃ¤hlen. DrÃ¼cken Sie ESC zum Verlassen des MenÃ¼s."},{name:"Editor-Elementpfadleiste",legend:"DrÃ¼cken Sie ${elementsPathFocus} um sich durch die Pfadleiste zu bewegen. Um zum nÃ¤chsten Element zu gelangen drÃ¼cken Sie TAB oder die Pfeilrechts-Taste. Zum vorherigen Element gelangen Sie mit der SHIFT+TAB oder der Pfeillinks-Taste. DrÃ¼cken Sie die Leertaste oder Enter um das Element auszuwÃ¤hlen."}]},
{name:"Befehle",items:[{name:"RÃ¼ckgÃ¤ngig-Befehl",legend:"DrÃ¼cken Sie ${undo}"},{name:"Wiederherstellen-Befehl",legend:"DrÃ¼cken Sie ${redo}"},{name:"Fettschrift-Befehl",legend:"DrÃ¼cken Sie ${bold}"},{name:"Kursiv-Befehl",legend:"DrÃ¼cken Sie ${italic}"},{name:"Unterstreichen-Befehl",legend:"DrÃ¼cken Sie ${underline}"},{name:"Link-Befehl",legend:"DrÃ¼cken Sie ${link}"},{name:"Werkzeugleiste einklappen-Befehl",legend:"DrÃ¼cken Sie ${toolbarCollapse}"},{name:"Zugang bisheriger Fokussierung Raumbefehl ",legend:"DrÃ¼cken Sie ${accessPreviousSpace}  auf den am nÃ¤chsten nicht erreichbar Fokus-Abstand vor die EinfÃ¼gemarke zugreifen: zwei benachbarte HR-Elemente. Wiederholen Sie die Tastenkombination um entfernte FokusrÃ¤ume zu erreichen. "},
{name:"Zugang nÃ¤chster Schwerpunkt Raumbefehl ",legend:"DrÃ¼cken Sie $ { accessNextSpace }, um den nÃ¤chsten unerreichbar Fokus Leerzeichen nach dem Cursor zum Beispiel auf: zwei benachbarten HR Elemente. Wiederholen Sie die Tastenkombination zum fernen Fokus Bereiche zu erreichen. "},{name:"Eingabehilfen",legend:"DrÃ¼cken Sie ${a11yHelp}"},{name:" Paste as plain text",legend:"Press ${pastetext}",legendEdge:"Press ${pastetext}, followed by ${paste}"}]}],tab:"Tab",pause:"Pause",capslock:"Feststell",escape:"Escape",
pageUp:"Bild auf",pageDown:"Bild ab",leftArrow:"Linke Pfeiltaste",upArrow:"Obere Pfeiltaste",rightArrow:"Rechte Pfeiltaste",downArrow:"Untere Pfeiltaste",insert:"EinfÃ¼gen",leftWindowKey:"Linke Windowstaste",rightWindowKey:"Rechte Windowstaste",selectKey:"Taste auswÃ¤hlen",numpad0:"Ziffernblock 0",numpad1:"Ziffernblock 1",numpad2:"Ziffernblock 2",numpad3:"Ziffernblock 3",numpad4:"Ziffernblock 4",numpad5:"Ziffernblock 5",numpad6:"Ziffernblock 6",numpad7:"Ziffernblock 7",numpad8:"Ziffernblock 8",numpad9:"Ziffernblock 9",
multiply:"Multiplizieren",add:"Addieren",subtract:"Subtrahieren",decimalPoint:"Punkt",divide:"Dividieren",f1:"F1",f2:"F2",f3:"F3",f4:"F4",f5:"F5",f6:"F6",f7:"F7",f8:"F8",f9:"F9",f10:"F10",f11:"F11",f12:"F12",numLock:"Ziffernblock feststellen",scrollLock:"Rollen",semiColon:"Semikolon",equalSign:"Gleichheitszeichen",comma:"Komma",dash:"Bindestrich",period:"Punkt",forwardSlash:"SchrÃ¤gstrich",graveAccent:"Gravis",openBracket:"Ãffnende eckige Klammer",backSlash:"RÃ¼ckwÃ¤rtsgewandter SchrÃ¤gstrich",closeBracket:"Schliessende eckige Klammer",
singleQuote:"Einfaches AnfÃ¼hrungszeichen"});