ï»¿/*
 Copyright (c) 2003-2019, CKSource - Frederico Knabben. All rights reserved.
 For licensing, see LICENSE.md or https://ckeditor.com/legal/ckeditor-oss-license
*/
CKEDITOR.plugins.setLang("a11yhelp","es-mx",{title:"Instrucciones de accesibilidad",contents:"Contenidos de ayuda. Para cerrar este cuadro de diÃ¡logo presione ESC.",legend:[{name:"General",items:[{name:"Barra de herramientas del editor",legend:"Presione ${toolbarFocus} para navegar a la barra de herramientas. DesplÃ¡cese al grupo de barras de herramientas siguiente y anterior con  SHIFT + TAB. DesplÃ¡cese al botÃ³n siguiente y anterior de la barra de herramientas con FLECHA DERECHA o FLECHA IZQUIERDA. Presione SPACE o ENTER para activar el botÃ³n de la barra de herramientas."},
{name:"Editor de diÃ¡logo",legend:"Dentro de un cuadro de diÃ¡logo, pulse TAB para desplazarse hasta el siguiente elemento de diÃ¡logo, pulse MAYÃS + TAB para desplazarse al elemento de diÃ¡logo anterior, pulse ENTER para enviar el diÃ¡logo, pulse ESC para cancelar el diÃ¡logo. Cuando un cuadro de diÃ¡logo tiene varias pestaÃ±as, se puede acceder a la lista de pestaÃ±as con ALT + F10 o con TAB como parte del orden de tabulaciÃ³n del diÃ¡logo. Con la lista de tabuladores enfocada, mueva a la pestaÃ±a siguiente y anterior con las flechas DERECHA y IZQUIERDA, respectivamente."},
{name:"MenÃº contextual del editor",legend:"Presione ${contextMenu} o CLAVE DE APLICACIÃN para abrir el menÃº contextual. A continuaciÃ³n, vaya a la siguiente opciÃ³n del menÃº con TAB o DOWN ARROW. DesplÃ¡cese a la opciÃ³n anterior con SHIFT + TAB o FLECHA ARRIBA. Presione SPACE o ENTER para seleccionar la opciÃ³n del menÃº. Abra el submenÃº de la opciÃ³n actual con ESPACIO o ENTER o FLECHA DERECHA. Vuelva al elemento de menÃº principal con ESC o FLECHA IZQUIERDA. Cerrar el menÃº contextual con ESC."},{name:"Editor de cuadro de lista",
legend:"Dentro de un cuadro de lista, mueva al siguiente elemento de lista con TAB O FLECHA ABAJO. Mueva al elemento anterior de la lista con MAYÃS + TAB o FLECHA ARRIBA. Presione SPACE o ENTER para seleccionar la opciÃ³n de lista. Presione ESC para cerrar el cuadro de lista."},{name:"Barra de ruta del elemento del editor",legend:"Presione ${elementsPathFocus} para navegar a la barra de ruta de elementos. DesplÃ¡cese al siguiente botÃ³n de elemento con TAB o FLECHA DERECHA. DesplÃ¡cese al botÃ³n anterior con SHIFT + TAB o FLECHA IZQUIERDA. Presione SPACE o ENTER para seleccionar el elemento en el editor."}]},
{name:"Comandos",items:[{name:"Comando deshacer",legend:"Presiona ${undo}"},{name:"Comando rehacer",legend:"Presiona ${redo}"},{name:"Comando negrita",legend:"Presiona ${bold}"},{name:"Comando cursiva",legend:"Presiona {italic}"},{name:"Comando subrayado",legend:"Presiona ${underline}"},{name:"Comando enlace",legend:"Presiona ${link}"},{name:"Comando colapsar barra de herramientas",legend:"Presiona ${toolbarCollapse}"},{name:"Acceda al comando de espacio de enfoque anterior",legend:"Presione ${accessPreviousSpace} para acceder al espacio de enfoque inaccesible mÃ¡s cercano antes del cursor, por ejemplo: dos elementos HR adyacentes. Repita la combinaciÃ³n de teclas para alcanzar los espacios de enfoque distantes."},
{name:"Acceder al siguiente comando de espacio de enfoque",legend:"Pulse ${accessNextSpace} para acceder al espacio de enfoque mÃ¡s cercano inaccesible despuÃ©s del cursor, por ejemplo: dos elementos HR adyacentes. Repita la combinaciÃ³n de teclas para alcanzar los espacios de enfoque distantes."},{name:"Ayuda de accesibilidad",legend:"Presiona ${a11yHelp}"},{name:" Paste as plain text",legend:"Press ${pastetext}",legendEdge:"Press ${pastetext}, followed by ${paste}"}]}],tab:"Tabulador",pause:"Pausa",
capslock:"MayÃºsculas",escape:"Escape",pageUp:"PÃ¡gina arriba",pageDown:"PÃ¡gina abajo",leftArrow:"Flecha izquierda",upArrow:"Flecha arriba",rightArrow:"Flecha derecha",downArrow:"Flecha abajo",insert:"Insertar",leftWindowKey:"Tecla izquierda de Windows",rightWindowKey:"Tecla derecha de Windows",selectKey:"Tecla de selecciÃ³n",numpad0:"Teclado numÃ©rico 0",numpad1:"Teclado numÃ©rico 1",numpad2:"Teclado numÃ©rico 2",numpad3:"Teclado numÃ©rico 3",numpad4:"Teclado numÃ©rico 4",numpad5:"Teclado numÃ©rico 5",numpad6:"Teclado numÃ©rico 6",
numpad7:"Teclado numÃ©rico 7",numpad8:"Teclado numÃ©rico 8",numpad9:"Teclado numÃ©rico 9",multiply:"Multiplicar",add:"Sumar",subtract:"Restar",decimalPoint:"Punto decimal",divide:"Dividir",f1:"F1",f2:"F2",f3:"F3",f4:"F4",f5:"F5",f6:"F6",f7:"F7",f8:"F8",f9:"F9",f10:"F10",f11:"F11",f12:"F12",numLock:"NÃºmeros",scrollLock:"Bloqueo de desplazamiento",semiColon:"punto y coma",equalSign:"Signo igual",comma:"Coma",dash:"GuiÃ³n",period:"Espacio",forwardSlash:"Diagonal",graveAccent:"Acento grave",openBracket:"Abrir parÃ©ntesis",
backSlash:"Diagonal invertida",closeBracket:"Cerrar parÃ©ntesis",singleQuote:"Comillas simple"});