ï»¿/*
 Copyright (c) 2003-2019, CKSource - Frederico Knabben. All rights reserved.
 For licensing, see LICENSE.md or https://ckeditor.com/legal/ckeditor-oss-license
*/
CKEDITOR.plugins.setLang("a11yhelp","et",{title:"HÃµlbustuste kasutamise juhised",contents:"Abi sisu. Selle dialoogi sulgemiseks vajuta ESC klahvi.",legend:[{name:"Ãldine",items:[{name:"Redaktori tÃ¶Ã¶riistariba",legend:"TÃ¶Ã¶riistaribale navigeerimiseks vajuta ${toolbarFocus}. JÃ¤rgmisele vÃµi eelmisele tÃ¶Ã¶riistagrupile liikumiseks vajuta TAB vÃµi SHIFT+TAB. JÃ¤rgmisele vÃµi eelmisele tÃ¶Ã¶riistaribale liikumiseks vajuta PAREMALE NOOLT vÃµi VASAKULE NOOLT. Vajuta TÃHIKUT vÃµi ENTERIT, et tÃ¶Ã¶riistariba nupp aktiveerida."},
{name:"Redaktori dialoog",legend:"Dialoogi sees vajuta TAB, et liikuda jÃ¤rgmisele dialoogi elemendile, SHIFT+TAB, et liikuda tagasi, vajuta ENTER dialoogi kinnitamiseks, ESC dialoogi sulgemiseks. Kui dialoogil on mitu kaarti/sakki, pÃ¤Ã¤seb kaartide nimekirjale ligi ALT+F10 klahvidega vÃµi TABi kasutades. Kui kaartide nimekiri on fookuses, saab jÃ¤rgmisele ja eelmisele kaardile vastavalt PAREMALE ja VASAKULE NOOLTEGA."},{name:"Redaktori kontekstimenÃ¼Ã¼",legend:"Vajuta ${contextMenu} vÃµi RAKENDUSE KLAHVI, et avada kontekstimenÃ¼Ã¼. Siis saad liikuda jÃ¤rgmisele reale TAB klahvi vÃµi ALLA NOOLEGA. Eelmisele valikule saab liikuda SHIFT+TAB klahvidega vÃµi ÃLES NOOLEGA. Kirje valimiseks vajuta TÃHIK vÃµi ENTER. AlamenÃ¼Ã¼ saab valida kui alammenÃ¼Ã¼ kirje on aktiivne ja valida kas TÃHIK, ENTER vÃµi PAREMALE NOOL. Ãlemisse menÃ¼Ã¼sse tagasi saab ESC klahvi vÃµi VASAKULE NOOLEGA. MenÃ¼Ã¼ saab sulgeda ESC klahviga."},
{name:"Redaktori loetelu kast",legend:"Loetelu kasti sees saab jÃ¤rgmisele reale liikuda TAB klahvi vÃµi ALLANOOLEGA. Eelmisele reale saab liikuda SHIFT+TAB klahvide vÃµi ÃLESNOOLEGA. Kirje valimiseks vajuta TÃHIKUT vÃµi ENTERIT. Loetelu kasti sulgemiseks vajuta ESC klahvi."},{name:"Redaktori elementide jÃ¤rjestuse riba",legend:"Vajuta ${elementsPathFocus} et liikuda asukoha ribal asuvatele elementidele. JÃ¤rgmise elemendi nupule saab liikuda TAB klahviga vÃµi PAREMALE NOOLEGA. Eelmisele nupule saab liikuda SHIFT+TAB klahvi vÃµi VASAKULE NOOLEGA. Vajuta TÃHIK vÃµi ENTER, et valida redaktoris vastav element."}]},
{name:"KÃ¤sud",items:[{name:"TÃ¼histamise kÃ¤sk",legend:"Vajuta ${undo}"},{name:"Uuesti tegemise kÃ¤sk",legend:"Vajuta ${redo}"},{name:"Rasvase kÃ¤sk",legend:"Vajuta ${bold}"},{name:"Kursiivi kÃ¤sk",legend:"Vajuta ${italic}"},{name:"Allajoonimise kÃ¤sk",legend:"Vajuta ${underline}"},{name:"Lingi kÃ¤sk",legend:"Vajuta ${link}"},{name:"TÃ¶Ã¶riistariba peitmise kÃ¤sk",legend:"Vajuta ${toolbarCollapse}"},{name:"LigipÃ¤Ã¤s eelmisele fookuskohale",legend:"Vajuta ${accessPreviousSpace}, et pÃ¤Ã¤seda ligi lÃ¤himale liigipÃ¤Ã¤sematule fookuskohale enne kursorit, nÃ¤iteks: kahe jÃ¤rjestikuse HR elemendi vahele. Vajuta kombinatsiooni uuesti, et pÃ¤Ã¤seda ligi kaugematele kohtadele."},
{name:"LigipÃ¤Ã¤s jÃ¤rgmisele fookuskohale",legend:"Vajuta ${accessNextSpace}, et pÃ¤Ã¤seda ligi lÃ¤himale liigipÃ¤Ã¤sematule fookuskohale pÃ¤rast kursorit, nÃ¤iteks: kahe jÃ¤rjestikuse HR elemendi vahele. Vajuta kombinatsiooni uuesti, et pÃ¤Ã¤seda ligi kaugematele kohtadele."},{name:"HÃµlbustuste abi",legend:"Vajuta ${a11yHelp}"},{name:"Asetamine tavalise tekstina",legend:"Vajuta ${pastetext}",legendEdge:"Vajuta ${pastetext}, siis ${paste}"}]}],tab:"Tabulaator",pause:"Paus",capslock:"TÃµstulukk",escape:"Paoklahv",
pageUp:"Leht Ã¼les",pageDown:"Leht alla",leftArrow:"Nool vasakule",upArrow:"Nool Ã¼les",rightArrow:"Nool paremale",downArrow:"Nool alla",insert:"Sisetamine",leftWindowKey:"Vasak Windowsi klahv",rightWindowKey:"Parem Windowsi klahv",selectKey:"Vali klahv",numpad0:"Numbriala 0",numpad1:"Numbriala 1",numpad2:"Numbriala 2",numpad3:"Numbriala 3",numpad4:"Numbriala 4",numpad5:"Numbriala 5",numpad6:"Numbriala 6",numpad7:"Numbriala 7",numpad8:"Numbriala 8",numpad9:"Numbriala 9",multiply:"Korrutus",add:"Pluss",
subtract:"Miinus",decimalPoint:"Koma",divide:"Jagamine",f1:"F1",f2:"F2",f3:"F3",f4:"F4",f5:"F5",f6:"F6",f7:"F7",f8:"F8",f9:"F9",f10:"F10",f11:"F11",f12:"F12",numLock:"Numbrilukk",scrollLock:"Kerimislukk",semiColon:"Semikoolon",equalSign:"VÃµrdusmÃ¤rk",comma:"Koma",dash:"Sidekriips",period:"Punkt",forwardSlash:"Kaldkriips",graveAccent:"RÃµhumÃ¤rk",openBracket:"Algussulg",backSlash:"Kurakaldkriips",closeBracket:"LÃµpusulg",singleQuote:"Ãlakoma"});