ï»¿/*
 Copyright (c) 2003-2019, CKSource - Frederico Knabben. All rights reserved.
 For licensing, see LICENSE.md or https://ckeditor.com/legal/ckeditor-oss-license
*/
CKEDITOR.plugins.setLang("a11yhelp","he",{title:"×××¨×××ª × ×××©××ª",contents:"×××¨×××ª × ×××©××ª. ××¡×××¨× ×××¥ ××¡×§×××¤ (ESC).",legend:[{name:"××××",items:[{name:"×¡×¨×× ×××××",legend:"×××¥ ×¢× ${toolbarFocus} ××× ×× ××× ××¡×¨×× ×××××. ×¢×××¨ ×××¤×ª××¨ ××× ×¢× ××§×© ×××× (TAB) ×× ××¥ ×©××××. ×¢×××¨ ×××¤×ª××¨ ××§××× ×¢× ××§×© ××©××¤× (SHIFT) + ××× (TAB) ×× ××¥ ××× ×. ×××¥ ×¨××× ×× ×× ××¨ (ENTER) ××× ×××¤×¢×× ××ª ×××¤×ª××¨ ×× ×××¨."},{name:"×××××××× (×××× ××ª ×ª×©×××)",legend:"Inside a dialog, press TAB to navigate to the next dialog element, press SHIFT+TAB to move to the previous dialog element, press ENTER to submit the dialog, press ESC to cancel the dialog. When a dialog has multiple tabs, the tab list can be reached either with ALT+F10 or with TAB as part of the dialog tabbing order. With tab list focused, move to the next and previous tab with RIGHT and LEFT ARROW, respectively."},
{name:"×ª×¤×¨×× ×××§×©×¨ (Context Menu)",legend:"×××¥ ${contextMenu} ×× APPLICATION KEY××× ××¤×ª×× ××ª ×ª×¤×¨×× ×××§×©×¨. ×¢×××¨ ×××¤×©×¨××ª ×××× ×¢× ××× (TAB) ×× ××¥ ××××. ×¢×××¨ ×××¤×©×¨××ª ××§××××ª ×¢× ×©××¤× (SHIFT) + ××× (TAB) ×× ××¥ ×××¢××. ×××¥ ×¨××× ×× ×× ××¨ (ENTER) ××× ×××××¨ ××ª ×××¤×©×¨××ª. ×¤×ª× ××ª ×ª×ª ××ª×¤×¨×× (Sub-menu) ×©× ×××¤×©×¨××ª ×× ×××××ª ×¢× ×¨××× ×× ×× ××¨ (ENTER) ×× ××¥ ×©××××. ××××¨ ××ª×¤×¨×× ××× ×¢× ××¡×§×××¤ (ESC) ×× ××¥ ×©××××. ×¡×××¨ ××ª ×ª×¤×¨×× ×××§×©×¨ ×¢× ××¡×§×××¤ (ESC)."},{name:"×ª×¤×¨×××× ×¦×¤×× (List boxes)",legend:"Inside a list-box, move to next list item with TAB OR DOWN ARROW. Move to previous list item with SHIFT+TAB or UP ARROW. Press SPACE or ENTER to select the list option. Press ESC to close the list-box."},
{name:"×¢×¥ ×××× ××× (Elements Path)",legend:"×××¥ ${elementsPathFocus} ××× ×× ××× ××¢×¥ ××××× ×××. ×¢×××¨ ××¤×¨×× ××× ×¢× ××× (TAB) ×× ××¥ ××× ×. ×¢×××¨ ××¤×¨×× ××§××× ×¢× ×©××¤× (SHIFT) + ××× (TAB) ×× ××¥ ×©××××. ×××¥ ×¨××× ×× ×× ××¨ (ENTER) ××× ×××××¨ ××ª ××××× × ××¢××¨×."}]},{name:"×¤×§××××ª",items:[{name:" ××××× ×¦×¢× ×××¨××",legend:"×××¥ ${undo}"},{name:" ×××¨× ×¢× ×¦×¢× ×××¨××",legend:"×××¥ ${redo}"},{name:" ××××©×",legend:"×××¥ ${bold}"},{name:" ×××××",legend:"×××¥ ${italic}"},{name:" ×××¡×¤×ª ×§× ×ª××ª××",legend:"×××¥ ${underline}"},{name:" ×××¡×¤×ª ××× ×§",
legend:"×××¥ ${link}"},{name:" ×××××¥ ×¡×¨×× ×××××",legend:"×××¥ ${toolbarCollapse}"},{name:"×××©× ××××§×× ××××§×× ××§×××",legend:"×××¥ ${accessPreviousSpace} ××× ×××©×ª ××××§×× ××××§×× ×××-× ×××© ××§×¨×× ××¤× × ××¡××, ×××©× ××× ×©× × ×××× ××× ×¡××××× ××¡×× HR. ××××¨ ×¢× ×¦××¨××£ ××§×©×× ×× ××× ×××××¢ ×××§××××ª ×××§×× ×¨×××§×× ×××ª×¨."},{name:"×××©× ××××§×× ××××§×× ×××",legend:"×××¥ ${accessNextSpace} ××× ×××©×ª ××××§×× ××××§×× ×××-× ×××© ××§×¨×× ×××¨× ××¡××, ×××©× ××× ×©× × ×××× ××× ×¡××××× ××¡×× HR. ××××¨ ×¢× ×¦××¨××£ ××§×©×× ×× ××× ×××××¢ ×××§××××ª ×××§×× ×¨×××§×× ×××ª×¨."},
{name:" ×××¨×××ª × ×××©××ª",legend:"×××¥ ${a11yHelp}"},{name:" Paste as plain text",legend:"Press ${pastetext}",legendEdge:"Press ${pastetext}, followed by ${paste}"}]}],tab:"Tab",pause:"Pause",capslock:"Caps Lock",escape:"Escape",pageUp:"Page Up",pageDown:"Page Down",leftArrow:"××¥ ×©××××",upArrow:"××¥ ×××¢××",rightArrow:"××¥ ×××× ×",downArrow:"××¥ ××××",insert:"××× ×¡",leftWindowKey:"Left Windows key",rightWindowKey:"Right Windows key",selectKey:"×××¨ ××§×©",numpad0:"Numpad 0",numpad1:"Numpad 1",numpad2:"Numpad 2",
numpad3:"Numpad 3",numpad4:"Numpad 4",numpad5:"Numpad 5",numpad6:"Numpad 6",numpad7:"Numpad 7",numpad8:"Numpad 8",numpad9:"Numpad 9",multiply:"Multiply",add:"×××¡×£",subtract:"Subtract",decimalPoint:"Decimal Point",divide:"Divide",f1:"F1",f2:"F2",f3:"F3",f4:"F4",f5:"F5",f6:"F6",f7:"F7",f8:"F8",f9:"F9",f10:"F10",f11:"F11",f12:"F12",numLock:"Num Lock",scrollLock:"Scroll Lock",semiColon:"Semicolon",equalSign:"Equal Sign",comma:"Comma",dash:"Dash",period:"Period",forwardSlash:"×¡×××©",graveAccent:"Grave Accent",
openBracket:"Open Bracket",backSlash:"×¡×××© ××¤××",closeBracket:"Close Bracket",singleQuote:"×¦×××× ××××"});