ï»¿/*
 Copyright (c) 2003-2019, CKSource - Frederico Knabben. All rights reserved.
 For licensing, see LICENSE.md or https://ckeditor.com/legal/ckeditor-oss-license
*/
CKEDITOR.plugins.setLang("a11yhelp","hu",{title:"KisegÃ­tÅ utasÃ­tÃ¡sok",contents:"SÃºgÃ³ tartalmak. A pÃ¡rbeszÃ©dablak bezÃ¡rÃ¡sÃ¡hoz nyomjon ESC-et.",legend:[{name:"ÃltalÃ¡nos",items:[{name:"SzerkesztÅ EszkÃ¶ztÃ¡r",legend:"Nyomjon ${toolbarFocus} hogy kijelÃ¶lje az eszkÃ¶ztÃ¡rat. A kÃ¶vetkezÅ Ã©s elÅzÅ eszkÃ¶ztÃ¡r csoporthoz a TAB Ã©s SHIFT+TAB-al juthat el. A kÃ¶vetkezÅ Ã©s elÅzÅ eszkÃ¶ztÃ¡r gombhoz a BAL NYÃL vagy JOBB NYÃL gombbal juthat el. Nyomjon SPACE-t vagy ENTER-t hogy aktivÃ¡lja az eszkÃ¶ztÃ¡r gombot."},{name:"SzerkeszÅ pÃ¡rbeszÃ©d ablak",
legend:"PÃ¡rbeszÃ©dablakban nyomjon TAB-ot a kÃ¶vetkezÅ pÃ¡rbeszÃ©dmezÅhÃ¶z ugrÃ¡shoz, nyomjon SHIFT + TAB-ot az elÅzÅ mezÅhÃ¶z ugrÃ¡shoz, nyomjon ENTER-t a pÃ¡rbeszÃ©dablak elfogadÃ¡sÃ¡hoz, nyomjon ESC-et a pÃ¡rbeszÃ©dablak elvetÃ©sÃ©hez. Azokhoz a pÃ¡rbeszÃ©dablakokhoz, amik tÃ¶bb fÃ¼let tartalmaznak, nyomjon ALT + F10-et vagy TAB-ot hogy a fÃ¼lekre ugorjon. EzutÃ¡n a TAB-al vagy a JOBB NYÃLLAL a kÃ¶vetkezÅ fÃ¼lre ugorhat."},{name:"SzerkesztÅ helyi menÃ¼",legend:"Nyomjon ${contextMenu}-t vagy ALKALMAZÃS BILLENTYÅ°T a helyi menÃ¼ megnyitÃ¡sÃ¡hoz. EzutÃ¡n a kÃ¶vetkezÅ menÃ¼pontra lÃ©phet a TAB vagy LEFELÃ NYÃLLAL. Az elÅzÅ opciÃ³t a SHIFT+TAB vagy FELFELÃ NYÃLLAL Ã©rheti el. Nyomjon SPACE-t vagy ENTER-t a menÃ¼pont kivÃ¡lasztÃ¡sÃ¡hoz. A jelenlegi menÃ¼pont almenÃ¼jÃ©nek megnyitÃ¡sÃ¡hoz nyomjon SPACE-t vagy ENTER-t, vagy JOBB NYILAT. A fÅmenÃ¼hÃ¶z valÃ³ visszatÃ©rÃ©shez nyomjon ESC-et vagy BAL NYILAT. A helyi menÃ¼ bezÃ¡rÃ¡sa az ESC billentyÅ±vel lehetsÃ©ges."},
{name:"SzerkesztÅ lista",legend:"A listÃ¡n belÃ¼l a kÃ¶vetkezÅ elemre a TAB vagy LEFELÃ NYÃLLAL mozoghat. Az elÅzÅ elem kivÃ¡lasztÃ¡sÃ¡hoz nyomjon SHIFT+TAB-ot vagy FELFELÃ NYILAT. Nyomjon SPACE-t vagy ENTER-t az elem kivÃ¡lasztÃ¡sÃ¡hoz. Az ESC billentyÅ± megnyomÃ¡sÃ¡val bezÃ¡rhatja a listÃ¡t."},{name:"SzerkesztÅ elem utak sÃ¡v",legend:"Nyomj ${elementsPathFocus} hogy kijelÃ¶ld a elemek Ãºt sÃ¡vjÃ¡t. A kÃ¶vetkezÅ elem gombhoz a TAB-al vagy a JOBB NYÃLLAL juthatsz el. Az elÅzÅ gombhoz a SHIFT+TAB vagy BAL NYÃLLAL mehetsz. A SPACE vagy ENTER billentyÅ±vel kivÃ¡laszthatod az elemet a szerkesztÅben."}]},
{name:"Parancsok",items:[{name:"Parancs visszavonÃ¡sa",legend:"Nyomj ${undo}"},{name:"Parancs megismÃ©tlÃ©se",legend:"Nyomjon ${redo}"},{name:"FÃ©lkÃ¶vÃ©r parancs",legend:"Nyomjon ${bold}"},{name:"DÅlt parancs",legend:"Nyomjon ${italic}"},{name:"AlÃ¡hÃºzott parancs",legend:"Nyomjon ${underline}"},{name:"Link parancs",legend:"Nyomjon ${link}"},{name:"SzerkesztÅsÃ¡v Ã¶sszecsukÃ¡sa parancs",legend:"Nyomjon ${toolbarCollapse}"},{name:"HozzÃ¡fÃ©rÃ©s az elÅzÅ fÃ³kusz helyhez parancs",legend:"Nyomj ${accessNextSpace} hogy hozzÃ¡fÃ©rj a legkÃ¶zelebbi elÃ©rhetetlen fÃ³kusz helyhez a hiÃ¡nyjel elÅtt, pÃ©ldÃ¡ul: kÃ©t szomszÃ©dos HR elemhez. IsmÃ©teld meg a billentyÅ±kombinÃ¡ciÃ³t hogy megtalÃ¡ld a tÃ¡volabbi fÃ³kusz helyeket."},
{name:"HozzÃ¡fÃ©rÃ©s a kÃ¶vetkezÅ fÃ³kusz helyhez parancs",legend:"Nyomj ${accessNextSpace} hogy hozzÃ¡fÃ©rj a legkÃ¶zelebbi elÃ©rhetetlen fÃ³kusz helyhez a hiÃ¡nyjel utÃ¡n, pÃ©ldÃ¡ul: kÃ©t szomszÃ©dos HR elemhez. IsmÃ©teld meg a billentyÅ±kombinÃ¡ciÃ³t hogy megtalÃ¡ld a tÃ¡volabbi fÃ³kusz helyeket."},{name:"KisegÃ­tÅ sÃºgÃ³",legend:"Nyomjon ${a11yHelp}"},{name:"BeillesztÃ©s egyszerÅ± szÃ¶vegkÃ©nt",legend:"Nyomja meg: ${pastetext}",legendEdge:"Nyomjon ${pastetext}-t, majd ${paste}-t"}]}],tab:"Tab",pause:"Pause",capslock:"Caps Lock",
escape:"Escape",pageUp:"Page Up",pageDown:"Page Down",leftArrow:"balra nyÃ­l",upArrow:"felfelÃ© nyÃ­l",rightArrow:"jobbra nyÃ­l",downArrow:"lefelÃ© nyÃ­l",insert:"Insert",leftWindowKey:"bal Windows-billentyÅ±",rightWindowKey:"jobb Windows-billentyÅ±",selectKey:"BillentyÅ± vÃ¡lasztÃ¡sa",numpad0:"SzÃ¡mbillentyÅ±k 0",numpad1:"SzÃ¡mbillentyÅ±k 1",numpad2:"SzÃ¡mbillentyÅ±k 2",numpad3:"SzÃ¡mbillentyÅ±k 3",numpad4:"SzÃ¡mbillentyÅ±k 4",numpad5:"SzÃ¡mbillentyÅ±k 5",numpad6:"SzÃ¡mbillentyÅ±k 6",numpad7:"SzÃ¡mbillentyÅ±k 7",numpad8:"SzÃ¡mbillentyÅ±k 8",
numpad9:"SzÃ¡mbillentyÅ±k 9",multiply:"SzorzÃ¡s",add:"HozzÃ¡adÃ¡s",subtract:"KivonÃ¡s",decimalPoint:"Tizedespont",divide:"OsztÃ¡s",f1:"F1",f2:"F2",f3:"F3",f4:"F4",f5:"F5",f6:"F6",f7:"F7",f8:"F8",f9:"F9",f10:"F10",f11:"F11",f12:"F12",numLock:"Num Lock",scrollLock:"Scroll Lock",semiColon:"PontosvesszÅ",equalSign:"EgyenlÅsÃ©gjel",comma:"VesszÅ",dash:"KÃ¶tÅjel",period:"Pont",forwardSlash:"Perjel",graveAccent:"VisszafelÃ© dÅlÅ Ã©kezet",openBracket:"NyitÃ³ szÃ¶gletes zÃ¡rÃ³jel",backSlash:"fordÃ­tott perjel",closeBracket:"ZÃ¡rÃ³ szÃ¶gletes zÃ¡rÃ³jel",
singleQuote:"szimpla idÃ©zÅjel"});