ï»¿/*
 Copyright (c) 2003-2019, CKSource - Frederico Knabben. All rights reserved.
 For licensing, see LICENSE.md or https://ckeditor.com/legal/ckeditor-oss-license
*/
CKEDITOR.plugins.setLang("a11yhelp","km",{title:"Accessibility Instructions",contents:"áá¶áá·áá¶âáááá½áá áá¾áááá¸âáá·áâáááá¶ááâááá áá¼áâáá»á ESC á",legend:[{name:"áá¼áá",items:[{name:"ááá¶áâá§áááááâáááááá·áá¸âáá·áááá",legend:"Press ${toolbarFocus} to navigate to the toolbar. Move to the next and previous toolbar group with TAB and SHIFT+TAB. Move to the next and previous toolbar button with RIGHT ARROW or LEFT ARROW. Press SPACE or ENTER to activate the toolbar button."},{name:"áááá¶ááâáááááá·áá¸áá·áááá",legend:"Inside a dialog, press TAB to navigate to the next dialog element, press SHIFT+TAB to move to the previous dialog element, press ENTER to submit the dialog, press ESC to cancel the dialog. When a dialog has multiple tabs, the tab list can be reached either with ALT+F10 or with TAB as part of the dialog tabbing order. With tab list focused, move to the next and previous tab with RIGHT and LEFT ARROW, respectively."},
{name:"ááá¸áá»áááá·ááá¢áááááááááá½á",legend:"Press ${contextMenu} or APPLICATION KEY to open context-menu. Then move to next menu option with TAB or DOWN ARROW. Move to previous option with SHIFT+TAB or UP ARROW. Press SPACE or ENTER to select the menu option. Open sub-menu of current option with SPACE or ENTER or RIGHT ARROW. Go back to parent menu item with ESC or LEFT ARROW. Close context menu with ESC."},{name:"áááá¢ááááááá¸á¢áááááááááá½á",legend:"Inside a list-box, move to next list item with TAB OR DOWN ARROW. Move to previous list item with SHIFT+TAB or UP ARROW. Press SPACE or ENTER to select the list option. Press ESC to close the list-box."},
{name:"Editor Element Path Bar",legend:"Press ${elementsPathFocus} to navigate to the elements path bar. Move to next element button with TAB or RIGHT ARROW. Move to previous button with SHIFT+TAB or LEFT ARROW. Press SPACE or ENTER to select the element in editor."}]},{name:"áá¶áááááááá¶",items:[{name:"áá¶áâááááá¶âáá·ááááá¾áá·á",legend:"áá»á ${undo}"},{name:"áá¶áááááá¶âáááá¾áá·á",legend:"áá»á ${redo}"},{name:"áá¶áááááá¶âá¢ááááâáá·á",legend:"áá»á ${bold}"},{name:"áá¶áááááá¶âá¢ááááâááááá",legend:"áá»á ${italic}"},{name:"áá¶áááááááá¶âááááá¶ááâáá¸ááááá",
legend:"áá»á ${underline}"},{name:"áá¶áááááááá¶âááá",legend:"áá»á ${link}"},{name:" Toolbar Collapse command",legend:"Press ${toolbarCollapse}"},{name:" Access previous focus space command",legend:"Press ${accessPreviousSpace} to access the closest unreachable focus space before the caret, for example: two adjacent HR elements. Repeat the key combination to reach distant focus spaces."},{name:" Access next focus space command",legend:"Press ${accessNextSpace} to access the closest unreachable focus space after the caret, for example: two adjacent HR elements. Repeat the key combination to reach distant focus spaces."},
{name:"áááá½áâáá¸âáá¶áâáá¶ááááá½á",legend:"áá½á ${a11yHelp}"},{name:" Paste as plain text",legend:"Press ${pastetext}",legendEdge:"Press ${pastetext}, followed by ${paste}"}]}],tab:"Tab",pause:"ááá¢á¶á",capslock:"Caps Lock",escape:"áá¶áááá",pageUp:"áááááâáá¾",pageDown:"áááááâááááá",leftArrow:"áááá½áâááááá",upArrow:"áááá½áâáá¾",rightArrow:"áááá½áâáááá¶á",downArrow:"áááá½áâááááá",insert:"ááááá¼á",leftWindowKey:"Left Windows key",rightWindowKey:"Right Windows key",selectKey:"áááá¾áâáááá¶ááâáá»á",numpad0:"Numpad 0",numpad1:"Numpad 1",
numpad2:"Numpad 2",numpad3:"Numpad 3",numpad4:"Numpad 4",numpad5:"Numpad 5",numpad6:"Numpad 6",numpad7:"Numpad 7",numpad8:"Numpad 8",numpad9:"Numpad 9",multiply:"áá»á",add:"áááááá",subtract:"áá",decimalPoint:"áááá»ááááá¶á",divide:"ááá",f1:"F1",f2:"F2",f3:"F3",f4:"F4",f5:"F5",f6:"F6",f7:"F7",f8:"F8",f9:"F9",f10:"F10",f11:"F11",f12:"F12",numLock:"Num Lock",scrollLock:"áá·áâáááá·á",semiColon:"áá»áâááááá",equalSign:"ááááá¶âá¢áºááá¼",comma:"ááááá",dash:"Dash",period:"áá»á",forwardSlash:"Forward Slash",graveAccent:"Grave Accent",
openBracket:"ááááááâáá¾á",backSlash:"Backslash",closeBracket:"ááááááâáá·á",singleQuote:"ááááááâáá½á"});