ï»¿/*
 Copyright (c) 2003-2019, CKSource - Frederico Knabben. All rights reserved.
 For licensing, see LICENSE.md or https://ckeditor.com/legal/ckeditor-oss-license
*/
CKEDITOR.plugins.setLang("a11yhelp","lv",{title:"PieejamÄ«bas instrukcija",contents:"PalÄ«dzÄ«bas saturs. Lai aizvÄrtu ciet Å¡o dialogu nospiediet ESC.",legend:[{name:"Galvenais",items:[{name:"Redaktora rÄ«kjosla",legend:"Nospiediet ${toolbarFocus} lai pÄrvietotos uz rÄ«kjoslu. Lai pÄrvietotos uz nÄkoÅ¡o vai iepriekÅ¡Äjo rÄ«kjoslas grupu izmantojiet pogu TAB un SHIFT+TAB. Lai pÄrvietotos uz nÄkoÅ¡o vai iepriekÅ¡Äjo rÄ«kjoslas pogu izmantojiet Kreiso vai Labo bultiÅu. Nospiediet Atstarpi vai ENTER lai aktivizÄtu rÄ«kjosla pogu."},
{name:"Redaktora dialoga  logs",legend:"Inside a dialog, press TAB to navigate to the next dialog element, press SHIFT+TAB to move to the previous dialog element, press ENTER to submit the dialog, press ESC to cancel the dialog. When a dialog has multiple tabs, the tab list can be reached either with ALT+F10 or with TAB as part of the dialog tabbing order. With tab list focused, move to the next and previous tab with RIGHT and LEFT ARROW, respectively."},{name:"Redaktora satura izvÄle",legend:"Nospiediet ${contextMenu} vai APPLICATION KEY lai atvÄrtu satura izvÄlni. Lai pÄrvietotos uz nÄkoÅ¡o izvÄlnes opciju izmantojiet pogu TAB vai pogu BultiÅu uz leju. Lai pÄrvietotos uz iepriekÅ¡Äjo opciju izmantojiet  SHIFT+TAB vai pogu BultiÅa uz augÅ¡u. Nospiediet SPACE vai ENTER lai izvelÄtos izvÄlnes opciju. Atveriet tekoÅ¡ajÄ opcija apakÅ¡izvÄlni ar SAPCE vai ENTER ka ari to var izdarÄ«t ar Labo bultiÅu. Lai atgrieztos atpakaÄ¼ uz sakuma izvÄlni nospiediet ESC vai Kreiso bultiÅu. Lai aizvÄrtu ciet izvÄlnes saturu nospiediet ESC."},
{name:"Redaktora saraksta lauks",legend:"Saraksta laukÄ, lai pÄrvietotos uz nÄkoÅ¡o saraksta elementu nospiediet TAB vai pogu BultiÅa uz leju. Lai pÄrvietotos uz iepriekÅ¡Äjo saraksta elementu nospiediet SHIFT+TAB vai pogu BultiÅa uz augÅ¡u. Nospiediet SPACE vai ENTER lai izvÄlÄtos saraksta opcijas. Nospiediet ESC lai aizvÄrtu saraksta lauku."},{name:"Redaktora elementa ceÄ¼a josla",legend:"Nospiediet ${elementsPathFocus} lai pÄrvietotos uz elementa ceÄ¼a joslu. Lai pÄrvietotos uz nÄkoÅ¡o elementa pogu izmantojiet TAB vai Labo bultiÅu. Lai pÄrvietotos uz iepriekÅ¡Äjo elementa pogu izmantojiet SHIFT+TAB vai Kreiso bultiÅu. Nospiediet SPACE vai ENTER lai izvÄlÄtos elementu redaktorÄ."}]},
{name:"Komandas",items:[{name:"Komanda atcelt darbÄ«bu",legend:"Nospiediet ${undo}"},{name:"Komanda atkÄrtot darbÄ«bu",legend:"Nospiediet ${redo}"},{name:"Treknraksta komanda",legend:"Nospiediet ${bold}"},{name:"KursÄ«va komanda",legend:"Nospiediet ${italic}"},{name:"ApakÅ¡svÄ«tras komanda ",legend:"Nospiediet ${underline}"},{name:"Hipersaites komanda",legend:"Nospiediet ${link}"},{name:"RÄ«kjoslas aizvÄrÅ¡anas komanda",legend:"Nospiediet ${toolbarCollapse}"},{name:"PiekÄ¼Å«t iepriekÅ¡Äjai fokusa vietas komandai",
legend:"Nospiediet ${accessPreviousSpace} lai piekÄ¼Å«tu tuvÄkajai nepieejamajai fokusa vietai pirms kursora. PiemÄram: diviem blakus esoÅ¡iem lÄ«nijas HR elementiem. AtkÄrtojiet taustiÅu kombinÄciju lai piekÄ¼Å«tu pie tÄlÄkÄm vietÄm."},{name:"PiekÄ¼Å«t nÄkoÅ¡Ä fokusa apgabala komandai",legend:"Nospiediet ${accessNextSpace} lai piekÄ¼Å«tu tuvÄkajai nepieejamajai fokusa vietai pÄc kursora. PiemÄram: diviem blakus esoÅ¡iem lÄ«nijas HR elementiem. AtkÄrtojiet taustiÅu kombinÄciju lai piekÄ¼Å«tu pie tÄlÄkÄm vietÄm."},
{name:"PieejamÄ«bas palÄ«dzÄ«ba",legend:"Nospiediet ${a11yHelp}"},{name:" Paste as plain text",legend:"Press ${pastetext}",legendEdge:"Press ${pastetext}, followed by ${paste}"}]}],tab:"Tab",pause:"Pause",capslock:"Caps Lock",escape:"Escape",pageUp:"Page Up",pageDown:"Page Down",leftArrow:"Left Arrow",upArrow:"Up Arrow",rightArrow:"Right Arrow",downArrow:"Down Arrow",insert:"Insert",leftWindowKey:"Left Windows key",rightWindowKey:"Right Windows key",selectKey:"Select key",numpad0:"Numpad 0",numpad1:"Numpad 1",
numpad2:"Numpad 2",numpad3:"Numpad 3",numpad4:"Numpad 4",numpad5:"Numpad 5",numpad6:"Numpad 6",numpad7:"Numpad 7",numpad8:"Numpad 8",numpad9:"Numpad 9",multiply:"Multiply",add:"Add",subtract:"Subtract",decimalPoint:"Decimal Point",divide:"Divide",f1:"F1",f2:"F2",f3:"F3",f4:"F4",f5:"F5",f6:"F6",f7:"F7",f8:"F8",f9:"F9",f10:"F10",f11:"F11",f12:"F12",numLock:"Num Lock",scrollLock:"Scroll Lock",semiColon:"Semicolon",equalSign:"Equal Sign",comma:"Comma",dash:"Dash",period:"Period",forwardSlash:"Forward Slash",
graveAccent:"Grave Accent",openBracket:"Open Bracket",backSlash:"Backslash",closeBracket:"Close Bracket",singleQuote:"Single Quote"});