ï»¿/*
 Copyright (c) 2003-2019, CKSource - Frederico Knabben. All rights reserved.
 For licensing, see LICENSE.md or https://ckeditor.com/legal/ckeditor-oss-license
*/
CKEDITOR.plugins.setLang("a11yhelp","mk",{title:"ÐÐ½ÑÑÑÑÐºÑÐ¸Ð¸ Ð·Ð° Ð¿ÑÐ¸ÑÑÐ°Ð¿Ð½Ð¾ÑÑ",contents:"Ð¡Ð¾Ð´ÑÐ¶Ð¸Ð½Ð° Ð½Ð° Ð´ÐµÐ»Ð¾Ñ Ð·Ð° Ð¿Ð¾Ð¼Ð¾Ñ. ÐÐ° Ð´Ð° Ð³Ð¾ Ð·Ð°ÑÐ²Ð¾ÑÐ¸ÑÐµ Ð¾Ð²Ð¾Ñ Ð´Ð¸ÑÐ°Ð»Ð¾Ð³ Ð¿ÑÐ¸ÑÐ¸ÑÐ½ÐµÑÐµ ESC.",legend:[{name:"ÐÐ¿ÑÑÐ¾",items:[{name:"ÐÐµÐ½Ð¸ Ð·Ð° ÑÑÐµÐ´ÑÐ²Ð°ÑÐ¾Ñ",legend:"Press ${toolbarFocus} to navigate to the toolbar. Move to the next and previous toolbar group with TAB and SHIFT+TAB. Move to the next and previous toolbar button with RIGHT ARROW or LEFT ARROW. Press SPACE or ENTER to activate the toolbar button."},{name:"ÐÐ¸ÑÐ°Ð»Ð¾Ñ Ð·Ð° ÐµÐ´Ð¸ÑÐ¾ÑÐ¾Ñ",
legend:"Inside a dialog, press TAB to navigate to the next dialog element, press SHIFT+TAB to move to the previous dialog element, press ENTER to submit the dialog, press ESC to cancel the dialog. When a dialog has multiple tabs, the tab list can be reached either with ALT+F10 or with TAB as part of the dialog tabbing order. With tab list focused, move to the next and previous tab with RIGHT and LEFT ARROW, respectively."},{name:"ÐÐ¾Ð½ÑÐµÐºÑÑ-Ð¼ÐµÐ½Ð¸ Ð½Ð° ÑÑÐµÐ´ÑÐ²Ð°ÑÐ¾Ñ",legend:"Press ${contextMenu} or APPLICATION KEY to open context-menu. Then move to next menu option with TAB or DOWN ARROW. Move to previous option with SHIFT+TAB or UP ARROW. Press SPACE or ENTER to select the menu option. Open sub-menu of current option with SPACE or ENTER or RIGHT ARROW. Go back to parent menu item with ESC or LEFT ARROW. Close context menu with ESC."},
{name:"Editor List Box",legend:"Inside a list-box, move to next list item with TAB OR DOWN ARROW. Move to previous list item with SHIFT+TAB or UP ARROW. Press SPACE or ENTER to select the list option. Press ESC to close the list-box."},{name:"Editor Element Path Bar",legend:"Press ${elementsPathFocus} to navigate to the elements path bar. Move to next element button with TAB or RIGHT ARROW. Move to previous button with SHIFT+TAB or LEFT ARROW. Press SPACE or ENTER to select the element in editor."}]},
{name:"ÐÐ°ÑÐµÐ´Ð±Ð¸",items:[{name:" Undo command",legend:"Press ${undo}"},{name:" Redo command",legend:"Press ${redo}"},{name:" Bold command",legend:"Press ${bold}"},{name:" Italic command",legend:"Press ${italic}"},{name:" Underline command",legend:"Press ${underline}"},{name:" Link command",legend:"Press ${link}"},{name:" Toolbar Collapse command",legend:"Press ${toolbarCollapse}"},{name:" Access previous focus space command",legend:"Press ${accessPreviousSpace} to access the closest unreachable focus space before the caret, for example: two adjacent HR elements. Repeat the key combination to reach distant focus spaces."},
{name:" Access next focus space command",legend:"Press ${accessNextSpace} to access the closest unreachable focus space after the caret, for example: two adjacent HR elements. Repeat the key combination to reach distant focus spaces."},{name:" Accessibility Help",legend:"Press ${a11yHelp}"},{name:" Paste as plain text",legend:"Press ${pastetext}",legendEdge:"Press ${pastetext}, followed by ${paste}"}]}],tab:"Tab",pause:"ÐÐ°ÑÐ·Ð°",capslock:"Caps Lock",escape:"Escape",pageUp:"Page Up",pageDown:"Page Up",
leftArrow:"Ð¡ÑÑÐµÐ»ÐºÐ° Ð»ÐµÐ²Ð¾",upArrow:"Ð¡ÑÑÐµÐ»ÐºÐ° Ð³Ð¾ÑÐµ",rightArrow:"Ð¡ÑÑÐµÐ»ÐºÐ° Ð´ÐµÑÐ½Ð¾",downArrow:"Ð¡ÑÑÐµÐ»ÐºÐ° Ð´Ð¾Ð»Ðµ",insert:"Insert",leftWindowKey:"ÐÐµÐ²Ð¾ Windows ÐºÐ¾Ð¿ÑÐµ",rightWindowKey:"ÐÐµÑÐ½Ð¾ Windows ÐºÐ¾Ð¿ÑÐµ",selectKey:"Select ÐºÐ¾Ð¿ÑÐµ",numpad0:"ÐÑÐ¼. ÑÐ°ÑÑ. 0",numpad1:"ÐÑÐ¼. ÑÐ°ÑÑ. 1",numpad2:"ÐÑÐ¼. ÑÐ°ÑÑ. 2",numpad3:"ÐÑÐ¼. ÑÐ°ÑÑ. 3",numpad4:"ÐÑÐ¼. ÑÐ°ÑÑ. 4",numpad5:"ÐÑÐ¼. ÑÐ°ÑÑ. 5",numpad6:"ÐÑÐ¼. ÑÐ°ÑÑ. 6",numpad7:"ÐÑÐ¼. ÑÐ°ÑÑ. 7",numpad8:"ÐÑÐ¼. ÑÐ°ÑÑ. 8",numpad9:"ÐÑÐ¼. ÑÐ°ÑÑ. 9",multiply:"Multiply",add:"Add",subtract:"Subtract",decimalPoint:"Decimal Point",
divide:"Divide",f1:"F1",f2:"F2",f3:"F3",f4:"F4",f5:"F5",f6:"F6",f7:"F7",f8:"F8",f9:"F9",f10:"F10",f11:"F11",f12:"F12",numLock:"Num Lock",scrollLock:"Scroll Lock",semiColon:"Semicolon",equalSign:"Equal Sign",comma:"Comma",dash:"Dash",period:"Period",forwardSlash:"Forward Slash",graveAccent:"Grave Accent",openBracket:"Open Bracket",backSlash:"Backslash",closeBracket:"Close Bracket",singleQuote:"Single Quote"});