ï»¿/*
 Copyright (c) 2003-2019, CKSource - Frederico Knabben. All rights reserved.
 For licensing, see LICENSE.md or https://ckeditor.com/legal/ckeditor-oss-license
*/
CKEDITOR.plugins.setLang("a11yhelp","nb",{title:"Instruksjoner for tilgjengelighet",contents:"Innhold for hjelp. Trykk ESC for Ã¥ lukke denne dialogen.",legend:[{name:"Generelt",items:[{name:"VerktÃ¸ylinje for editor",legend:"Trykk ${toolbarFocus} for Ã¥ navigere til verktÃ¸ylinjen. Flytt til neste og forrige verktÃ¸ylinjegruppe med TAB og SHIFT+TAB. Flytt til neste og forrige verktÃ¸ylinjeknapp med HÃYRE PILTAST og VENSTRE PILTAST. Trykk MELLOMROM eller ENTER for Ã¥ aktivere verktÃ¸ylinjeknappen."},{name:"Dialog for editor",
legend:"Mens du er i en dialog, trykk TAB for Ã¥ navigere til neste dialogelement, trykk SHIFT+TAB for Ã¥ flytte til forrige dialogelement, trykk ENTER for Ã¥ akseptere dialogen, trykk ESC for Ã¥ avbryte dialogen. NÃ¥r en dialog har flere faner, kan fanelisten nÃ¥s med enten ALT+F10 eller med TAB. NÃ¥r fanelisten er fokusert, gÃ¥r man til neste og forrige fane med henholdsvis HÃYRE og VENSTRE PILTAST."},{name:"Kontekstmeny for editor",legend:"Trykk ${contextMenu} eller MENYKNAPP for Ã¥ Ã¥pne kontekstmeny. GÃ¥ til neste alternativ i menyen med TAB eller PILTAST NED. GÃ¥ til forrige alternativ med SHIFT+TAB eller PILTAST OPP. Trykk MELLOMROM eller ENTER for Ã¥ velge menyalternativet. Ãpne undermenyen pÃ¥ valgt alternativ med MELLOMROM eller ENTER eller HÃYRE PILTAST. GÃ¥ tilbake til overordnet menyelement med ESC eller VENSTRE PILTAST. Lukk kontekstmenyen med ESC."},
{name:"Listeboks for editor",legend:"I en listeboks, gÃ¥ til neste alternativ i listen med TAB eller PILTAST NED. GÃ¥ til forrige alternativ i listen med SHIFT+TAB eller PILTAST OPP. Trykk MELLOMROM eller ENTER for Ã¥ velge alternativet i listen. Trykk ESC for Ã¥ lukke listeboksen."},{name:"VerktÃ¸ylinje for elementsti",legend:"Trykk ${elementsPathFocus} for Ã¥ navigere til verktÃ¸ylinjen som viser elementsti. GÃ¥ til neste elementknapp med TAB eller HÃYRE PILTAST. GÃ¥ til forrige elementknapp med SHIFT+TAB eller VENSTRE PILTAST. Trykk MELLOMROM eller ENTER for Ã¥ velge elementet i editoren."}]},
{name:"Hurtigtaster",items:[{name:"Angre",legend:"Trykk ${undo}"},{name:"GjÃ¸r om",legend:"Trykk ${redo}"},{name:"Fet tekst",legend:"Trykk ${bold}"},{name:"Kursiv tekst",legend:"Trykk ${italic}"},{name:"Understreking",legend:"Trykk ${underline}"},{name:"Lenke",legend:"Trykk ${link}"},{name:"Skjul verktÃ¸ylinje",legend:"Trykk ${toolbarCollapse}"},{name:"GÃ¥ til forrige fokusomrÃ¥de",legend:"Trykk ${accessPreviousSpace} for Ã¥ komme til nÃ¦rmeste fokusomrÃ¥de fÃ¸r skrivemarkÃ¸ren som ikke kan nÃ¥s pÃ¥ vanlig mÃ¥te, for eksempel to tilstÃ¸tende HR-elementer. Gjenta tastekombinasjonen for Ã¥ komme til fokusomrÃ¥der lenger unna i dokumentet."},
{name:"GÃ¥ til neste fokusomrÃ¥de",legend:"Trykk ${accessNextSpace} for Ã¥ komme til nÃ¦rmeste fokusomrÃ¥de etter skrivemarkÃ¸ren som ikke kan nÃ¥s pÃ¥ vanlig mÃ¥te, for eksempel to tilstÃ¸tende HR-elementer. Gjenta tastekombinasjonen for Ã¥ komme til fokusomrÃ¥der lenger unna i dokumentet."},{name:"Hjelp for tilgjengelighet",legend:"Trykk ${a11yHelp}"},{name:"Lim inn som ren tekst",legend:"Trykk ${pastetext}",legendEdge:"Trykk ${pastetext}, etterfulgt av ${past}"}]}],tab:"Tabulator",pause:"Pause",capslock:"Caps Lock",
escape:"Escape",pageUp:"Page Up",pageDown:"Page Down",leftArrow:"Venstre piltast",upArrow:"Opp-piltast",rightArrow:"HÃ¸yre piltast",downArrow:"Ned-piltast",insert:"Insert",leftWindowKey:"Venstre Windows-tast",rightWindowKey:"HÃ¸yre Windows-tast",selectKey:"Velg nÃ¸kkel",numpad0:"Numerisk tastatur 0",numpad1:"Numerisk tastatur 1",numpad2:"Numerisk tastatur 2",numpad3:"Numerisk tastatur 3",numpad4:"Numerisk tastatur 4",numpad5:"Numerisk tastatur 5",numpad6:"Numerisk tastatur 6",numpad7:"Numerisk tastatur 7",
numpad8:"Numerisk tastatur 8",numpad9:"Numerisk tastatur 9",multiply:"Multipliser",add:"Legg til",subtract:"Trekk fra",decimalPoint:"Desimaltegn",divide:"Divider",f1:"F1",f2:"F2",f3:"F3",f4:"F4",f5:"F5",f6:"F6",f7:"F7",f8:"F8",f9:"F9",f10:"F10",f11:"F11",f12:"F12",numLock:"Num Lock",scrollLock:"Scroll Lock",semiColon:"Semikolon",equalSign:"Likhetstegn",comma:"Komma",dash:"Bindestrek",period:"Punktum",forwardSlash:"Forover skrÃ¥strek",graveAccent:"Grav aksent",openBracket:"Ãpne parentes",backSlash:"Bakover skrÃ¥strek",
closeBracket:"Lukk parentes",singleQuote:"Enkelt sitattegn"});