ï»¿/*
 Copyright (c) 2003-2019, CKSource - Frederico Knabben. All rights reserved.
 For licensing, see LICENSE.md or https://ckeditor.com/legal/ckeditor-oss-license
*/
CKEDITOR.plugins.setLang("a11yhelp","pl",{title:"Instrukcje dotyczÄce dostÄpnoÅci",contents:"ZawartoÅÄ pomocy. WciÅnij ESC, aby zamknÄÄ to okno.",legend:[{name:"Informacje ogÃ³lne",items:[{name:"Pasek narzÄdzi edytora",legend:"NaciÅnij ${toolbarFocus}, by przejÅÄ do paska narzÄdzi. PrzejdÅº do nastÄpnej i poprzedniej grupy narzÄdzi uÅ¼ywajÄc TAB oraz SHIFT+TAB. PrzejdÅº do nastÄpnego i poprzedniego przycisku paska narzÄdzi za pomocÄ STRZAÅKI W PRAWO lub STRZAÅKI W LEWO. NaciÅnij SPACJÄ lub ENTER by aktywowaÄ przycisk paska narzÄdzi."},
{name:"Okno dialogowe edytora",legend:"WewnÄtrz okna dialogowego naciÅnij TAB, by przejÅÄ do kolejnego elementu tego okna lub SHIFT+TAB, by przejÅÄ do poprzedniego elementu okna. NaciÅnij ENTER w celu zatwierdzenia opcji okna dialogowego lub ESC w celu anulowania zmian. JeÅli okno dialogowe ma kilka zakÅadek, do listy zakÅadek moÅ¼na przejÅÄ za pomocÄ ALT+F10 lub TAB. Gdy lista zakÅadek jest aktywna, moÅ¼esz przejÅÄ do kolejnej i poprzedniej zakÅadki za pomocÄ STRZAÅKI W PRAWO i STRZAÅKI W LEWO."},
{name:"Menu kontekstowe edytora",legend:"WciÅnij ${contextMenu} lub PRZYCISK APLIKACJI aby otworzyÄ menu kontekstowe. PrzejdÅº do nastÄpnej pozycji menu wciskajÄc TAB lub STRZAÅKÄ W DÃÅ. PrzejdÅº do poprzedniej pozycji menu wciskajÄc SHIFT + TAB lub STRZAÅKÄ W GÃRÄ. WciÅnij SPACJÄ lub ENTER aby wygraÄ pozycjÄ menu. OtwÃ³rz pod-menu obecnej pozycji wciskajÄc SPACJÄ lub ENTER lub STRZAÅKÄ W PRAWO. WrÃ³Ä do pozycji nadrzÄdnego menu wciskajÄc ESC lub STRZAÅKÄ W LEWO. Zamknij menu wciskajÄc ESC."},{name:"Lista w edytorze",
legend:"WewnÄtrz listy przejdÅº do kolejnego elementu listy za pomocÄ przycisku TAB lub STRZAÅKI W DÃÅ. PrzejdÅº do poprzedniego elementu listy za pomocÄ SHIFT+TAB lub STRZAÅKI W GÃRÄ. NaciÅnij SPACJÄ lub ENTER w celu wybrania opcji z listy. NaciÅnij ESC, by zamknÄÄ listÄ."},{name:"Pasek ÅcieÅ¼ki elementÃ³w edytora",legend:"NaciÅnij ${elementsPathFocus} w celu przejÅcia do paska ÅcieÅ¼ki elementÃ³w edytora. W celu przejÅcia do kolejnego elementu naciÅnij klawisz TAB lub STRZAÅKI W PRAWO. W celu przejÅcia do poprzedniego elementu naciÅnij klawisze SHIFT+TAB lub STRZAÅKI W LEWO. By wybraÄ element w edytorze, uÅ¼yj klawisza SPACJI lub ENTER."}]},
{name:"Polecenia",items:[{name:"Polecenie Cofnij",legend:"NaciÅnij ${undo}"},{name:"Polecenie PonÃ³w",legend:"NaciÅnij ${redo}"},{name:"Polecenie Pogrubienie",legend:"NaciÅnij ${bold}"},{name:"Polecenie Kursywa",legend:"NaciÅnij ${italic}"},{name:"Polecenie PodkreÅlenie",legend:"NaciÅnij ${underline}"},{name:"Polecenie Wstaw/ edytuj odnoÅnik",legend:"NaciÅnij ${link}"},{name:"Polecenie schowaj pasek narzÄdzi",legend:"NaciÅnij ${toolbarCollapse}"},{name:"PrzejdÅº do poprzedniego miejsca, w ktÃ³rym moÅ¼na ustawiÄ focus",
legend:"NaciÅnij ${accessPreviousSpace}, aby przejÅÄ do najbliÅ¼szego niedostÄpnego miejsca przed kursorem, w ktÃ³rym moÅ¼na ustawiÄ focus. PrzykÅad: dwa przylegajÄce elementy HR. PowtÃ³rz ten skrÃ³t klawiaturowy, by dotrzeÄ do kolejnych takich miejsc."},{name:"PrzejdÅº do nastÄpnego miejsca, w ktÃ³rym moÅ¼na ustawiÄ focus",legend:"NaciÅnij ${accessNextSpace}, aby przejÅÄ do najbliÅ¼szego niedostÄpnego miejsca po kursorze, w ktÃ³rym moÅ¼na ustawiÄ focus. PrzykÅad: dwa przylegajÄce elementy HR. PowtÃ³rz ten skrÃ³t klawiaturowy, by dotrzeÄ do kolejnych takich miejsc."},
{name:"Pomoc dotyczÄca dostÄpnoÅci",legend:"NaciÅnij ${a11yHelp}"},{name:"Wklej jako tekst",legend:"NaciÅnij ${pastetext}",legendEdge:"NaciÅnij ${pastetext}, a nastÄpnie ${paste}"}]}],tab:"Tab",pause:"Pause",capslock:"Caps Lock",escape:"Escape",pageUp:"Page Up",pageDown:"Page Down",leftArrow:"StrzaÅka w lewo",upArrow:"StrzaÅka w gÃ³rÄ",rightArrow:"StrzaÅka w prawo",downArrow:"StrzaÅka w dÃ³Å",insert:"Insert",leftWindowKey:"Lewy klawisz Windows",rightWindowKey:"Prawy klawisz Windows",selectKey:"Klawisz wyboru",
numpad0:"Klawisz 0 na klawiaturze numerycznej",numpad1:"Klawisz 1 na klawiaturze numerycznej",numpad2:"Klawisz 2 na klawiaturze numerycznej",numpad3:"Klawisz 3 na klawiaturze numerycznej",numpad4:"Klawisz 4 na klawiaturze numerycznej",numpad5:"Klawisz 5 na klawiaturze numerycznej",numpad6:"Klawisz 6 na klawiaturze numerycznej",numpad7:"Klawisz 7 na klawiaturze numerycznej",numpad8:"Klawisz 8 na klawiaturze numerycznej",numpad9:"Klawisz 9 na klawiaturze numerycznej",multiply:"PrzemnÃ³Å¼",add:"Plus",
subtract:"Minus",decimalPoint:"Separator dziesiÄtny",divide:"Podziel",f1:"F1",f2:"F2",f3:"F3",f4:"F4",f5:"F5",f6:"F6",f7:"F7",f8:"F8",f9:"F9",f10:"F10",f11:"F11",f12:"F12",numLock:"Num Lock",scrollLock:"Scroll Lock",semiColon:"Årednik",equalSign:"Znak rÃ³wnoÅci",comma:"Przecinek",dash:"Pauza",period:"Kropka",forwardSlash:"UkoÅnik prawy",graveAccent:"Akcent sÅaby",openBracket:"Nawias kwadratowy otwierajÄcy",backSlash:"UkoÅnik lewy",closeBracket:"Nawias kwadratowy zamykajÄcy",singleQuote:"Apostrof"});