ï»¿/*
 Copyright (c) 2003-2019, CKSource - Frederico Knabben. All rights reserved.
 For licensing, see LICENSE.md or https://ckeditor.com/legal/ckeditor-oss-license
*/
CKEDITOR.plugins.setLang("a11yhelp","pt-br",{title:"InstruÃ§Ãµes de Acessibilidade",contents:"ConteÃºdo da Ajuda. Para fechar este diÃ¡logo pressione ESC.",legend:[{name:"Geral",items:[{name:"Barra de Ferramentas do Editor",legend:"Pressione ${toolbarFocus} para navegar para a barra de ferramentas. Mova para o anterior ou prÃ³ximo grupo de ferramentas com TAB e SHIFT+TAB. Mova para o anterior ou prÃ³ximo botÃ£o com SETA PARA DIREITA or SETA PARA ESQUERDA. Pressione ESPAÃO ou ENTER para ativar o botÃ£o da barra de ferramentas."},
{name:"DiÃ¡logo do Editor",legend:"Dentro de um diÃ¡logo, pressione TAB para navegar para o prÃ³ximo elemento. Pressione SHIFT+TAB para mover para o elemento anterior. Pressione ENTER ara enviar o diÃ¡logo. pressione ESC para cancelar o diÃ¡logo. Quando um diÃ¡logo tem mÃºltiplas abas, a lista de abas pode ser acessada com ALT+F10 ou TAB, como parte da ordem de tabulaÃ§Ã£o do diÃ¡logo. Com a lista de abas em foco, mova para a prÃ³xima aba e para a aba anterior com a SETA DIREITA ou SETA ESQUERDA, respectivamente."},
{name:"Menu de Contexto do Editor",legend:"Pressione ${contextMenu} ou TECLA DE MENU para abrir o menu de contexto, entÃ£o mova para a prÃ³xima opÃ§Ã£o com TAB ou SETA PARA BAIXO. Mova para a anterior com SHIFT+TAB ou SETA PARA CIMA. Pressione ESPAÃO ou ENTER para selecionar a opÃ§Ã£o do menu. Abra o submenu da opÃ§Ã£o atual com ESPAÃO ou ENTER ou SETA PARA DIREITA. Volte para o menu pai com ESC ou SETA PARA ESQUERDA. Feche o menu de contexto com ESC."},{name:"Caixa de Lista do Editor",legend:"Dentro de uma caixa de lista, mova para o prÃ³ximo item com TAB ou SETA PARA BAIXO. Mova para o item anterior com SHIFT+TAB ou SETA PARA CIMA. Pressione ESPAÃO ou ENTER para selecionar uma opÃ§Ã£o na lista. Pressione ESC para fechar a caixa de lista."},
{name:"Barra de Caminho do Elementos do Editor",legend:"Pressione ${elementsPathFocus} para a barra de caminho dos elementos. Mova para o prÃ³ximo botÃ£o de elemento com TAB ou SETA PARA DIREITA. Mova para o botÃ£o anterior com SHIFT+TAB ou SETA PARA ESQUERDA. Pressione ESPAÃO ou ENTER para selecionar o elemento no editor."}]},{name:"Comandos",items:[{name:" Comando Desfazer",legend:"Pressione ${undo}"},{name:" Comando Refazer",legend:"Pressione ${redo}"},{name:" Comando Negrito",legend:"Pressione ${bold}"},
{name:" Comando ItÃ¡lico",legend:"Pressione ${italic}"},{name:" Comando Sublinhado",legend:"Pressione ${underline}"},{name:" Comando Link",legend:"Pressione ${link}"},{name:" Comando Fechar Barra de Ferramentas",legend:"Pressione ${toolbarCollapse}"},{name:"Acessar o comando anterior de spaÃ§o de foco",legend:"Pressione ${accessNextSpace} para acessar o espaÃ§o de foco nÃ£o alcanÃ§Ã¡vel mais prÃ³ximo antes do cursor, por exemplo: dois elementos HR adjacentes. Repita a combinaÃ§Ã£o de teclas para alcanÃ§ar espaÃ§os de foco distantes."},
{name:"Acessar prÃ³ximo fomando de spaÃ§o de foco",legend:"Pressione ${accessNextSpace} para acessar o espaÃ§o de foco nÃ£o alcanÃ§Ã¡vel mais prÃ³ximo apÃ³s o cursor, por exemplo: dois elementos HR adjacentes. Repita a combinaÃ§Ã£o de teclas para alcanÃ§ar espaÃ§os de foco distantes."},{name:" Ajuda de Acessibilidade",legend:"Pressione ${a11yHelp}"},{name:"Colar como texto sem formataÃ§Ã£o",legend:"Pressione ${pastetext}",legendEdge:"Pressione ${pastetext}, seguido de ${paste}"}]}],tab:"Tecla Tab",pause:"Pause",
capslock:"Caps Lock",escape:"Escape",pageUp:"Page Up",pageDown:"Page Down",leftArrow:"Seta Ã  Esquerda",upArrow:"Seta Ã  Cima",rightArrow:"Seta Ã  Direita",downArrow:"Seta Ã  Baixo",insert:"Insert",leftWindowKey:"Tecla do Windows Esquerda",rightWindowKey:"Tecla do Windows Direita",selectKey:"Tecla Selecionar",numpad0:"0 do Teclado NumÃ©rico",numpad1:"1 do Teclado NumÃ©rico",numpad2:"2 do Teclado NumÃ©rico",numpad3:"3 do Teclado NumÃ©rico",numpad4:"4 do Teclado NumÃ©rico",numpad5:"5 do Teclado NumÃ©rico",numpad6:"6 do Teclado NumÃ©rico",
numpad7:"7 do Teclado NumÃ©rico",numpad8:"8 do Teclado NumÃ©rico",numpad9:"9 do Teclado NumÃ©rico",multiply:"Multiplicar",add:"Mais",subtract:"Subtrair",decimalPoint:"Ponto",divide:"Dividir",f1:"F1",f2:"F2",f3:"F3",f4:"F4",f5:"F5",f6:"F6",f7:"F7",f8:"F8",f9:"F9",f10:"F10",f11:"F11",f12:"F12",numLock:"Num Lock",scrollLock:"Scroll Lock",semiColon:"Ponto-e-vÃ­rgula",equalSign:"Igual",comma:"VÃ­rgula",dash:"HÃ­fen",period:"Ponto",forwardSlash:"Barra",graveAccent:"Acento Grave",openBracket:"Abrir Conchetes",
backSlash:"Contra-barra",closeBracket:"Fechar Colchetes",singleQuote:"Aspas Simples"});