ï»¿/*
 Copyright (c) 2003-2019, CKSource - Frederico Knabben. All rights reserved.
 For licensing, see LICENSE.md or https://ckeditor.com/legal/ckeditor-oss-license
*/
CKEDITOR.plugins.setLang("a11yhelp","ro",{title:"InstrucÈiuni Accesibilitate",contents:"Cuprins. Pentru a Ã®nchide acest dialog, apÄsaÈi tasta ESC.",legend:[{name:"General",items:[{name:"Editor barÄ de instrumente.",legend:"ApasÄ ${toolbarFocus} pentru a naviga pe de instrumente. Pentru deplasarea la urmÄtorul sau anteriorul grup de instrumente se folosesc tastele TAB Èi SHIFT+TAB. Pentru deplasare pe urmatorul sau anteriorul instrument se folosesc tastele SÄGEATÄ DREAPTA sau SÄGEATÄ STÃNGA. Tasta SPAÈIU sau ENTER activeazÄ instrumentul."},
{name:"Dialog editor",legend:"Ãn interiorul unui dialog, se apasÄ TAB pentru navigarea la urmÄtorul element de dialog, SHIFT+TAB pentru deplasarea la anteriorul element de dialog, ENTER pentru validare dialog, ESC pentru anulare dialog. CÃ¢nd un dialog are secÈiuni multiple, lista secÈiunilor este accesibilÄ cu ALT+F10 sau cu TAB ca parte a ordonÄrii secÈionÄrii dialogului. Cu lista secÈiunii activatÄ, deplasarea Ã®nainte Ã®napoi se face cu tastele SÄGEATÄ DREAPTA Èi respectiv STÃNGA."},{name:"Editor meniu contextual",
legend:"ApasÄ ${contextMenu} sau TASTA MENIU pentru a deschide meniul contextual. Se trece la urmÄtoarea opÈiune din meniu cu TAB sau SÄGEATÄ JOS. La opÈiunea anterioarÄ cu SHIFT+TAB sau SÄGEATÄ SUS. Se apasÄ SPAÈIU sau ENTER pentru a selecta opÈiunea. Deschide sub-meniul opÈiunii curente cu SPAÈIU sau ENTER sau SÄGEATÄ DREAPTA. Se revine la elementul din meniul pÄrinte cu ESC sau SÄGEATÄ STÃNGA. Ãnchide meniul de context cu ESC."},{name:"Caseta listÄ a editorului",legend:"Ãn interiorul unei liste, treci la urmÄtorull element cu TAB sau SÄGEATÄ JOS. Treci la elementul anterior din listÄ cu SHIFT+TAB sau SÄGEATÄ SUS. ApasÄ SPAÈIU sau ENTER pentru a selecta opÈiunea din listÄ. ApasÄ ESC pentru a Ã®nchide lista."},
{name:"Bara cÄii editorului de elemente",legend:"ApasÄ ${elementsPathFocus} pentru navigare pe elementele barei. Mergi la urmÄtorul buton cu TAB sau SÄGEATÄ JOS. Treci la butonul anterior din listÄ cu SHIFT+TAB sau SÄGEATÄ SUS. ApasÄ SPAÈIU sau ENTER pentru a selecta butonul Ã®n editor."}]},{name:"Comenzi",items:[{name:"Revino anterior (Undo)",legend:"ApasÄ ${undo}"},{name:"Comanda precedentÄ",legend:"ApasÄ ${redo}"},{name:"ÃngroÈat (Bold)",legend:"ApasÄ ${bold}"},{name:"Ãnclinat (Italic)",legend:"ApasÄ ${italic}"},
{name:"Subliniere (Underline)",legend:"ApasÄ ${underline}"},{name:"LegaturÄ (Link)",legend:"ApasÄ ${link}"},{name:"DesfÄÈurare BarÄ instrumente",legend:"ApasÄ ${toolbarCollapse}"},{name:"Accesare spaÈiu focus anterior",legend:"ApasÄ ${accessPreviousSpace} pentru a accesa cel mai apropiat spaÈiu focus indisponibil Ã®naintea cursorului, de exemplu: 2 elemente adiacente HR. RepetÄ combinaÈia de taste pentru a accesa spaÈiile Ã®ndepÄrtate de focus."},{name:"Accesare spaÈiu focus urmÄtor",legend:"ApasÄ ${accessNextSpace} pentru a accesa cel mai apropiat spaÈiu focus indisponibil dupÄ cursor, de exemplu: 2 elemente adiacente HR. RepetÄ combinaÈia de taste pentru a accesa spaÈiile Ã®ndepÄrtate de focus."},
{name:"Ajutor Accesibilitate",legend:"ApasÄ ${a11yHelp}"},{name:"AdaugÄ ca Text simplu (Plain Text)",legend:"ApasÄ ${pastetext}",legendEdge:"ApasÄ ${pastetext}, urmat de ${paste}"}]}],tab:"TAB",pause:"PauzÄ",capslock:"Majuscule",escape:"Esc - renunÈÄ",pageUp:"PaginÄ sus",pageDown:"SÄgeatÄ jos",leftArrow:"SÄgeatÄ stÃ¢nga",upArrow:"SÄgeatÄ sus",rightArrow:"SÄgeatÄ dreapta",downArrow:"SÄgeatÄ jos",insert:"InsereazÄ",leftWindowKey:"Windows stÃ¢nga",rightWindowKey:"Windows dreapta",selectKey:"Tasta SelecÈie",
numpad0:"0 Numeric",numpad1:"1 Numeric",numpad2:"2 Numeric",numpad3:"3 Numeric",numpad4:"4 Numeric",numpad5:"5 Numeric",numpad6:"6 Numeric",numpad7:"7 Numeric",numpad8:"8 Numeric",numpad9:"9 Numeric",multiply:"ÃnmulÈire",add:"Adunare",subtract:"ScÄdere",decimalPoint:"Punct zecimal",divide:"ÃmpÄrÈire",f1:"F1",f2:"F2",f3:"F3",f4:"F4",f5:"F5",f6:"F6",f7:"F7",f8:"F8",f9:"F9",f10:"F10",f11:"F11",f12:"F12",numLock:"NumLock",scrollLock:"Scroll Lock",semiColon:"Punct Èi virgulÄ",equalSign:"Egal",comma:"VirgulÄ",
dash:"Linie",period:"Punct",forwardSlash:"Slash",graveAccent:"Accent grav",openBracket:"ParantezÄ dreaptÄ stÃ¢nga",backSlash:"Backslash",closeBracket:"ParantezÄ dreaptÄ dreapta",singleQuote:"Ghilimea simplÄ"});