ï»¿/*
 Copyright (c) 2003-2019, CKSource - Frederico Knabben. All rights reserved.
 For licensing, see LICENSE.md or https://ckeditor.com/legal/ckeditor-oss-license
*/
CKEDITOR.plugins.setLang("a11yhelp","sl",{title:"Navodila za dostopnost",contents:"Vsebina pomoÄi. Äe Å¾elite zapreti pogovorno okno, pritisnite ESC.",legend:[{name:"SploÅ¡no",items:[{name:"Orodna vrstica urejevalnika",legend:"Pritisnite ${toolbarFocus} za pomik v orodno vrstico. Z TAB in SHIFT+TAB se pomikate na naslednjo in prejÅ¡njo skupino orodne vrstice. Z DESNO PUÅ ÄICO ali LEVO PUÅ ÄICO se pomikate na naslednji in prejÅ¡nji gumb orodne vrstice. Pritisnite SPACE ali ENTER, da aktivirate gumb orodne vrstice."},
{name:"Urejevalno Pogovorno Okno",legend:"Inside a dialog, press TAB to navigate to the next dialog element, press SHIFT+TAB to move to the previous dialog element, press ENTER to submit the dialog, press ESC to cancel the dialog. When a dialog has multiple tabs, the tab list can be reached either with ALT+F10 or with TAB as part of the dialog tabbing order. With tab list focused, move to the next and previous tab with RIGHT and LEFT ARROW, respectively."},{name:"Kontekstni meni urejevalnika",legend:"Pritisnite ${contextMenu} ali APPLICATION KEY, da odprete kontekstni meni. Nato se premaknite na naslednjo moÅ¾nost menija s tipko TAB ali PUÅ ÄICA DOL. Premakniti se na prejÅ¡njo moÅ¾nost z SHIFT + TAB ali PUÅ ÄICA GOR. Pritisnite SPACE ali ENTER za izbiro moÅ¾nosti menija. Odprite podmeni trenutne moÅ¾nosti menija s tipko SPACE ali ENTER ali DESNA PUÅ ÄICA. Vrnite se na matiÄni element menija s tipko ESC ali LEVA PUÅ ÄICA. Zaprite kontekstni meni z ESC."},
{name:"Urejevalno Seznamsko Polje",legend:"Znotraj seznama, se premaknete na naslednji element seznama s tipko TAB ali PUÅ ÄICO DOL. Z SHIFT+TAB ali PUÅ ÄICO GOR se premaknete na prejÅ¡nji element seznama. Pritisnite tipko SPACE ali ENTER za izbiro elementa. Pritisnite tipko ESC, da zaprete seznam."},{name:"Urejevalna vrstica poti elementa",legend:"Pritisnite ${elementsPathFocus} za pomikanje po vrstici elementnih poti. S TAB ali DESNA PUÅ ÄICA se premaknete na naslednji gumb elementa. Z SHIFT+TAB ali LEVO PUÅ ÄICO se premaknete na prejÅ¡nji gumb elementa. Pritisnite SPACE ali ENTER za izbiro elementa v urejevalniku."}]},
{name:"Ukazi",items:[{name:"Razveljavi ukaz",legend:"Pritisnite ${undo}"},{name:"Ponovi ukaz",legend:"Pritisnite ${redo}"},{name:"Krepki ukaz",legend:"Pritisnite ${bold}"},{name:"LeÅ¾eÄi ukaz",legend:"Pritisnite ${italic}"},{name:"Poudarni ukaz",legend:"Pritisnite ${underline}"},{name:"Ukaz povezave",legend:"Pritisnite ${link}"},{name:"SkrÄi Orodno Vrstico Ukaz",legend:"Pritisnite ${toolbarCollapse}"},{name:"Dostop do prejÅ¡njega ukaza ostrenja",legend:"Pritisnite ${accessPreviousSpace} za dostop do najbliÅ¾jega nedosegljivega osredotoÄenega prostora pred streÅ¡ico, npr.: dva sosednja HR elementa. Ponovite kombinacijo tipk, da doseÅ¾ete oddaljene osredotoÄene prostore."},
{name:"Dostop do naslednjega ukaza ostrenja",legend:"Pritisnite ${accessNextSpace} za dostop do najbliÅ¾jega nedosegljivega osredotoÄenega prostora po streÅ¡ici, npr.: dva sosednja HR elementa. Ponovite kombinacijo tipk, da doseÅ¾ete oddaljene osredotoÄene prostore."},{name:"PomoÄ dostopnosti",legend:"Pritisnite ${a11yHelp}"},{name:" Paste as plain text",legend:"Press ${pastetext}",legendEdge:"Press ${pastetext}, followed by ${paste}"}]}],tab:"Tab",pause:"Pause",capslock:"Caps Lock",escape:"Escape",
pageUp:"Page Up",pageDown:"Page Down",leftArrow:"PuÅ¡Äica levo",upArrow:"PuÅ¡Äica gor",rightArrow:"PuÅ¡Äica desno",downArrow:"PuÅ¡Äica dol",insert:"Insert",leftWindowKey:"Leva tipka Windows",rightWindowKey:"Desna tipka Windows",selectKey:"Select tipka",numpad0:"Numpad 0",numpad1:"Numpad 1",numpad2:"Numpad 2",numpad3:"Numpad 3",numpad4:"Numpad 4",numpad5:"Numpad 5",numpad6:"Numpad 6",numpad7:"Numpad 7",numpad8:"Numpad 8",numpad9:"Numpad 9",multiply:"ZmnoÅ¾i",add:"Dodaj",subtract:"OdÅ¡tej",decimalPoint:"Decimalna vejica",
divide:"Deli",f1:"F1",f2:"F2",f3:"F3",f4:"F4",f5:"F5",f6:"F6",f7:"F7",f8:"F8",f9:"F9",f10:"F10",f11:"F11",f12:"F12",numLock:"Num Lock",scrollLock:"Scroll Lock",semiColon:"PodpiÄje",equalSign:"EnaÄaj",comma:"Vejica",dash:"Vezaj",period:"Pika",forwardSlash:"Desna poÅ¡evnica",graveAccent:"Krativec",openBracket:"Oklepaj",backSlash:"Leva poÅ¡evnica",closeBracket:"Zaklepaj",singleQuote:"OpuÅ¡Äaj"});