ï»¿/*
 Copyright (c) 2003-2019, CKSource - Frederico Knabben. All rights reserved.
 For licensing, see LICENSE.md or https://ckeditor.com/legal/ckeditor-oss-license
*/
CKEDITOR.plugins.setLang("a11yhelp","sq",{title:"UdhÃ«zimet e Qasjes",contents:"PÃ«rmbajtja ndihmÃ«se. PÃ«r ta mbyllur dialogun shtyp ESC.",legend:[{name:"TÃ« pÃ«rgjithshme",items:[{name:"Shiriti i Redaktuesit",legend:"Shtyp ${toolbarFocus} pÃ«r tÃ« shfletuar kokÃ«shtrirjen. Kalo tek grupi paraprak ose pasues i shiritit pÃ«rmes kombinacionit TAB dhe SHIFT+TAB, nÃ« tastierÃ«. Kalo tek pulla paraprake ose pasuese e kokÃ«shtrirjes pÃ«rmes SHIGJETÃ DJATHTAS ose SHIGJETÃS MAJTAS, nÃ« tastierÃ«. Shtyp HAPÃSIRÃ ose ENTER Move to the next and previous toolbar button with RIGHT ARROW pÃ«r tÃ« aktivizuar pullÃ«n e kokÃ«shtrirjes."},
{name:"Dialogu i Redaktuesit",legend:"NÃ« brendi tÃ« dialogut, shtyp TAB pÃ«r tÃ« kaluar tek elementi tjetÃ«r i dialogut, shtyp SHIFT+TAB pÃ«r tÃ« kaluar tek elementi paraprak i dialogut, shtyp ENTER pÃ«r tÃ« shtuar dialogun, shtyp ESC pÃ«r tÃ« anuluar dialogun.  Kur njÃ« dialog ka mÃ« shumÃ« fletÃ«, lista e fletÃ«ve mund tÃ« hapet pÃ«rmes ALT+F10 ose pÃ«rmes TAB si pjesÃ« e radhitjes sÃ« fletÃ«ve tÃ« dialogut. Me listÃ«n e fokusuar tÃ« fletÃ«ve,kalo tek fleta paraprake dhe pasuese pÃ«rmes SHIGJETÃS MAJSA ose DJATHTAS."},{name:"Menyja Kontestuese e Redaktorit",
legend:"Shtyp ${contextMenu} ose APPLICATION KEY pÃ«r tÃ« hapur menynÃ« kontekstuale. Pastaj kalo tek mundÃ«sia tjetÃ«r e menysÃ« pÃ«rmes TAB ose SHIGJETÃS POSHTÃ. Kalo tek mundÃ«sia paraprake pÃ«rmes SHIFT+TAB ose SHIGJETA SIPÃR. Shtyp SPACE ose ENTER pÃ«r tÃ« pÃ«rzgjedhur mundÃ«sinÃ« e menysÃ«. Hape nÃ«nmenynÃ« e mundÃ«sisÃ« aktuale pÃ«rmes tastÃ«s HAPÃSIRÃ ose ENTER ose SHIGJETÃS DJATHTAS. Kalo prapa tek artikulli i menysÃ« prind pÃ«rmes ESC ose SHIGJETÃS MAJTAS. Mbylle menynÃ« kontekstuale pÃ«rmes ESC."},{name:"Kutiza e ListÃ«s sÃ« Redaktuesit",
legend:"Brenda kutisÃ« sÃ« listÃ«s, kalo tek artikulli pasues i listÃ«s pÃ«rmes TAB ose SHIGJETÃS POSHTÃ. Kalo tek artikulli paraprak i listÃ«s pÃ«rmes SHIFT+TAB ose SHIGJETÃS SIPÃR. Shtyp tastÃ«n HAPÃSIRÃ ose ENTER pÃ«r tÃ« pÃ«rzgjedhur mundÃ«sitÃ« e listÃ«s. Shtyp ESC pÃ«r tÃ« mbyllur kutinÃ« e listÃ«s."},{name:"Shiriti i RrugÃ«s sÃ« Elementeve tÃ« Redaktorit",legend:"Shtyp ${elementsPathFocus} pÃ«r tÃ« lÃ«vizur tek shiriti i elementeve. Kalo tek pulla pasuese e elementit pÃ«rmes TAB ose SHIGJETÃS DJATHTAS. Kalo tek pulla paraprake pÃ«rmes SHIFT+TAB ose SHIGJETÃS MAJTAS. Shtyp tastÃ«n HAPÃSIRÃ ose ENTER pÃ«r tÃ« pÃ«rzgjedhur elementin tek redaktuesi."}]},
{name:"Komandat",items:[{name:"Rikthe komandÃ«n",legend:"Shtyp ${undo}"},{name:"RibÃ«j komandÃ«n",legend:"Shtyp ${redo}"},{name:"Komanda e trashjes sÃ« tekstit",legend:"Shtyp ${bold}"},{name:"Komanda kursive",legend:"Shtyp ${italic}"},{name:"Komanda e nÃ«nvijÃ«zimit",legend:"Shtyp ${underline}"},{name:"Komanda e Nyjes",legend:"Shtyp ${link}"},{name:"Komanda e Mbjedhjes sÃ« KokÃ«shtrirjes",legend:"Shtyp ${toolbarCollapse}"},{name:"Qasu komandÃ«s paraprake tÃ« hapÃ«sirÃ«s sÃ« fokusimit",legend:"Shtyp ${accessPreviousSpace} pÃ«r t'iu qasur hapÃ«sirÃ«s mÃ« tÃ« afÃ«rt tÃ« paarritshme tÃ« fokusimit para simbolit ^, pÃ«r shembull: dy elemente tÃ« afÃ«rt  HR. PÃ«rsÃ«rit kombinacionin e tasteve pÃ«r tÃ« arritur hapÃ«sirÃ« tÃ« largÃ«t fokusimi."},
{name:"Qasu komandÃ«s pasuese tÃ« hapÃ«sirÃ«s sÃ« fokusimit",legend:"Shtyp ${accessNextSpace} pÃ«r t'iu qasur hapÃ«sirÃ«s mÃ« tÃ« afÃ«rt tÃ« paarritshme tÃ« fokusimit pas shenjÃ«s ^, pÃ«r shembull: dy elemente tÃ« afÃ«rt HR. PÃ«rsÃ«rit kombinacionin e tasteve pÃ«r tÃ« arritur hapÃ«sirÃ«n e largÃ«t tÃ« fokusimit."},{name:"NdihmÃ« Qasjeje",legend:"Shtyp ${a11yHelp}"},{name:"Hidhe si tekst tÃ« thjeshtÃ«",legend:"Shtyp ${pastetext}",legendEdge:"Shtyp ${pastetext}, pasuar nga ${paste}"}]}],tab:"Tab",pause:"Pause",capslock:"Caps Lock",
escape:"Escape",pageUp:"Faqja sipÃ«r",pageDown:"Faqja poshtÃ«",leftArrow:"Shigjeta majtas",upArrow:"Shigjeta sipÃ«r",rightArrow:"Shigjeta djathtas",downArrow:"Shigjeta poshtÃ«",insert:"Insert",leftWindowKey:"Pulla Majtas e Windows-it",rightWindowKey:"Pulla Djathtas e Windows-it",selectKey:"Pulla PÃ«rzgjedhÃ«se",numpad0:"Numpad 0",numpad1:"Numpad 1",numpad2:"Numpad 2",numpad3:"Numpad 3",numpad4:"Numpad 4",numpad5:"Numpad 5",numpad6:"Numpad 6",numpad7:"Numpad 7",numpad8:"Numpad 8",numpad9:"Numpad 9",multiply:"ShumÃ«zo",
add:"Shto",subtract:"Zbrit",decimalPoint:"Pika Decimale",divide:"PjesÃ«to",f1:"F1",f2:"F2",f3:"F3",f4:"F4",f5:"F5",f6:"F6",f7:"F7",f8:"F8",f9:"F9",f10:"F10",f11:"F11",f12:"F12",numLock:"Num Lock",scrollLock:"Scroll Lock",semiColon:"PikÃ«presje",equalSign:"Shenja e Barazimit",comma:"Presje",dash:"minus",period:"PikÃ«",forwardSlash:"Vija e pjerrÃ«t pÃ«rpara",graveAccent:"Shenja e theksit",openBracket:"Hape kllapÃ«n",backSlash:"Vija e pjerrÃ«t prapa",closeBracket:"Mbylle kllapÃ«n",singleQuote:"ThonjÃ«z e vetme"});