ï»¿/*
 Copyright (c) 2003-2019, CKSource - Frederico Knabben. All rights reserved.
 For licensing, see LICENSE.md or https://ckeditor.com/legal/ckeditor-oss-license
*/
CKEDITOR.plugins.setLang("a11yhelp","sr-latn",{title:"Uputstva za pomoÄ",contents:"SadrÅ¾aji za pomoÄ. Da bi ste zatvorili diÑalog pritisnite ESC.",legend:[{name:"OpÅ¡te",items:[{name:"Alatke za ureÄivanje",legend:"Pritisnite ${toolbarFocus} da bi oznaÄili alatke. Do sledeÄe i prethodne grupe alatki moÅ¾ete doÄi sa tasterom  TAB i SHIFT+TAB. Do tastera sledeÄe i predthodne grupe alatki moÅ¾ete doÄi sa tasterima STRELICA LEVO i STRELICA DESNO. Pritisnite  SPACE ili ENTER da bi aktivirali taster alatki."},
{name:"UreÄivaÄ dijaloga",legend:"U prozoru dijalog pritisnite TAB da bi doÅ¡li do sledeÄeg polja dijaloga, pritisnite ENTER za prihvatanje dijaloga, pritisnite ESC za odbijanje dijaloga. Kada dijalog ima viÅ¡e kartica, do njih moÅ¾ete doÄi pritiskom na ALT + F10 ili  TAB. Zatim sa TAB ili STRELICA  DESNO dolazite do naredne kartice."},{name:"UreÄivaÄ lokalnog menija",legend:"Pritisnite  ${contextMenu} ili APPLICATION TASTER za otvaranje lokalnog menija. Zatim sa TAB ili STRELICA DOLE moÅ¾ete preÄi na sledeÄu taÄku menija.  Prethodnu opciju moÅ¾ete postiÄi sa SHIFT+TAB ili STRELICA GORE. Pritisnite SPACE ili ENTER za odabir taÄke menija. Pritisnite SPACE ili ENTER  da bi ste otvorili podmeni trenutne stavke menija. Za povratak u glavni meni pritisnite ESC ili STRELICA DESNO. Zatvorite lokalni meni pomoÄu tastera ESC."},
{name:"UreÄjivaÄ liste",legend:"Do sledeÄÐµg elementa liste moÅ¾ete doÄi sa TAB ili STERLICA DOLE. Za odabir prethodnog elementa  pritisnite SHIFT+TAB ili STREKICA DOLE. Za odabir elementa pritisnite SPACE ili ENTER. Sa pritiskom ESC zatvarate listu. "},{name:"UredjivaÄ trake puta elemenata",legend:"Pritisnite $ {elementsPathFocus} da bi ste oznaÄili traku puta elenementa. Do sledeÄÐµg elementa  moÅ¾ete doÄi sa TAB ili STRELICA DESNO. Do prethodnÐ¾g dolazite sa SHIFT+TAB ili STRELICA DESNO. Sa SPACE ili ENTER moÅ¾ete odbrati element u uredjivaÄu."}]},
{name:"Komanda",items:[{name:"OtkaÅ¾i komandu",legend:"Pritisni ${undo}"},{name:"Prepoznavanje komande",legend:"Pritisni ${redo}"},{name:"Podebljana komanda",legend:"Pritisni ${bold}"},{name:"Kurziv komanda",legend:"Pritisni ${italic}"},{name:"Precrtana komanda",legend:"Pritisni ${underline}"},{name:"Link komanda",legend:"Pritisni ${link}"},{name:"Zatvori traku uredjivaÄa komanda ",legend:"Pritisni ${toolbarCollapse}"},{name:"Pristup prethodnom fokus mestu komanda ",legend:"Pritisni ${accessNextSpace} da bi pristupio najbliÅ¾em nedostupnom fokus mestu pre znaka hiÃ¡nyjel, na primer: dva susedna HR elementa.Ponovi kombinaciju tastera da pronadjeÅ¡ fokus mesto koje se nalazi dalje."},
{name:"Pristup sledeÄem fokus mestu komanda ",legend:"Pritisni ${accessNextSpace} da bi pristupio najbliÅ¾em nedostupnom fokus mestu posle znaka hiÃ¡nyjel, na primer: dva susedna HR elementa.Ponovi kombinaciju tastera da pronadjeÅ¡ fokus mesto koje se nalazi dalje."},{name:"PomoÄ pristupaÄnosti",legend:"Pritisni ${a11yHelp}"},{name:"Nalepi kao obiÄan tekst",legend:"Pritisnite: ${pastetext}",legendEdge:"Pritisnite ${pastetext}-t, zatim ${paste}-t"}]}],tab:"Tab",pause:"Pause",capslock:"Caps Lock",escape:"Escape",
pageUp:"Page Up",pageDown:"Page Down",leftArrow:"Strelica levo",upArrow:"strelica gore",rightArrow:"strelica desno",downArrow:"strelica dole",insert:"Insert",leftWindowKey:"levi Windows-taster",rightWindowKey:"desni Windows-taster",selectKey:"Odabir tastera",numpad0:"Tasteri sa brojevima 0",numpad1:"Tasteri sa brojevima 1",numpad2:"Tasteri sa brojevima 2",numpad3:"Tasteri sa brojevima 3",numpad4:"Tasteri sa brojevima 4",numpad5:"Tasteri sa brojevima 5",numpad6:"Tasteri sa brojevima 6",numpad7:"Tasteri sa brojevima 7",
numpad8:"Tasteri sa brojevima 8",numpad9:"Tasteri sa brojevima 9",multiply:"MnoÅ¾enje",add:"Sabiranje",subtract:"Oduzimanje",decimalPoint:"Decimalna taÄka",divide:"Deljenjje",f1:"F1",f2:"F2",f3:"F3",f4:"F4",f5:"F5",f6:"F6",f7:"F7",f8:"F8",f9:"F9",f10:"F10",f11:"F11",f12:"F12",numLock:"Num Lock",scrollLock:"Scroll Lock",semiColon:"TaÄka zarez",equalSign:"Znak jednakosti",comma:"Zarez",dash:"Crtica",period:"TaÄka",forwardSlash:"Kosa crta",graveAccent:"Obrnuti znak akcenta",openBracket:"Otvorena ÄoÅ¡kasta zagrada",
backSlash:"Obrnuta kosa crta",closeBracket:"Zatvorena ÄoÅ¡kasta zagrada",singleQuote:"Simpli znak navoda"});