ï»¿/*
 Copyright (c) 2003-2019, CKSource - Frederico Knabben. All rights reserved.
 For licensing, see LICENSE.md or https://ckeditor.com/legal/ckeditor-oss-license
*/
CKEDITOR.plugins.setLang("a11yhelp","sv",{title:"HjÃ¤lpmedelsinstruktioner",contents:"HjÃ¤lpinnehÃ¥ll. FÃ¶r att stÃ¤nga denna dialogruta trycker du pÃ¥ ESC.",legend:[{name:"AllmÃ¤nt",items:[{name:"Editor verktygsfÃ¤lt",legend:"Tryck pÃ¥ ${toolbarFocus} fÃ¶r att navigera till verktygsfÃ¤ltet. Flytta till nÃ¤sta och fÃ¶regÃ¥ende verktygsfÃ¤ltsgrupp med TAB och SHIFT+TAB. Flytta till nÃ¤sta och fÃ¶regÃ¥ende knapp i verktygsfÃ¤ltet med HÃGERPIL eller VÃNSTERPIL. Tryck SPACE eller ENTER fÃ¶r att aktivera knappen i verktygsfÃ¤ltet."},
{name:"Dialogeditor",legend:"Inuti en dialogruta, tryck TAB fÃ¶r att navigera till nÃ¤sta fÃ¤lt i dialogrutan, tryck SKIFT+TAB fÃ¶r att flytta till fÃ¶regÃ¥ende fÃ¤lt, tryck ENTER fÃ¶r att skicka. Du avbryter och stÃ¤nger dialogen med ESC. FÃ¶r dialogrutor som har flera flikar, tryck ALT+F10 eller TAB fÃ¶r att navigera till fliklistan. med fliklistan vald flytta till nÃ¤sta och fÃ¶regÃ¥ende flik med HÃGER- eller VÃNSTERPIL."},{name:"Editor fÃ¶r innehÃ¥llsmeny",legend:"Tryck pÃ¥ $ {contextMenu} eller PROGRAMTANGENTEN fÃ¶r att Ã¶ppna snabbmenyn. Flytta sedan till nÃ¤sta menyalternativ med TAB eller NEDPIL. Flytta till fÃ¶regÃ¥ende alternativ med SHIFT + TABB eller UPPIL. Tryck Space eller ENTER fÃ¶r att vÃ¤lja menyalternativ. Ãppna undermeny av nuvarande alternativ med SPACE eller ENTER eller HÃGERPIL. GÃ¥ tillbaka till Ã¶verordnade menyalternativ med ESC eller VÃNSTERPIL. StÃ¤ng snabbmenyn med ESC."},
{name:"Editor fÃ¶r list-box",legend:"Inuti en list-box, gÃ¥ till nÃ¤sta listobjekt med TAB eller NEDPIL. Flytta till fÃ¶regÃ¥ende listobjekt med SHIFT+TAB eller UPPIL. Tryck SPACE eller ENTER fÃ¶r att vÃ¤lja listan alternativet. Tryck ESC fÃ¶r att stÃ¤nga list-boxen."},{name:"Editor fÃ¶r elementens sÃ¶kvÃ¤g",legend:"Tryck pÃ¥ ${elementsPathFocus} fÃ¶r att navigera till verktygsfÃ¤ltet fÃ¶r elementens sÃ¶kvÃ¤gar. Flytta till nÃ¤sta elementknapp med TAB eller HÃGERPIL. Flytta till fÃ¶regÃ¥ende knapp med SKIFT+TAB eller VÃNSTERPIL. Tryck SPACE eller ENTER fÃ¶r att vÃ¤lja element i redigeraren."}]},
{name:"Kommandon",items:[{name:"Ãngra kommando",legend:"Tryck pÃ¥ ${undo}"},{name:"GÃ¶r om kommando",legend:"Tryck pÃ¥ ${redo}"},{name:"Kommandot fet stil",legend:"Tryck pÃ¥ ${bold}"},{name:"Kommandot kursiv",legend:"Tryck pÃ¥ ${italic}"},{name:"Kommandot understruken",legend:"Tryck pÃ¥ ${underline}"},{name:"Kommandot lÃ¤nk",legend:"Tryck pÃ¥ ${link}"},{name:"VerktygsfÃ¤lt DÃ¶lj kommandot",legend:"Tryck pÃ¥ ${toolbarCollapse}"},{name:"GÃ¥ till fÃ¶regÃ¥ende fokus plats",legend:"Tryck pÃ¥ ${accessPreviousSpace} fÃ¶r att gÃ¥ till nÃ¤rmast onÃ¥bara utrymme fÃ¶re markÃ¶ren, exempel: tvÃ¥ intilliggande HR element. Repetera tangentkombinationen fÃ¶r att gÃ¥ till nÃ¤sta."},
{name:"TillgÃ¥ nÃ¤sta fokuskommandots utrymme",legend:"Tryck ${accessNextSpace} pÃ¥ fÃ¶r att komma Ã¥t den nÃ¤rmaste onÃ¥bar fokus utrymme efter cirkumflex, till exempel: tvÃ¥ intilliggande HR element. Upprepa tangentkombinationen fÃ¶r att nÃ¥ avlÃ¤gsna fokus utrymmen."},{name:"HjÃ¤lp om tillgÃ¤nglighet",legend:"Tryck ${a11yHelp}"},{name:"Klistra in som vanlig text",legend:"Tryck ${pastetext}",legendEdge:"Tryck ${pastetext}, fÃ¶ljt av ${paste}"}]}],tab:"Tab",pause:"Paus",capslock:"Caps lock",escape:"Escape",pageUp:"Sida Up",
pageDown:"Sida Ned",leftArrow:"VÃ¤nsterpil",upArrow:"Uppil",rightArrow:"HÃ¶gerpil",downArrow:"NedÃ¥tpil",insert:"Infoga",leftWindowKey:"VÃ¤nster Windowstangent",rightWindowKey:"HÃ¶ger Windowstangent",selectKey:"VÃ¤lj tangent",numpad0:"Nummer 0",numpad1:"Nummer 1",numpad2:"Nummer 2",numpad3:"Nummer 3",numpad4:"Nummer 4",numpad5:"Nummer 5",numpad6:"Nummer 6",numpad7:"Nummer 7",numpad8:"Nummer 8",numpad9:"Nummer 9",multiply:"Multiplicera",add:"Addera",subtract:"Minus",decimalPoint:"Decimalpunkt",divide:"Dividera",
f1:"F1",f2:"F2",f3:"F3",f4:"F4",f5:"F5",f6:"F6",f7:"F7",f8:"F8",f9:"F9",f10:"F10",f11:"F11",f12:"F12",numLock:"Num Lock",scrollLock:"Scroll Lock",semiColon:"Semikolon",equalSign:"Lika med tecken",comma:"Komma",dash:"Minus",period:"Punkt",forwardSlash:"Snedstreck framÃ¥t",graveAccent:"Accent",openBracket:"Ãppningsparentes",backSlash:"Snedstreck bakÃ¥t",closeBracket:"Slutparentes",singleQuote:"Enkelt Citattecken"});