ï»¿/*
 Copyright (c) 2003-2019, CKSource - Frederico Knabben. All rights reserved.
 For licensing, see LICENSE.md or https://ckeditor.com/legal/ckeditor-oss-license
*/
CKEDITOR.plugins.setLang("a11yhelp","tr",{title:"EriÅilebilirlik TalimatlarÄ±",contents:"YardÄ±m iÃ§eriÄi. Bu pencereyi kapatmak iÃ§in ESC tuÅuna basÄ±n.",legend:[{name:"Genel",items:[{name:"DÃ¼zenleyici AraÃ§ ÃubuÄu",legend:"AraÃ§ Ã§ubuÄunda gezinmek iÃ§in ${toolbarFocus} basÄ±n. TAB ve SHIFT+TAB ile Ã¶nceki ve sonraki araÃ§ Ã§ubuÄu grubuna taÅÄ±yÄ±n. SAÄ OK veya SOL OK ile Ã¶nceki ve sonraki bir araÃ§ Ã§ubuÄu dÃ¼Ämesini hareket ettirin. SPACE tuÅuna basÄ±n veya araÃ§ Ã§ubuÄu dÃ¼Ämesini etkinleÅtirmek iÃ§in ENTER tuÅna basÄ±n."},
{name:"Diyalog DÃ¼zenleyici",legend:"Dialog penceresi iÃ§inde, sonraki iletiÅim alanÄ±na gitmek iÃ§in SEKME tuÅuna basÄ±n, Ã¶nceki alana geÃ§mek iÃ§in SHIFT + TAB tuÅuna basÄ±n, pencereyi gÃ¶ndermek iÃ§in ENTER tuÅuna basÄ±n, dialog penceresini iptal etmek iÃ§in ESC tuÅuna basÄ±n. Birden Ã§ok sekme sayfalarÄ± olan diyaloglarÄ±n, sekme listesine gitmek iÃ§in ALT + F10 tuÅlarÄ±na basÄ±n. Sonra TAB veya SAÄ OK sonraki sekmeye taÅÄ±yÄ±n. SHIFT + TAB veya SOL OK ile Ã¶nceki sekmeye geÃ§in. Sekme sayfayÄ± seÃ§mek iÃ§in SPACE veya ENTER tuÅuna basÄ±n."},
{name:"Ä°Ã§erik MenÃ¼ EditÃ¶rÃ¼",legend:"Ä°Ã§erik menÃ¼sÃ¼nÃ¼ aÃ§mak iÃ§in ${contextMenu} veya UYGULAMA TUÅU'na basÄ±n. Daha sonra SEKME veya AÅAÄI OK ile bir sonraki menÃ¼ seÃ§eneÄi taÅÄ±yÄ±n. SHIFT + TAB veya YUKARI OK ile Ã¶nceki seÃ§eneÄe gider. MenÃ¼ seÃ§eneÄini seÃ§mek iÃ§in SPACE veya ENTER tuÅuna basÄ±n. SeÃ§ili seÃ§eneÄin alt menÃ¼sÃ¼nÃ¼ SPACE ya da ENTER veya SAÄ OK aÃ§Ä±n. Ãst menÃ¼ Ã¶Äesini geÃ§mek iÃ§in ESC veya SOL OK ile geri dÃ¶nÃ¼n. ESC ile baÄlam menÃ¼sÃ¼nÃ¼ kapatÄ±n."},{name:"Liste Kutusu EditÃ¶rÃ¼",legend:"Liste kutusu iÃ§inde, bir sonraki liste Ã¶Äesine SEKME VEYA AÅAÄI OK ile taÅÄ±yÄ±n. SHIFT+TAB veya YUKARI Ã¶nceki liste Ã¶Äesi taÅÄ±yÄ±n. Liste seÃ§eneÄi seÃ§mek iÃ§in SPACE veya ENTER tuÅuna basÄ±n. Liste kutusunu kapatmak iÃ§in ESC tuÅuna basÄ±n."},
{name:"Element Yol ÃubuÄu EditÃ¶rÃ¼",legend:"Elementlerin yol Ã§ubuÄunda gezinmek iÃ§in ${ElementsPathFocus} basÄ±n. SEKME veya SAÄ OK ile sonraki element dÃ¼Ämesine taÅÄ±yÄ±n. SHIFT+TAB veya SOL OK Ã¶nceki dÃ¼Ämeye hareket ettirin. EditÃ¶r iÃ§indeki elementi seÃ§mek iÃ§in ENTER veya SPACE tuÅuna basÄ±n."}]},{name:"Komutlar",items:[{name:"Komutu geri al",legend:"$(undo)'ya basÄ±n"},{name:"Komutu geri al",legend:"${redo} basÄ±n"},{name:" KalÄ±n komut",legend:"${bold} basÄ±n"},{name:" Ä°talik komutu",legend:"${italic} basÄ±n"},
{name:" Alttan Ã§izgi komutu",legend:"${underline} basÄ±n"},{name:" BaÄlantÄ± komutu",legend:"${link} basÄ±n"},{name:" AraÃ§ Ã§ubuÄu Toplama komutu",legend:"${toolbarCollapse} basÄ±n"},{name:"Ãnceki komut alanÄ±na odaklan",legend:"DÃ¼zeltme imleÃ§inden Ã¶nce, en yakÄ±n uzaktaki alana eriÅmek iÃ§in ${accessPreviousSpace} basÄ±n, Ã¶rneÄin: iki birleÅik HR elementleri. AynÄ± tuÅ kombinasyonu tekrarÄ±yla diÄer alanlarada ulaÅÄ±n."},{name:"Sonraki komut alanÄ±na odaklan",legend:"DÃ¼zeltme imleÃ§inden sonra, en yakÄ±n uzaktaki alana eriÅmek iÃ§in ${accessNextSpace} basÄ±n, Ã¶rneÄin: iki birleÅik HR elementleri. AynÄ± tuÅ kombinasyonu tekrarÄ±yla diÄer alanlarada ulaÅÄ±n."},
{name:"EriÅilebilirlik YardÄ±mÄ±",legend:"${a11yHelp}'e basÄ±n"},{name:"DÃ¼z Metin Olarak YapÄ±ÅtÄ±r",legend:"${pastetext} basÄ±n",legendEdge:"Ãnce ${pastetext} ardÄ±ndan${paste} basÄ±n"}]}],tab:"Sekme tuÅu",pause:"Durdurma tuÅu",capslock:"BÃ¼yÃ¼k harf tuÅu",escape:"VazgeÃ§ tuÅu",pageUp:"Sayfa YukarÄ±",pageDown:"Sayfa AÅaÄÄ±",leftArrow:"Sol ok",upArrow:"YukarÄ± ok",rightArrow:"SaÄ ok",downArrow:"AÅaÄÄ± ok",insert:"Araya gir",leftWindowKey:"Sol windows tuÅu",rightWindowKey:"SaÄ windows tuÅu",selectKey:"SeÃ§me tuÅu",
numpad0:"NÃ¼merik 0",numpad1:"NÃ¼merik 1",numpad2:"NÃ¼merik 2",numpad3:"NÃ¼merik 3",numpad4:"NÃ¼merik 4",numpad5:"NÃ¼merik 5",numpad6:"NÃ¼merik 6",numpad7:"NÃ¼merik 7",numpad8:"NÃ¼merik 8",numpad9:"NÃ¼merik 9",multiply:"Ãarpma",add:"Toplama",subtract:"ÃÄ±karma",decimalPoint:"OndalÄ±k iÅareti",divide:"BÃ¶lme",f1:"F1",f2:"F2",f3:"F3",f4:"F4",f5:"F5",f6:"F6",f7:"F7",f8:"F8",f9:"F9",f10:"F10",f11:"F11",f12:"F12",numLock:"Num Lk",scrollLock:"Scr Lk",semiColon:"NoktalÄ± virgÃ¼l",equalSign:"EÅittir",comma:"VirgÃ¼l",dash:"Eksi",
period:"Nokta",forwardSlash:"Ä°leri eÄik Ã§izgi",graveAccent:"Ãst tÄ±rnak",openBracket:"Parantez aÃ§",backSlash:"Ters eÄik Ã§izgi",closeBracket:"Parantez kapa",singleQuote:"Tek tÄ±rnak"});