ï»¿/*
 Copyright (c) 2003-2019, CKSource - Frederico Knabben. All rights reserved.
 For licensing, see LICENSE.md or https://ckeditor.com/legal/ckeditor-oss-license
*/
CKEDITOR.plugins.setLang("a11yhelp","tt",{title:"Accessibility Instructions",contents:"Help Contents. To close this dialog press ESC.",legend:[{name:"ÐÐ¾Ð¼ÑÐ¼Ð¸",items:[{name:"Editor Toolbar",legend:"Press ${toolbarFocus} to navigate to the toolbar. Move to the next and previous toolbar group with TAB and SHIFT+TAB. Move to the next and previous toolbar button with RIGHT ARROW or LEFT ARROW. Press SPACE or ENTER to activate the toolbar button."},{name:"Editor Dialog",legend:"Inside a dialog, press TAB to navigate to the next dialog element, press SHIFT+TAB to move to the previous dialog element, press ENTER to submit the dialog, press ESC to cancel the dialog. When a dialog has multiple tabs, the tab list can be reached either with ALT+F10 or with TAB as part of the dialog tabbing order. With tab list focused, move to the next and previous tab with RIGHT and LEFT ARROW, respectively."},
{name:"Editor Context Menu",legend:"Press ${contextMenu} or APPLICATION KEY to open context-menu. Then move to next menu option with TAB or DOWN ARROW. Move to previous option with SHIFT+TAB or UP ARROW. Press SPACE or ENTER to select the menu option. Open sub-menu of current option with SPACE or ENTER or RIGHT ARROW. Go back to parent menu item with ESC or LEFT ARROW. Close context menu with ESC."},{name:"Editor List Box",legend:"Inside a list-box, move to next list item with TAB OR DOWN ARROW. Move to previous list item with SHIFT+TAB or UP ARROW. Press SPACE or ENTER to select the list option. Press ESC to close the list-box."},
{name:"Editor Element Path Bar",legend:"Press ${elementsPathFocus} to navigate to the elements path bar. Move to next element button with TAB or RIGHT ARROW. Move to previous button with SHIFT+TAB or LEFT ARROW. Press SPACE or ENTER to select the element in editor."}]},{name:"ÐÐ¾Ð¼Ð°Ð½Ð´Ð°Ð»Ð°Ñ",items:[{name:"ÐÐ°Ð¹ÑÐ°ÑÑ",legend:"${undo} Ð±Ð°ÑÑÐ³ÑÐ·"},{name:"ÐÐ°Ð±Ð°ÑÐ»Ð°Ñ",legend:"${redo} Ð±Ð°ÑÑÐ³ÑÐ·"},{name:"ÐÐ°Ð»ÑÐ½",legend:"${bold} Ð±Ð°ÑÑÐ³ÑÐ·"},{name:"ÐÑÑÑÐ¸Ð²",legend:"${italic} Ð±Ð°ÑÑÐ³ÑÐ·"},{name:"ÐÑÑÑÐ½Ð° ÑÑÐ·ÑÐ»Ð³Ð°Ð½",legend:"${underline} Ð±Ð°ÑÑÐ³ÑÐ·"},
{name:"Ð¡ÑÐ»ÑÐ°Ð»Ð°Ð¼Ð°",legend:"${link} Ð±Ð°ÑÑÐ³ÑÐ·"},{name:" Toolbar Collapse command",legend:"${toolbarCollapse} Ð±Ð°ÑÑÐ³ÑÐ·"},{name:" Access previous focus space command",legend:"Press ${accessPreviousSpace} to access the closest unreachable focus space before the caret, for example: two adjacent HR elements. Repeat the key combination to reach distant focus spaces."},{name:" Access next focus space command",legend:"Press ${accessNextSpace} to access the closest unreachable focus space after the caret, for example: two adjacent HR elements. Repeat the key combination to reach distant focus spaces."},
{name:" Accessibility Help",legend:"${a11yHelp} Ð±Ð°ÑÑÐ³ÑÐ·"},{name:" Paste as plain text",legend:"Press ${pastetext}",legendEdge:"Press ${pastetext}, followed by ${paste}"}]}],tab:"Tab",pause:"Ð¢ÑÐ½ÑÑ",capslock:"Caps Lock",escape:"Escape",pageUp:"Page Up",pageDown:"Page Down",leftArrow:"Ð¡ÑÐ» ÑÐºÐºÐ° ÑÐº",upArrow:"Ó¨ÑÐºÓ ÑÐ°Ð±Ð° ÑÐº",rightArrow:"Ð£Ò£ ÑÐºÐºÐ° ÑÐº",downArrow:"ÐÑÐºÐ° ÑÐ°Ð±Ð° ÑÐº",insert:"Ó¨ÑÑÓÒ¯",leftWindowKey:"Ð¡ÑÐ» Windows ÑÓ©Ð¹Ð¼ÉÑÐµ",rightWindowKey:"Ð£Ò£ Windows ÑÓ©Ð¹Ð¼ÉÑÐµ",selectKey:"Select ÑÓ©Ð¹Ð¼ÉÑÐµ",numpad0:"Numpad 0",
numpad1:"Numpad 1",numpad2:"Numpad 2",numpad3:"Numpad 3",numpad4:"Numpad 4",numpad5:"Numpad 5",numpad6:"Numpad 6",numpad7:"Numpad 7",numpad8:"Numpad 8",numpad9:"Numpad 9",multiply:"Ð¢Ð°Ð¿ÐºÑÑÐ»Ð°Ñ",add:"ÐÑÑÑ",subtract:"ÐÐ»Ñ",decimalPoint:"Ð£Ð½Ð°ÑÐ»Ñ Ð½Ð¾ÐºÑÐ°",divide:"ÐÒ¯Ð»Ò¯",f1:"F1",f2:"F2",f3:"F3",f4:"F4",f5:"F5",f6:"F6",f7:"F7",f8:"F8",f9:"F9",f10:"F10",f11:"F11",f12:"F12",numLock:"Num Lock",scrollLock:"Scroll Lock",semiColon:"ÐÐ¾ÐºÑÐ°Ð»Ñ Ó©ÑÐµÑ",equalSign:"Ð¢Ð¸Ð³ÐµÐ·Ð»ÐµÐº Ð±Ð¸Ð»Ð³ÐµÑÐµ",comma:"Ó¨ÑÐµÑ",dash:"Ð¡ÑÐ·ÑÐº",period:"ÐÓÑÓÒÓ",
forwardSlash:"ÐÑÐµÐº ÑÑÐ·ÑÐº",graveAccent:"ÐÑÐ°Ð²Ð¸Ñ",openBracket:"ÒÓÑ Ð°ÑÑ",backSlash:"ÐÐ¸ÑÐµ ÐºÑÐµÐº ÑÑÐ·ÑÐº",closeBracket:"ÒÓÑ ÑÐ±Ñ",singleQuote:"ÐÐµÑ Ð¸Ò£Ð»Ðµ ÐºÑÑÑÑÑÐ½Ð°ÐºÐ»Ð°Ñ"});