ï»¿/*
 Copyright (c) 2003-2019, CKSource - Frederico Knabben. All rights reserved.
 For licensing, see LICENSE.md or https://ckeditor.com/legal/ckeditor-oss-license
*/
CKEDITOR.plugins.setLang("specialchar","az",{euro:"Avropa valyuta iÅarÉsi",lsquo:"Sol tÉk dÄ±rnaq iÅarÉsi",rsquo:"SaÄ tÉk dÄ±rnaq iÅarÉsi",ldquo:"Sol cÃ¼t dÄ±rnaq iÅarÉsi",rdquo:"SaÄ cÃ¼t dÄ±rnaq iÅarÉsi",ndash:"ÃÄ±xma iÅarÉsi",mdash:"Tire",iexcl:"ÃevrilmiÅ nida iÅarÉsi",cent:"Sent iÅarÉsi",pound:"Funt sterlinq iÅarÉsi",curren:"Valyuta iÅarÉsi",yen:"Ä°ena iÅarÉsi",brvbar:"SÄ±nmÄ±Å zolaq",sect:"Paraqraf iÅarÉsi",uml:"Umlyaut",copy:"MÃ¼Éllif hÃ¼quqlarÄ± haqqÄ±nda iÅarÉsi",ordf:"QadÄ±n sÄ±ra indikatoru (a)",laquo:"Sola gÃ¶stÉrÉn cÃ¼t bucaqlÄ± dÄ±rnaq",
not:"QEYRÄ° iÅarÉsi",reg:"Qeyd olunmuÅ iÅarÉsi",macr:"Makron",deg:"DÉrÉcÉ iÅarÉsi",sup2:"YuxarÄ± indeks 2",sup3:"YuxarÄ± indeks 3",acute:"VurÄu iÅarÉsi",micro:"Mikro iÅarÉsi",para:"Abzas iÅarÉsi",middot:"Orta nÃ¶qtÉ",cedil:"Tsedilla iÅarÉsi",sup1:"YuxarÄ± indeks 1",ordm:"KiÅi say indikatoru (o)",raquo:"SaÄa gÃ¶stÉrÉn cÃ¼t bucaqlÄ± dÄ±rnaq",frac14:"DÃ¶rddÉ bir hissÉ kÉsri",frac12:"Bir yarÄ±m kÉsri",frac34:"DÃ¶rddÉ Ã¼Ã§ hissÉ kÉsri",iquest:"ÃevrilmiÅ sual iÅarÉsi",Agrave:"Soldan vurÄu ilÉ A",Aacute:"VurÄu ilÉ A",
Acirc:"Dam iÅarÉsi ilÉ A",Atilde:"Tilda iÅarÉsi ilÉ A",Auml:"Umlyaut ilÉ A",Aring:"DairÉli A",AElig:"Ã hÉrfi",Ccedil:"Tsedilla ilÉ C",Egrave:"Soldan vurÄu ilÉ E",Eacute:"VurÄu ilÉ E",Ecirc:"Dam iÅarÉsi ilÉ E",Euml:"Umlyaut ilÉ E",Igrave:"Soldan vurÄu ilÉ I",Iacute:"VurÄu ilÉ I",Icirc:"Dam iÅarÉsi ilÉ I",Iuml:"Umlyaut ilÉ I",ETH:"Eth latin hÉrfi",Ntilde:"Tilda iÅarÉsi ilÉ N",Ograve:"Soldan vurÄu ilÉ O",Oacute:"VurÄu ilÉ O",Ocirc:"Dam iÅarÉsi ilÉ E",Otilde:"Tilda iÅarÉsi ilÉ O",Ouml:"Umlyaut ilÉ O",
times:"Vurma iÅarÉsi",Oslash:"ÃstxÉttli O",Ugrave:"Soldan vurÄu ilÉ U",Uacute:"VurÄu ilÉ U",Ucirc:"Dam iÅarÉsi ilÉ U",Uuml:"Umlyaut ilÉ U",Yacute:"VurÄu ilÉ Y",THORN:"Thorn hÉrfi",szlig:"Ä°ti s kiÃ§ik hÉrfi",agrave:"Soldan vurÄu ilÉ a",aacute:"VurÄu ilÉ a",acirc:"Dam iÅarÉsi ilÉ a",atilde:"Tilda iÅarÉsi ilÉ a",auml:"Umlyaut ilÉ a",aring:"DairÉli a",aelig:"Ã¦ hÉrfi",ccedil:"Ã§ hÉrfi",egrave:"Soldan vurÄu ilÉ e",eacute:"VurÄu ilÉ e",ecirc:"Dam iÅarÉsi ilÉ e",euml:"Umlyaut ilÉ e",igrave:"Soldan vurÄu ilÉ i",
iacute:"VurÄu ilÉ i",icirc:"Dam iÅarÉsi ilÉ i",iuml:"Umlyaut ilÉ i",eth:"eth kiÃ§ik hÉrfi",ntilde:"Tilda iÅarÉsi ilÉ n",ograve:"Soldan vurÄu ilÉ o",oacute:"VurÄu ilÉ o",ocirc:"Dam iÅarÉsi ilÉ o",otilde:"Tilda iÅarÉsi ilÉ o",ouml:"Umlyaut ilÉ o",divide:"BÃ¶lÃ¼nmÉ iÅarÉsi",oslash:"ÃstxÉttli o",ugrave:"Soldan vurÄu ilÉ u",uacute:"VurÄu ilÉ u",ucirc:"Dam iÅarÉsi ilÉ u",uuml:"Umlyaut ilÉ u",yacute:"VurÄu ilÉ y",thorn:"Thorn kiÃ§ik hÉrfi",yuml:"Umlyaut ilÉ y",OElig:"OE ligaturasÄ±",oelig:"oe ligaturasÄ±",372:"Dam iÅarÉsi ilÉ W",
374:"Dam iÅarÉsi ilÉ Y",373:"Dam iÅarÉsi ilÉ w",375:"Dam iÅarÉsi ilÉ y",sbquo:"AÅaÄÄ± dÄ±rnaq",8219:"TÉk yuxarÄ± Ã§evrilmiÅ dÄ±rnaq",bdquo:"AÅaÄÄ± cÃ¼tlÃ¼ dÄ±rnaqlar",hellip:"ÃfÃ¼qi ellips",trade:"ÆmtÉÉ niÅanÄ±",9658:"SaÄa gÃ¶stÉrici",bull:"Marker",rarr:"SaÄa istiqamÉtlÉndirÉn ox",rArr:"SaÄa istiqamÉtlÉndirÉn cÃ¼tlÃ¼ ox",hArr:"HÉrtÉrÉfli ox",diams:"Qara kÉrpic",asymp:"TÉxmini barabÉr"});