ï»¿/*
 Copyright (c) 2003-2019, CKSource - Frederico Knabben. All rights reserved.
 For licensing, see LICENSE.md or https://ckeditor.com/legal/ckeditor-oss-license
*/
CKEDITOR.plugins.setLang("specialchar","es-mx",{euro:"Signo de Euro",lsquo:"Comillas simple izquierda",rsquo:"Comillas simple derecha",ldquo:"Comillas dobles izquierda",rdquo:"Comillas dobles derecha",ndash:"GuiÃ³n corto",mdash:"GuiÃ³n largo",iexcl:"Signo de exclamaciÃ³n invertido",cent:"Signo de centavo",pound:"Signo de Libra",curren:"Signo de moneda",yen:"Signo de Yen",brvbar:"Barra rota",sect:"Signo de la secciÃ³n",uml:"DiÃ©resis",copy:"Signo de Derechos reservados",ordf:"Indicador ordinal femenino",
laquo:"SeÃ±al de doble Ã¡ngulo hacia la izquierda",not:"Sin signo",reg:"Signo registrado",macr:"Macron",deg:"signo de grados",sup2:"SuperÃ­ndice dos",sup3:"SuperÃ­ndice tres",acute:"Acento agudo",micro:"Signo micro",para:"Signo pilcrow",middot:"Punto medio",cedil:"Cedilla",sup1:"SuperÃ­ndice uno",ordm:"Indicador ordinal masculino",raquo:"SeÃ±al de doble Ã¡ngulo hacia la derecha",frac14:"FracciÃ³n un cuarto",frac12:"FracciÃ³n medio",frac34:"FracciÃ³n tres cuartos",iquest:"Signo de interrogaciÃ³n invertido",Agrave:"Letra mayÃºscula latina A con acento grave",
Aacute:"Letra mayÃºscula latina A con acento agudo",Acirc:"Letra mayÃºscula latina A con circunflexo",Atilde:"Letra mayÃºscula latina A con tilde",Auml:"Letra mayÃºscula latina A con diÃ©resis",Aring:"Letra mayÃºscula latina A con anillo arriba",AElig:"Letra mayÃºscula latina Ã",Ccedil:"Letra mayÃºscula latina C con cedilla",Egrave:"Letra mayÃºscula latina E con acento grave",Eacute:"Letra mayÃºscula latina E con acento agudo",Ecirc:"Letra mayÃºscula latina E con circumflex",Euml:"Letra mayÃºscula latina E con diÃ©resis",
Igrave:"Letra mayÃºscula latina I con acento grave",Iacute:"Letra mayÃºscula latina I con acento agudo",Icirc:"Letra mayÃºscula latina I con circumflex",Iuml:"Letra mayÃºscula latina E con diÃ©resis",ETH:"Letra mayÃºscula latina Eth",Ntilde:"Letra mayÃºscula latina N con tilde",Ograve:"Letra mayÃºscula latina O con acento grave",Oacute:"Letra mayÃºscula latina O con acento agudo",Ocirc:"Letra mayÃºscula latina O con circumflex",Otilde:"Letra mayÃºscula latina O con tilde",Ouml:"Letra mayÃºscula latina O con diÃ©resis",
times:"Signo de multiplicaciÃ³n",Oslash:"Letra mayÃºscula latina O con trazo",Ugrave:"Letra mayÃºscula latina U con acento grave",Uacute:"Letra mayÃºscula latina U con acento agudo",Ucirc:"Letra mayÃºscula latina U con circumflex",Uuml:"Letra mayÃºscula latina U con diÃ©resis",Yacute:"Letra mayÃºscula latina Y con acento agudo",THORN:"Letra mayÃºscula latina Thorn",szlig:"Letra pequeÃ±a latina s",agrave:"Letra pequeÃ±a latina a con acento grave",aacute:"Letra pequeÃ±a latina a con acento agudo",acirc:"Letra pequeÃ±a latina a con circumflex",
atilde:"Letra pequeÃ±a latina a con tilde",auml:"Letra pequeÃ±a latina a con diÃ©resis",aring:"Letra pequeÃ±a latina a con anillo arriba",aelig:"Letra pequeÃ±a latina Ã¦",ccedil:"Letra pequeÃ±a latina c con cedilla",egrave:"Letra pequeÃ±a latina e con acento grave",eacute:"Letra pequeÃ±a latina e con acento agudo",ecirc:"Letra pequeÃ±a latina e con circumflex",euml:"Letra pequeÃ±a latina e con diÃ©resis",igrave:"Letra pequeÃ±a latina i con acento grave",iacute:"Letra pequeÃ±a latina i con acento agudo",icirc:"Letra pequeÃ±a latina i con circumflex",
iuml:"Letra pequeÃ±a latina i con diÃ©resis",eth:"Letra pequeÃ±a latina eth",ntilde:"Letra pequeÃ±a latina n con tilde",ograve:"Letra pequeÃ±a latina o con acento grave",oacute:"Letra pequeÃ±a latina o con acento agudo",ocirc:"Letra pequeÃ±a latina o con circumflex",otilde:"Letra pequeÃ±a latina o con tilde",ouml:"Letra pequeÃ±a latina o con diÃ©resis",divide:"Signo de divisiÃ³n",oslash:"Letra pequeÃ±a latina o con trazo",ugrave:"Letra pequeÃ±a latina u con acento grave",uacute:"Letra pequeÃ±a latina u con acento agudo",
ucirc:"Letra pequeÃ±a latina u con circumflex",uuml:"Letra pequeÃ±a latina u con diÃ©resis",yacute:"Letra pequeÃ±a latina y con acento agudo",thorn:"Espina de letra pequeÃ±a latina",yuml:"Letra pequeÃ±a latina y con diÃ©resis",OElig:"Ligadura de capital latino OE",oelig:"Ligadura de pequeÃ±a latino OE",372:"Letra latina mayÃºscula W con circunflexo",374:"Letra latina mayÃºscula Y con circunflexo",373:"Letra latina minÃºscula w con circunflexo",375:"Letra latina minÃºscula y con circunflexo",sbquo:"Signo de comillas simple abajo",
8219:"Signo de comillas simple arriba",bdquo:"Signo de doble comillas abajo",hellip:"Elipsis horizontal",trade:"Signo merccantl",9658:"Puntero derecho negro",bull:"Bala",rarr:"Flecha hacia la derecha",rArr:"Doble flecha hacia la derecha",hArr:"Flecha doble izquierda derecha",diams:"Palo de diamante negro",asymp:"Casi igual a"});