ï»¿/*
 Copyright (c) 2003-2019, CKSource - Frederico Knabben. All rights reserved.
 For licensing, see LICENSE.md or https://ckeditor.com/legal/ckeditor-oss-license
*/
CKEDITOR.plugins.setLang("specialchar","es",{euro:"SÃ­mbolo de euro",lsquo:"Comilla simple izquierda",rsquo:"Comilla simple derecha",ldquo:"Comilla doble izquierda",rdquo:"Comilla doble derecha",ndash:"GuiÃ³n corto",mdash:"GuiÃ³n medio largo",iexcl:"Signo de admiraciÃ³n invertido",cent:"SÃ­mbolo centavo",pound:"SÃ­mbolo libra",curren:"SÃ­mbolo moneda",yen:"SÃ­mbolo yen",brvbar:"Barra vertical rota",sect:"SÃ­mbolo secciÃ³n",uml:"DiÃ©resis",copy:"Signo de derechos de autor",ordf:"Indicador ordinal femenino",laquo:"Abre comillas angulares",
not:"Signo negaciÃ³n",reg:"Signo de marca registrada",macr:"GuiÃ³n alto",deg:"Signo de grado",sup2:"SuperÃ­ndice dos",sup3:"SuperÃ­ndice tres",acute:"Acento agudo",micro:"Signo micro",para:"Signo de pi",middot:"Punto medio",cedil:"Cedilla",sup1:"SuperÃ­ndice uno",ordm:"Indicador orginal masculino",raquo:"Cierra comillas angulares",frac14:"FracciÃ³n ordinaria de un quarto",frac12:"FracciÃ³n ordinaria de una mitad",frac34:"FracciÃ³n ordinaria de tres cuartos",iquest:"Signo de interrogaciÃ³n invertido",Agrave:"Letra A latina mayÃºscula con acento grave",
Aacute:"Letra A latina  mayÃºscula con acento agudo",Acirc:"Letra A latina mayÃºscula con acento circunflejo",Atilde:"Letra A latina mayÃºscula con tilde",Auml:"Letra A latina mayÃºscula con diÃ©resis",Aring:"Letra A latina mayÃºscula con aro arriba",AElig:"Letra Ã latina mayÃºscula",Ccedil:"Letra C latina mayÃºscula con cedilla",Egrave:"Letra E latina mayÃºscula con acento grave",Eacute:"Letra E latina mayÃºscula con acento agudo",Ecirc:"Letra E latina mayÃºscula con acento circunflejo",Euml:"Letra E latina mayÃºscula con diÃ©resis",
Igrave:"Letra I latina mayÃºscula con acento grave",Iacute:"Letra I latina mayÃºscula con acento agudo",Icirc:"Letra I latina mayÃºscula con acento circunflejo",Iuml:"Letra I latina mayÃºscula con diÃ©resis",ETH:"Letra Eth latina mayÃºscula",Ntilde:"Letra N latina mayÃºscula con tilde",Ograve:"Letra O latina mayÃºscula con acento grave",Oacute:"Letra O latina mayÃºscula con acento agudo",Ocirc:"Letra O latina mayÃºscula con acento circunflejo",Otilde:"Letra O latina mayÃºscula con tilde",Ouml:"Letra O latina mayÃºscula con diÃ©resis",
times:"Signo de multiplicaciÃ³n",Oslash:"Letra O latina mayÃºscula con barra inclinada",Ugrave:"Letra U latina mayÃºscula con acento grave",Uacute:"Letra U latina mayÃºscula con acento agudo",Ucirc:"Letra U latina mayÃºscula con acento circunflejo",Uuml:"Letra U latina mayÃºscula con diÃ©resis",Yacute:"Letra Y latina mayÃºscula con acento agudo",THORN:"Letra Thorn latina mayÃºscula",szlig:"Letra s latina fuerte pequeÃ±a",agrave:"Letra a latina pequeÃ±a con acento grave",aacute:"Letra a latina pequeÃ±a con acento agudo",
acirc:"Letra a latina pequeÃ±a con acento circunflejo",atilde:"Letra a latina pequeÃ±a con tilde",auml:"Letra a latina pequeÃ±a con diÃ©resis",aring:"Letra a latina pequeÃ±a con aro arriba",aelig:"Letra Ã¦ latina pequeÃ±a",ccedil:"Letra c latina pequeÃ±a con cedilla",egrave:"Letra e latina pequeÃ±a con acento grave",eacute:"Letra e latina pequeÃ±a con acento agudo",ecirc:"Letra e latina pequeÃ±a con acento circunflejo",euml:"Letra e latina pequeÃ±a con diÃ©resis",igrave:"Letra i latina pequeÃ±a con acento grave",
iacute:"Letra i latina pequeÃ±a con acento agudo",icirc:"Letra i latina pequeÃ±a con acento circunflejo",iuml:"Letra i latina pequeÃ±a con diÃ©resis",eth:"Letra eth latina pequeÃ±a",ntilde:"Letra n latina pequeÃ±a con tilde",ograve:"Letra o latina pequeÃ±a con acento grave",oacute:"Letra o latina pequeÃ±a con acento agudo",ocirc:"Letra o latina pequeÃ±a con acento circunflejo",otilde:"Letra o latina pequeÃ±a con tilde",ouml:"Letra o latina pequeÃ±a con diÃ©resis",divide:"Signo de divisiÃ³n",oslash:"Letra o latina minÃºscula con barra inclinada",
ugrave:"Letra u latina pequeÃ±a con acento grave",uacute:"Letra u latina pequeÃ±a con acento agudo",ucirc:"Letra u latina pequeÃ±a con acento circunflejo",uuml:"Letra u latina pequeÃ±a con diÃ©resis",yacute:"Letra u latina pequeÃ±a con acento agudo",thorn:"Letra thorn latina minÃºscula",yuml:"Letra y latina pequeÃ±a con diÃ©resis",OElig:"Diptongo OE latino en mayÃºscula",oelig:"Diptongo oe latino en minÃºscula",372:"Letra W latina mayÃºscula con acento circunflejo",374:"Letra Y latina mayÃºscula con acento circunflejo",
373:"Letra w latina pequeÃ±a con acento circunflejo",375:"Letra y latina pequeÃ±a con acento circunflejo",sbquo:"Comilla simple baja-9",8219:"Comilla simple alta invertida-9",bdquo:"Comillas dobles bajas-9",hellip:"Puntos suspensivos horizontales",trade:"Signo de marca registrada",9658:"Apuntador negro apuntando a la derecha",bull:"ViÃ±eta",rarr:"Flecha a la derecha",rArr:"Flecha doble a la derecha",hArr:"Flecha izquierda derecha doble",diams:"Diamante negro",asymp:"Casi igual a"});