ï»¿/*
 Copyright (c) 2003-2019, CKSource - Frederico Knabben. All rights reserved.
 For licensing, see LICENSE.md or https://ckeditor.com/legal/ckeditor-oss-license
*/
CKEDITOR.plugins.setLang("specialchar","et",{euro:"EuromÃ¤rk",lsquo:"Alustav Ã¼hekordne jutumÃ¤rk",rsquo:"LÃµpetav Ã¼hekordne jutumÃ¤rk",ldquo:"Alustav kahekordne jutumÃ¤rk",rdquo:"LÃµpetav kahekordne jutumÃ¤rk",ndash:"Enn-kriips",mdash:"Emm-kriips",iexcl:"PÃ¶Ã¶ratud hÃ¼Ã¼umÃ¤rk",cent:"SendimÃ¤rk",pound:"Naela mÃ¤rk",curren:"ValuutamÃ¤rk",yen:"Jeeni mÃ¤rk",brvbar:"Katkestatud kriips",sect:"LÃµigu mÃ¤rk",uml:"TÃ¤pid",copy:"AutoriÃµiguse mÃ¤rk",ordf:"Naissoost jÃ¤rjestuse mÃ¤rk",laquo:"Alustav kahekordne nurk jutumÃ¤rk",not:"Ei-mÃ¤rk",
reg:"KaubamÃ¤rk registreeritud mÃ¤rk",macr:"PikkusmÃ¤rk",deg:"KraadimÃ¤rk",sup2:"Ãlaindeks kaks",sup3:"Ãlaindeks kolm",acute:"AkuutrÃµhk",micro:"Mikro-mÃ¤rk",para:"LÃµigumÃ¤rk",middot:"Keskpunkt",cedil:"Sedii",sup1:"Ãlaindeks Ã¼ks",ordm:"Meessoost jÃ¤rjestuse mÃ¤rk",raquo:"LÃµpetav kahekordne nurk jutumÃ¤rk",frac14:"Lihtmurd veerand",frac12:"Lihtmurd pool",frac34:"Lihtmurd kolmveerand",iquest:"PÃ¶Ã¶ratud kÃ¼simÃ¤rk",Agrave:"Ladina suur A graavisega",Aacute:"Ladina suur A akuudiga",Acirc:"Ladina suur A tsirkumfleksiga",
Atilde:"Ladina suur A tildega",Auml:"Ladina suur A tÃ¤ppidega",Aring:"Ladina suur A Ã¼lasÃµÃµriga",AElig:"Ladina suur AE",Ccedil:"Ladina suur E sediiga",Egrave:"Ladina suur E graavisega",Eacute:"Ladina suur E akuudiga",Ecirc:"Ladina suur E tsirkumfleksiga",Euml:"Ladina suur E tÃ¤ppidega",Igrave:"Ladina suur I graavisega",Iacute:"Ladina suur I akuudiga",Icirc:"Ladina suur I tsirkumfleksiga",Iuml:"Ladina suur I tÃ¤ppidega",ETH:"Ladina suur ETH",Ntilde:"Ladina suur N tildega",Ograve:"Ladina suur O graavisega",
Oacute:"Ladina suur O akuudiga",Ocirc:"Ladina suur O tsirkumfleksiga",Otilde:"Ladina suur O tildega",Ouml:"TÃ¤ppidega ladina suur O",times:"KorrutusmÃ¤rk",Oslash:"Ladina suur O kaldkriipsuga",Ugrave:"Ladina suur U graavisega",Uacute:"Ladina suur U akuudiga",Ucirc:"Kandilise katusega suur ladina U",Uuml:"TÃ¤ppidega ladina suur U",Yacute:"Ladina suur Y akuudiga",THORN:"Ladina suur THORN",szlig:"Ladina vÃ¤ike terav s",agrave:"Ladina vÃ¤ike a graavisega",aacute:"Ladina vÃ¤ike a akuudiga",acirc:"Kandilise katusega ladina vÃ¤ike a",
atilde:"Tildega ladina vÃ¤ike a",auml:"TÃ¤ppidega ladina vÃ¤ike a",aring:"Ladina vÃ¤ike a Ã¼lasÃµÃµriga",aelig:"Ladina vÃ¤ike ae",ccedil:"Ladina vÃ¤ike c sediiga",egrave:"Ladina vÃ¤ike e graavisega",eacute:"Ladina vÃ¤ike e akuudiga",ecirc:"Ladina vÃ¤ike e Ã¼lasÃµÃµriga",euml:"Ladina vÃ¤ike e tÃ¤ppidega",igrave:"Ladina vÃ¤ike i graavisega",iacute:"Ladina vÃ¤ike i akuudiga",icirc:"Ladina vÃ¤ike i tsirkumfleksiga",iuml:"Ladina vÃ¤ike i tÃ¤ppidega",eth:"Ladina vÃ¤ike ETH",ntilde:"Ladina vÃ¤ike n tildega",ograve:"Ladina vÃ¤ike o graavisega",
oacute:"Ladina vÃ¤ike o akuudiga",ocirc:"Ladina vÃ¤ike o tsirkumfleksiga",otilde:"Ladina vÃ¤ike o tildega",ouml:"Ladina vÃ¤ike o tÃ¤ppidega",divide:"JagamismÃ¤rk",oslash:"Ladina vÃ¤ike o lÃ¤biva kaldkriipsuga",ugrave:"Ladina vÃ¤ike u graavisega",uacute:"Ladina vÃ¤ike u akuudiga",ucirc:"Ladina vÃ¤ike u tsirkumfleksiga",uuml:"Ladina vÃ¤ike u tÃ¤ppidega",yacute:"Ladina vÃ¤ike y akuudiga",thorn:"Ladina vÃ¤ike THORN",yuml:"Ladina vÃ¤ike y tÃ¤ppidega",OElig:"Ladina suur ligatuur OE",oelig:"Ladina vÃ¤ike ligatuur OE",372:"Ladina suur W tsirkumfleksiga",
374:"Ladina suur Y tsirkumfleksiga",373:"Ladina vÃ¤ike w tsirkumfleksiga",375:"Ladina vÃ¤ike y tsirkumfleksiga",sbquo:"Ãhekordne jutumÃ¤rk Ã¼heksa all",8219:"Ãhekordne jutumÃ¤rk kuus Ã¼leval",bdquo:"Kahekordne jutumÃ¤rk Ã¼heksa all",hellip:"Horisontaalne kolmikpunkt",trade:"KaubamÃ¤rgi mÃ¤rk",9658:"Must nool paremale",bull:"Kuul",rarr:"Nool paremale",rArr:"Topeltnool paremale",hArr:"Topeltnool vasakule",diams:"Must romb",asymp:"Ligikaudu vÃµrdne"});