ï»¿/*
 Copyright (c) 2003-2019, CKSource - Frederico Knabben. All rights reserved.
 For licensing, see LICENSE.md or https://ckeditor.com/legal/ckeditor-oss-license
*/
CKEDITOR.plugins.setLang("specialchar","fr-ca",{euro:"Symbole Euro",lsquo:"Guillemet simple ouvrant",rsquo:"Guillemet simple fermant",ldquo:"Guillemet double ouvrant",rdquo:"Guillemet double fermant",ndash:"Tiret haut",mdash:"Tiret",iexcl:"Point d'exclamation inversÃ©",cent:"Symbole de cent",pound:"Symbole de Livre Sterling",curren:"Symbole monÃ©taire",yen:"Symbole du Yen",brvbar:"Barre scindÃ©e",sect:"Symbole de section",uml:"TrÃ©ma",copy:"Symbole de copyright",ordf:"Indicateur ordinal fÃ©minin",laquo:"Guillemet franÃ§ais ouvrant",
not:"Indicateur de nÃ©gation",reg:"Symbole de marque dÃ©posÃ©e",macr:"Macron",deg:"DegrÃ©",sup2:"Exposant 2",sup3:"Exposant 3",acute:"Accent aigÃ¼e",micro:"Symbole micro",para:"Paragraphe",middot:"Point mÃ©dian",cedil:"CÃ©dille",sup1:"Exposant 1",ordm:"Indicateur ordinal masculin",raquo:"Guillemet franÃ§ais fermant",frac14:"Un quart",frac12:"Une demi",frac34:"Trois quart",iquest:"Point d'interrogation inversÃ©",Agrave:"A accent grave",Aacute:"A accent aigÃ¼e",Acirc:"A circonflexe",Atilde:"A tilde",Auml:"A trÃ©ma",
Aring:"A avec un rond au dessus",AElig:"Ã majuscule",Ccedil:"C cÃ©dille",Egrave:"E accent grave",Eacute:"E accent aigÃ¼e",Ecirc:"E accent circonflexe",Euml:"E trÃ©ma",Igrave:"I accent grave",Iacute:"I accent aigÃ¼e",Icirc:"I accent circonflexe",Iuml:"I trÃ©ma",ETH:"Lettre majuscule islandaise ED",Ntilde:"N tilde",Ograve:"O accent grave",Oacute:"O accent aigÃ¼e",Ocirc:"O accent circonflexe",Otilde:"O tilde",Ouml:"O trÃ©ma",times:"Symbole de multiplication",Oslash:"O barrÃ©",Ugrave:"U accent grave",Uacute:"U accent aigÃ¼e",
Ucirc:"U accent circonflexe",Uuml:"U trÃ©ma",Yacute:"Y accent aigÃ¼e",THORN:"Lettre islandaise Thorn majuscule",szlig:"Lettre minuscule allemande s dur",agrave:"a accent grave",aacute:"a accent aigÃ¼e",acirc:"a accent circonflexe",atilde:"a tilde",auml:"a trÃ©ma",aring:"a avec un cercle au dessus",aelig:"Ã¦",ccedil:"c cÃ©dille",egrave:"e accent grave",eacute:"e accent aigÃ¼e",ecirc:"e accent circonflexe",euml:"e trÃ©ma",igrave:"i accent grave",iacute:"i accent aigÃ¼e",icirc:"i accent circonflexe",iuml:"i trÃ©ma",
eth:"Lettre minuscule islandaise ED",ntilde:"n tilde",ograve:"o accent grave",oacute:"o accent aigÃ¼e",ocirc:"O accent circonflexe",otilde:"O tilde",ouml:"O trÃ©ma",divide:"Symbole de division",oslash:"o barrÃ©",ugrave:"u accent grave",uacute:"u accent aigÃ¼e",ucirc:"u accent circonflexe",uuml:"u trÃ©ma",yacute:"y accent aigÃ¼e",thorn:"Lettre islandaise thorn minuscule",yuml:"y trÃ©ma",OElig:"ligature majuscule latine Å",oelig:"ligature minuscule latine Å",372:"W accent circonflexe",374:"Y accent circonflexe",
373:"w accent circonflexe",375:"y accent circonflexe",sbquo:"Guillemet simple fermant",8219:"Guillemet-virgule supÃ©rieur culbutÃ©",bdquo:"Guillemet-virgule double infÃ©rieur",hellip:"Points de suspension",trade:"Symbole de marque dÃ©posÃ©e",9658:"FlÃ¨che noire pointant vers la droite",bull:"Puce",rarr:"FlÃ¨che vers la droite",rArr:"FlÃ¨che double vers la droite",hArr:"FlÃ¨che double vers la gauche",diams:"Carreau",asymp:"Presque Ã©gal"});