ï»¿/*
 Copyright (c) 2003-2019, CKSource - Frederico Knabben. All rights reserved.
 For licensing, see LICENSE.md or https://ckeditor.com/legal/ckeditor-oss-license
*/
CKEDITOR.plugins.setLang("specialchar","fr",{euro:"Symbole euro",lsquo:"Guillemet simple ouvrant",rsquo:"Guillemet simple fermant",ldquo:"Guillemet double ouvrant",rdquo:"Guillemet double fermant",ndash:"Tiret demi-cadratin",mdash:"Tiret cadratin",iexcl:"Point d'exclamation inversÃ©",cent:"Symbole cent",pound:"Symbole Livre sterling",curren:"Symbole monÃ©taire",yen:"Symbole yen",brvbar:"Barre verticale scindÃ©e",sect:"Signe de section",uml:"TrÃ©ma",copy:"Symbole Copyright",ordf:"Indicateur ordinal fÃ©minin",
laquo:"Guillemet franÃ§ais ouvrant",not:"Crochet de nÃ©gation",reg:"Symbole de marque dÃ©posÃ©e",macr:"Macron",deg:"Symbole degrÃ©",sup2:"Exposant 2",sup3:"Exposant 3",acute:"Accent aigu",micro:"Symbole micro",para:"Symbole pied-de-mouche",middot:"Point mÃ©dian",cedil:"CÃ©dille",sup1:"Exposant 1",ordm:"Indicateur ordinal masculin",raquo:"Guillemet franÃ§ais fermant",frac14:"Fraction un quart",frac12:"Fraction un demi",frac34:"Fraction trois quarts",iquest:"Point d'interrogation inversÃ©",Agrave:"A accent grave majuscule",
Aacute:"A accent aigu majuscule",Acirc:"A accent circonflexe majuscule",Atilde:"A caron majuscule",Auml:"A trÃ©ma majuscule",Aring:"A rond majuscule",AElig:"Ligature Ã majuscule",Ccedil:"C cÃ©dille majuscule",Egrave:"E accent grave majuscule",Eacute:"E accent aigu majuscule",Ecirc:"E accent circonflexe majuscule",Euml:"E trÃ©ma majuscule",Igrave:"I accent grave majuscule",Iacute:"I accent aigu majuscule",Icirc:"I accent circonflexe majuscule",Iuml:"I trÃ©ma majuscule",ETH:"Lettre majuscule islandaise ED",
Ntilde:"N caron majuscule",Ograve:"O accent grave majuscule",Oacute:"O accent aigu majuscule",Ocirc:"O accent circonflexe majuscule",Otilde:"O caron majuscule",Ouml:"O trÃ©ma majuscule",times:"Symbole de multiplication",Oslash:"O barrÃ© majuscule",Ugrave:"U accent grave majuscule",Uacute:"U accent aigu majuscule",Ucirc:"U accent circonflexe majuscule",Uuml:"U trÃ©ma majuscule",Yacute:"Y accent aigu majuscule",THORN:"Lettre islandaise thorn majuscule",szlig:"Lettre minuscule allemande S dur",agrave:"A accent grave minuscule",
aacute:"A accent aigu minuscule",acirc:"A accent circonflexe minuscule",atilde:"A tilde minuscule",auml:"A trÃ©ma minuscule",aring:"A rond minuscule",aelig:"Ligature Ã minuscule",ccedil:"C cÃ©dille minuscule",egrave:"E accent grave minuscule",eacute:"E accent aigu minuscule",ecirc:"E accent circonflexe minuscule",euml:"E trÃ©ma minuscule",igrave:"I accent grave minuscule",iacute:"I accent aigu minuscule",icirc:"I accent circonflexe minuscule",iuml:"i minuscule trÃ©ma",eth:"Lettre minuscule islandaise ED",
ntilde:"N caron minuscule",ograve:"O minuscule accent grave",oacute:"O accent aigu minuscule",ocirc:"O accent circonflexe minuscule",otilde:"O tilde minuscule",ouml:"O trÃ©ma minuscule",divide:"Symbole de division",oslash:"O barrÃ© minuscule",ugrave:"U accent grave minuscule",uacute:"U accent aigu minuscule",ucirc:"U accent circonflexe minuscule",uuml:"U trÃ©ma minuscule",yacute:"Y accent aigu minuscule",thorn:"Lettre islandaise thorn minuscule",yuml:"Y trÃ©ma minuscule",OElig:"Ligature Å majuscule",
oelig:"Ligature Å minuscule",372:"W accent circonflexe majuscule",374:"Y accent circonflexe majuscule",373:"W accent circonflexe minuscule",375:"Y accent circonflexe minuscule",sbquo:"Guillemet simple fermant infÃ©rieur",8219:"Guillemet-virgule supÃ©rieur culbutÃ©",bdquo:"Guillemet-virgule double infÃ©rieur",hellip:"Points de suspension",trade:"Symbole de marque commerciale",9658:"FlÃ¨che noire pointant vers la droite",bull:"Gros point mÃ©dian",rarr:"FlÃ¨che vers la droite",rArr:"Double flÃ¨che vers la droite",
hArr:"Double flÃ¨che vers la gauche",diams:"Losange noir",asymp:"Environ Ã©gal"});