ï»¿/*
 Copyright (c) 2003-2019, CKSource - Frederico Knabben. All rights reserved.
 For licensing, see LICENSE.md or https://ckeditor.com/legal/ckeditor-oss-license
*/
CKEDITOR.plugins.setLang("specialchar","gl",{euro:"SÃ­mbolo do euro",lsquo:"ComiÃ±a simple esquerda",rsquo:"ComiÃ±a simple dereita",ldquo:"ComiÃ±as dobres esquerda",rdquo:"ComiÃ±as dobres dereita",ndash:"GuiÃ³n",mdash:"Raia",iexcl:"Signo de admiraciÃ³n invertido",cent:"SÃ­mbolo do centavo",pound:"SÃ­mbolo da libra",curren:"SÃ­mbolo de moeda",yen:"SÃ­mbolo do yen",brvbar:"Barra vertical rota",sect:"SÃ­mbolo de secciÃ³n",uml:"DiÃ©rese",copy:"SÃ­mbolo de dereitos de autorÃ­a",ordf:"Indicador ordinal feminino",laquo:"ComiÃ±as latinas, apertura",
not:"Signo negaciÃ³n",reg:"SÃ­mbolo de marca rexistrada",macr:"GuiÃ³n alto",deg:"Signo de grao",sup2:"SuperÃ­ndice dous",sup3:"SuperÃ­ndice tres",acute:"Acento agudo",micro:"Signo de micro",para:"Signo de pi",middot:"Punto medio",cedil:"Cedilla",sup1:"SuperÃ­ndice un",ordm:"Indicador ordinal masculino",raquo:"ComiÃ±as latinas, peche",frac14:"FracciÃ³n ordinaria de un cuarto",frac12:"FracciÃ³n ordinaria de un medio",frac34:"FracciÃ³n ordinaria de tres cuartos",iquest:"Signo de interrogaciÃ³n invertido",Agrave:"Letra A latina maiÃºscula con acento grave",
Aacute:"Letra A latina maiÃºscula con acento agudo",Acirc:"Letra A latina maiÃºscula con acento circunflexo",Atilde:"Letra A latina maiÃºscula con til",Auml:"Letra A latina maiÃºscula con diÃ©rese",Aring:"Letra A latina maiÃºscula con aro enriba",AElig:"Letra Ã latina maiÃºscula",Ccedil:"Letra C latina maiÃºscula con cedilla",Egrave:"Letra E latina maiÃºscula con acento grave",Eacute:"Letra E latina maiÃºscula con acento agudo",Ecirc:"Letra E latina maiÃºscula con acento circunflexo",Euml:"Letra E latina maiÃºscula con diÃ©rese",
Igrave:"Letra I latina maiÃºscula con acento grave",Iacute:"Letra I latina maiÃºscula con acento agudo",Icirc:"Letra I latina maiÃºscula con acento circunflexo",Iuml:"Letra I latina maiÃºscula con diÃ©rese",ETH:"Letra Ed latina maiÃºscula",Ntilde:"Letra N latina maiÃºscula con til",Ograve:"Letra O latina maiÃºscula con acento grave",Oacute:"Letra O latina maiÃºscula con acento agudo",Ocirc:"Letra O latina maiÃºscula con acento circunflexo",Otilde:"Letra O latina maiÃºscula con til",Ouml:"Letra O latina maiÃºscula con diÃ©rese",
times:"Signo de multiplicaciÃ³n",Oslash:"Letra O latina maiÃºscula con barra transversal",Ugrave:"Letra U latina maiÃºscula con acento grave",Uacute:"Letra U latina maiÃºscula con acento agudo",Ucirc:"Letra U latina maiÃºscula con acento circunflexo",Uuml:"Letra U latina maiÃºscula con diÃ©rese",Yacute:"Letra Y latina maiÃºscula con acento agudo",THORN:"Letra Thorn latina maiÃºscula",szlig:"Letra s latina forte minÃºscula",agrave:"Letra a latina minÃºscula con acento grave",aacute:"Letra a latina minÃºscula con acento agudo",
acirc:"Letra a latina minÃºscula con acento circunflexo",atilde:"Letra a latina minÃºscula con til",auml:"Letra a latina minÃºscula con diÃ©rese",aring:"Letra a latina minÃºscula con aro enriba",aelig:"Letra Ã¦ latina minÃºscula",ccedil:"Letra c latina minÃºscula con cedilla",egrave:"Letra e latina minÃºscula con acento grave",eacute:"Letra e latina minÃºscula con acento agudo",ecirc:"Letra e latina minÃºscula con acento circunflexo",euml:"Letra e latina minÃºscula con diÃ©rese",igrave:"Letra i latina minÃºscula con acento grave",
iacute:"Letra i latina minÃºscula con acento agudo",icirc:"Letra i latina minÃºscula con acento circunflexo",iuml:"Letra i latina minÃºscula con diÃ©rese",eth:"Letra ed latina minÃºscula",ntilde:"Letra n latina minÃºscula con til",ograve:"Letra o latina minÃºscula con acento grave",oacute:"Letra o latina minÃºscula con acento agudo",ocirc:"Letra o latina minÃºscula con acento circunflexo",otilde:"Letra o latina minÃºscula con til",ouml:"Letra o latina minÃºscula con diÃ©rese",divide:"Signo de divisiÃ³n",oslash:"Letra o latina minÃºscula con barra transversal",
ugrave:"Letra u latina minÃºscula con acento grave",uacute:"Letra u latina minÃºscula con acento agudo",ucirc:"Letra u latina minÃºscula con acento circunflexo",uuml:"Letra u latina minÃºscula con diÃ©rese",yacute:"Letra y latina minÃºscula con acento agudo",thorn:"Letra Thorn latina minÃºscula",yuml:"Letra y latina minÃºscula con diÃ©rese",OElig:"Ligadura OE latina maiÃºscula",oelig:"Ligadura oe latina minÃºscula",372:"Letra W latina maiÃºscula con acento circunflexo",374:"Letra Y latina maiÃºscula con acento circunflexo",
373:"Letra w latina minÃºscula con acento circunflexo",375:"Letra y latina minÃºscula con acento circunflexo",sbquo:"ComiÃ±a simple baixa, de apertura",8219:"ComiÃ±a simple alta, de peche",bdquo:"ComiÃ±as dobres baixas, de apertura",hellip:"Elipse, puntos suspensivos",trade:"Signo de marca rexistrada",9658:"Apuntador negro apuntando Ã¡ dereita",bull:"ViÃ±eta",rarr:"Frecha Ã¡ dereita",rArr:"Frecha dobre Ã¡ dereita",hArr:"Frecha dobre da esquerda Ã¡ dereita",diams:"Diamante negro",asymp:"Case igual a"});