ï»¿/*
 Copyright (c) 2003-2019, CKSource - Frederico Knabben. All rights reserved.
 For licensing, see LICENSE.md or https://ckeditor.com/legal/ckeditor-oss-license
*/
CKEDITOR.plugins.setLang("specialchar","he",{euro:"×××¨×",lsquo:"×¡××× ×¦×××× ×××× ×©××××",rsquo:"×¡××× ×¦×××× ×××× ××× ×",ldquo:"×¡××× ×¦×××× ××¤×× ×©××××",rdquo:"×¡××× ×¦×××× ××¤×× ××× ×",ndash:"×§× ××¤×¨×× ×§×¦×¨",mdash:"×§× ××¤×¨×× ××¨××",iexcl:"×¡××× ×§×¨××× ××¤××",cent:"×¡× ×",pound:"×¤××× ×",curren:"××××¢",yen:"××",brvbar:"×§× ×©×××¨",sect:"×¡××× ××§××¢",uml:"×©×ª× × ×§××××ª ×××¤×§×××ª (Diaeresis)",copy:"×¡××× ××××××ª ×××¦×¨×× (Copyright)",ordf:"×¡××× ×××¨××× ××× × ×§××",laquo:"×¡××× ×¦×××× ×××××ª ××¤××× ××©×××",not:"×¡××× ×©×××× ××ª×××",reg:"×¡××× ×¨×©××",
macr:"××§×¨×× (×××× ××¨×××)",deg:"××¢×××ª",sup2:"2 ×××ª×× ×¢×××",sup3:"3 ×××ª×× ×¢×××",acute:"×¡××× ××××© (Acute)",micro:"×××§×¨×",para:"×¡×××× ×¤×¡×§×",middot:"× ×§××× ×××¦×¢××ª",cedil:"×¡×××××",sup1:"1 ×××ª×× ×¢×××",ordm:"×¡××× ×××¨××× ××× ×××¨×",raquo:"×¡××× ×¦×××× ×××××ª ××¤××× ×××××",frac14:"×¨××¢ ××©××¨ ×¤×©××",frac12:"××¦× ××©××¨ ×¤×©××",frac34:"×©×××©× ×¨××¢×× ××©××¨ ×¤×©××",iquest:"×¡××× ×©××× ××¤××",Agrave:"×××ª ×××× ××ª A ×¢× ××¨×© (Grave)",Aacute:"Latin capital letter A with acute accent",Acirc:"Latin capital letter A with circumflex",Atilde:"Latin capital letter A with tilde",
Auml:"Latin capital letter A with diaeresis",Aring:"Latin capital letter A with ring above",AElig:"×××ª ×××× ××ª Ã ×××××",Ccedil:"Latin capital letter C with cedilla",Egrave:"×××ª ×××× ××ª E ×¢× ××¨×© (Grave)",Eacute:"Latin capital letter E with acute accent",Ecirc:"Latin capital letter E with circumflex",Euml:"Latin capital letter E with diaeresis",Igrave:"×××ª ×××× ××ª I ×¢× ××¨×© (Grave)",Iacute:"Latin capital letter I with acute accent",Icirc:"Latin capital letter I with circumflex",Iuml:"Latin capital letter I with diaeresis",
ETH:"×××ª ×××× ××ª Eth ×××××",Ntilde:"Latin capital letter N with tilde",Ograve:"×××ª ×××× ××ª O ×¢× ××¨×© (Grave)",Oacute:"Latin capital letter O with acute accent",Ocirc:"Latin capital letter O with circumflex",Otilde:"Latin capital letter O with tilde",Ouml:"Latin capital letter O with diaeresis",times:"×¡××× ××¤×",Oslash:"Latin capital letter O with stroke",Ugrave:"×××ª ×××× ××ª U ×¢× ××¨×© (Grave)",Uacute:"Latin capital letter U with acute accent",Ucirc:"Latin capital letter U with circumflex",Uuml:"Latin capital letter U with diaeresis",
Yacute:"Latin capital letter Y with acute accent",THORN:"×××ª ×××× ××ª Thorn ×××××",szlig:"×××ª ×××× ××ª s ××× ×§×× ×",agrave:"×××ª ×××× ××ª a ×¢× ××¨×© (Grave)",aacute:"Latin small letter a with acute accent",acirc:"Latin small letter a with circumflex",atilde:"Latin small letter a with tilde",auml:"Latin small letter a with diaeresis",aring:"Latin small letter a with ring above",aelig:"×××ª ×××× ××ª Ã¦ ×§×× ×",ccedil:"Latin small letter c with cedilla",egrave:"×××ª ×××× ××ª e ×¢× ××¨×© (Grave)",eacute:"Latin small letter e with acute accent",
ecirc:"Latin small letter e with circumflex",euml:"Latin small letter e with diaeresis",igrave:"×××ª ×××× ××ª i ×¢× ××¨×© (Grave)",iacute:"Latin small letter i with acute accent",icirc:"Latin small letter i with circumflex",iuml:"Latin small letter i with diaeresis",eth:"×××ª ×××× ××ª eth ×§×× ×",ntilde:"Latin small letter n with tilde",ograve:"×××ª ×××× ××ª o ×¢× ××¨×© (Grave)",oacute:"Latin small letter o with acute accent",ocirc:"Latin small letter o with circumflex",otilde:"Latin small letter o with tilde",ouml:"Latin small letter o with diaeresis",
divide:"×¡××× ××××§×",oslash:"Latin small letter o with stroke",ugrave:"×××ª ×××× ××ª u ×¢× ××¨×© (Grave)",uacute:"Latin small letter u with acute accent",ucirc:"Latin small letter u with circumflex",uuml:"Latin small letter u with diaeresis",yacute:"Latin small letter y with acute accent",thorn:"×××ª ×××× ××ª thorn ×§×× ×",yuml:"Latin small letter y with diaeresis",OElig:"Latin capital ligature OE",oelig:"Latin small ligature oe",372:"Latin capital letter W with circumflex",374:"Latin capital letter Y with circumflex",
373:"Latin small letter w with circumflex",375:"Latin small letter y with circumflex",sbquo:"×¡××× ×¦×××× × ××× ××××",8219:"×¡××× ×¦××××",bdquo:"×¡××× ×¦×××× × ××× ××¤××",hellip:"×©×××© × ×§××××ª",trade:"×¡××× ××¨××××××¨×§",9658:"×¡×× ×©×××¨ ××¦× ××××",bull:"×ª×××× (×¨×©×××)",rarr:"××¥ ×××××",rArr:"××¥ ××¤×× ×××××",hArr:"××¥ ××¤×× ××××× ××©×××",diams:"××××× ×××",asymp:"×××¢× ×©×××"});