ï»¿/*
 Copyright (c) 2003-2019, CKSource - Frederico Knabben. All rights reserved.
 For licensing, see LICENSE.md or https://ckeditor.com/legal/ckeditor-oss-license
*/
CKEDITOR.plugins.setLang("specialchar","hr",{euro:"Euro znak",lsquo:"Lijevi jednostruki navodnik",rsquo:"Desni jednostruki navodnik",ldquo:"Lijevi dvostruki navodnik",rdquo:"Desni dvostruki navodnik",ndash:"En crtica",mdash:"Em crtica",iexcl:"Naopaki uskliÄnik",cent:"Cent znak",pound:"Funta znak",curren:"Znak valute",yen:"Yen znak",brvbar:"Potrgana preÄka",sect:"Znak odjeljka",uml:"Prijeglasi",copy:"Copyright znak",ordf:"Å½enska redna oznaka",laquo:"Lijevi dvostruki uglati navodnik",not:"Not znak",
reg:"Registered znak",macr:"Crta iznad",deg:"Stupanj znak",sup2:"Eksponent 2",sup3:"Eksponent tri",acute:"Akcent",micro:"Mikro znak",para:"Znak paragrafa",middot:"Srednja toÄka",cedil:"Cedilla",sup1:"Eksponent 1",ordm:"MuÅ¡ka redna oznaka",raquo:"Desni dvostruku uglati navodnik",frac14:"Äetvrtina",frac12:"Polovina",frac34:"Tri Äetvrtine",iquest:"Naopaki upitnik",Agrave:"Veliko latinsko slovo A s akcentom",Aacute:"LatiniÄno veliko slovo A sa oÅ¡trim naglaskom",Acirc:"LatiniÄno veliko slovo A sa circumflex",
Atilde:"LatiniÄno veliko slovo A sa tildom",Auml:"LatiniÄno veliko slovo A sa diaeresis",Aring:"LatiniÄno veliko slovo A sa gornjim prstenom",AElig:"LatiniÄno veliko slovo Ã",Ccedil:"Veliko latiniÄno slovo C sa cedilla",Egrave:"Veliko latiniÄno slovo E sa akcentom",Eacute:"Veliko latiniÄno slovo E sa  akcentom",Ecirc:"Veliko latiniÄno slovo E sa circumflex",Euml:"Veliko latiniÄno slovo E sa diaresis",Igrave:"Veliko latiniÄno slovo I sa akcentom",Iacute:"Veliko latiniÄno slovo I sa akcentom",Icirc:"Veliko latiniÄno slovo I sa circumflex",
Iuml:"Veliko latiniÄno slovo I sa diaresis",ETH:"Veliko latiniÄno slovo Eth",Ntilde:"Veliko latiniÄno slovo N sa tildom",Ograve:"Veliko latiniÄno slovo O sa akcentom",Oacute:"Veliko latiniÄno slovo O sa akcentom",Ocirc:"Veliko latiniÄno slovo O sa circumflex",Otilde:"Veliko latiniÄno slovo O sa tildom",Ouml:"Veliko latiniÄno slovo O sa diaresis",times:"Znak mnoÅ¾enja",Oslash:"Veliko latiniÄno slovo O sa crtom",Ugrave:"Veliko latiniÄno slovo U sa akcentom",Uacute:"Veliko latiniÄno slovo U sa akcentom",
Ucirc:"Veliko latiniÄno slovo U sa circumflex",Uuml:"Veliko latiniÄno slovo U sa diaresis",Yacute:"Veliko latiniÄno slovo Y sa akcentom",THORN:"Veliko latiniÄno slovo Trn",szlig:"Malo latiniÄno slovo oÅ¡tro s",agrave:"Malo latiniÄno slovo a sa akcentom",aacute:"Malo latiniÄno slovo sa akcentom",acirc:"Malo latiniÄno slovo a sa circumflex",atilde:"Malo latiniÄno slovo a sa tildom",auml:"Malo latiniÄno slovo a sa diaresis",aring:"Malo latiniÄno slovo a sa gornjim prstenom",aelig:"Malo latiniÄno slovo Ã¦",
ccedil:"Malo latiniÄno slovo e sa cedilla",egrave:"Malo latiniÄno slovo e sa akcentom",eacute:"Malo latiniÄno slovo e sa akcentom",ecirc:"Malo latiniÄno slovo e sa circumflex",euml:"Malo latiniÄno slovo e sa diaresis",igrave:"Malo latiniÄno slovo i sa akcentom",iacute:"Malo latiniÄno slovo i sa akcentom",icirc:"Malo latiniÄno slovo i sa circumflex",iuml:"Malo latiniÄno slovo i sa diaresis",eth:"Malo latiniÄno slovo eth",ntilde:"Malo latiniÄno slovo n sa tildom",ograve:"Malo latiniÄno slovo o sa akcentom",
oacute:"Malo latiniÄno slovo o sa akcentom",ocirc:"Malo latiniÄno slovo o sa circumflex",otilde:"Malo latiniÄno slovo o sa tildom",ouml:"Malo latiniÄno slovo o sa diaresis",divide:"Znak dijeljenja",oslash:"Malo latiniÄno slovo o sa crtom",ugrave:"Malo latiniÄno slovo s akcentom",uacute:"Malo latiniÄno slovo u sa akcentom",ucirc:"Malo latiniÄno slovo sa circumflex",uuml:"Malo latiniÄno slovo u sa diaresis",yacute:"Malo latiniÄno slovo y s akcentom",thorn:"Malo latiniÄno slovo Trn",yuml:"Malo latiniÄno slovo y sa diaresis",
OElig:"Veliko latiniÄno slovo OE",oelig:"Malo latiniÄno slovoe OE",372:"Veliko latiniÄno slovo W sa circumflex",374:"Veliko latiniÄno slovo Y sa circumflex",373:"Malo latiniÄno slovo w sa circumflex",375:"Malo latiniÄno slovo y sa circumflex",sbquo:"Jednostruki donji navodnik",8219:"Jednostruki gornji navodnik",bdquo:"Dvostruki donji navodnik",hellip:"Tri toÄkice",trade:"TM znak",9658:"Crni desni pokazivaÄ",bull:"Bullet",rarr:"Desna strelica",rArr:"Desna dvostruka strelica",hArr:"Dvostruka strelica",
diams:"Crni dijamant",asymp:"PribliÅ¾no"});