ï»¿/*
 Copyright (c) 2003-2019, CKSource - Frederico Knabben. All rights reserved.
 For licensing, see LICENSE.md or https://ckeditor.com/legal/ckeditor-oss-license
*/
CKEDITOR.plugins.setLang("specialchar","hu",{euro:"EurÃ³ jel",lsquo:"Bal szimpla idÃ©zÅjel",rsquo:"Jobb szimpla idÃ©zÅjel",ldquo:"Bal dupla idÃ©zÅjel",rdquo:"Jobb dupla idÃ©zÅjel",ndash:"RÃ¶vid gondolatjel",mdash:"HosszÃº gondolatjel",iexcl:"FordÃ­tott felkiÃ¡ltÃ³jel",cent:"Cent jel",pound:"Font jel",curren:"Valuta jel",yen:"Yen jel",brvbar:"HosszÃº kettÅspont",sect:"Paragrafus jel",uml:"KettÅs hangzÃ³ jel",copy:"SzerzÅi jog jel",ordf:"NÅi sorrend mutatÃ³ja",laquo:"Balra mutatÃ³ duplanyÃ­l",not:"FeltÃ©teles kÃ¶tÅjel",
reg:"Bejegyzett vÃ©djegy jele",macr:"HosszÃºsÃ¡gi jel",deg:"Fok jel",sup2:"NÃ©gyzeten jel",sup3:"KÃ¶bÃ¶n jel",acute:"Ãles Ã©kezet",micro:"Mikro-jel",para:"BekezdÃ©s jel",middot:"KÃ¶zÃ©p pont",cedil:"CÃ©dille",sup1:"ElsÅn jel",ordm:"FÃ©rfi sorrend mutatÃ³ja",raquo:"Jobbra mutatÃ³ duplanyÃ­l",frac14:"Egy negyed jel",frac12:"Egy ketted jel",frac34:"HÃ¡rom negyed jel",iquest:"FordÃ­tott kÃ©rdÅjel",Agrave:"Latin nagy A fordÃ­tott Ã©kezettel",Aacute:"Latin nagy A normÃ¡l Ã©kezettel",Acirc:"Latin nagy A hajtott Ã©kezettel",Atilde:"Latin nagy A hullÃ¡mjellel",
Auml:"Latin nagy A kettÅspont Ã©kezettel",Aring:"Latin nagy A gyÅ±rÅ± Ã©kezettel",AElig:"Latin nagy Ã betÅ±",Ccedil:"Latin nagy C cedillÃ¡val",Egrave:"Latin nagy E fordÃ­tott Ã©kezettel",Eacute:"Latin nagy E normÃ¡l Ã©kezettel",Ecirc:"Latin nagy E hajtott Ã©kezettel",Euml:"Latin nagy E dupla kettÅspont Ã©kezettel",Igrave:"Latin nagy I fordÃ­tott Ã©kezettel",Iacute:"Latin nagy I normÃ¡l Ã©kezettel",Icirc:"Latin nagy I hajtott Ã©kezettel",Iuml:"Latin nagy I kettÅspont Ã©kezettel",ETH:"Latin nagy Eth betÅ±",Ntilde:"Latin nagy N hullÃ¡mjellel",
Ograve:"Latin nagy O fordÃ­tott Ã©kezettel",Oacute:"Latin nagy O normÃ¡l Ã©kezettel",Ocirc:"Latin nagy O hajtott Ã©kezettel",Otilde:"Latin nagy O hullÃ¡mjellel",Ouml:"Latin nagy O kettÅspont Ã©kezettel",times:"SzorzÃ¡s jel",Oslash:"Latin O betÅ± Ã¡thÃºzÃ¡ssal",Ugrave:"Latin nagy U fordÃ­tott Ã©kezettel",Uacute:"Latin nagy U normÃ¡l Ã©kezettel",Ucirc:"Latin nagy U hajtott Ã©kezettel",Uuml:"Latin nagy U kettÅspont Ã©kezettel",Yacute:"Latin nagy Y normÃ¡l Ã©kezettel",THORN:"Latin nagy Thorn betÅ±",szlig:"Latin kis s betÅ±",
agrave:"Latin kis a fordÃ­tott Ã©kezettel",aacute:"Latin kis a normÃ¡l Ã©kezettel",acirc:"Latin kis a hajtott Ã©kezettel",atilde:"Latin kis a hullÃ¡mjellel",auml:"Latin kis a kettÅspont Ã©kezettel",aring:"Latin kis a gyÅ±rÅ± Ã©kezettel",aelig:"Latin kis Ã¦ betÅ±",ccedil:"Latin kis c cedillÃ¡val",egrave:"Latin kis e fordÃ­tott Ã©kezettel",eacute:"Latin kis e normÃ¡l Ã©kezettel",ecirc:"Latin kis e hajtott Ã©kezettel",euml:"Latin kis e dupla kettÅspont Ã©kezettel",igrave:"Latin kis i fordÃ­tott Ã©kezettel",iacute:"Latin kis i normÃ¡l Ã©kezettel",
icirc:"Latin kis i hajtott Ã©kezettel",iuml:"Latin kis i kettÅspont Ã©kezettel",eth:"Latin kis eth betÅ±",ntilde:"Latin kis n hullÃ¡mjellel",ograve:"Latin kis o fordÃ­tott Ã©kezettel",oacute:"Latin kis o normÃ¡l Ã©kezettel",ocirc:"Latin kis o hajtott Ã©kezettel",otilde:"Latin kis o hullÃ¡mjellel",ouml:"Latin kis o kettÅspont Ã©kezettel",divide:"OsztÃ¡sjel",oslash:"Latin kis o betÅ± Ã¡thÃºzÃ¡ssal",ugrave:"Latin kis u fordÃ­tott Ã©kezettel",uacute:"Latin kis u normÃ¡l Ã©kezettel",ucirc:"Latin kis u hajtott Ã©kezettel",
uuml:"Latin kis u kettÅspont Ã©kezettel",yacute:"Latin kis y normÃ¡l Ã©kezettel",thorn:"Latin kis thorn jel",yuml:"Latin kis y kettÅspont Ã©kezettel",OElig:"Latin nagy OE-jel",oelig:"Latin kis oe-jel",372:"Latin nagy W hajtott Ã©kezettel",374:"Latin nagy Y hajtott Ã©kezettel",373:"Latin kis w hajtott Ã©kezettel",375:"Latin kis y hajtott Ã©kezettel",sbquo:"NyitÃ³ nyomdai szimpla idÃ©zÅjel",8219:"ZÃ¡rÃ³ nyomdai zÃ¡rÃ³ idÃ©zÅjel",bdquo:"NyitÃ³ nyomdai dupla idÃ©zÅjel",hellip:"HÃ¡rom pont",trade:"Kereskedelmi vÃ©djegy jele",
9658:"Jobbra mutatÃ³ fekete mutatÃ³",bull:"GolyÃ³",rarr:"Jobbra mutatÃ³ nyÃ­l",rArr:"Jobbra mutatÃ³ duplanyÃ­l",hArr:"Bal-jobb duplanyÃ­l",diams:"Fekete gyÃ©mÃ¡nt jel",asymp:"Majdnem egyenlÅ jel"});