ï»¿/*
 Copyright (c) 2003-2019, CKSource - Frederico Knabben. All rights reserved.
 For licensing, see LICENSE.md or https://ckeditor.com/legal/ckeditor-oss-license
*/
CKEDITOR.plugins.setLang("specialchar","oc",{euro:"SimbÃ²l Ã¨uro",lsquo:"Vergueta simpla dobrenta",rsquo:"Vergueta simpla tampanta",ldquo:"Vergueta dobla dobrenta",rdquo:"Vergueta dobla tampanta",ndash:"Jonhent semi-quadratin",mdash:"Jonhent quadratin",iexcl:"Punt d'exclamacion inversat",cent:"SimbÃ²l cent",pound:"SimbÃ²l Liura sterling",curren:"SimbÃ²l monetari",yen:"SimbÃ²l iÃ¨n",brvbar:"Barra verticala separada",sect:"Signe de seccion",uml:"TrÃ¨ma",copy:"SimbÃ²l Copyright",ordf:"Indicador ordinal femenin",
laquo:"Vergueta francesa dobrenta",not:"Croquet de negacion",reg:"SimbÃ²l de marca depausada",macr:"Macron",deg:"SimbÃ²l gra",sup2:"Exponent 2",sup3:"Exponent 3",acute:"Accent agut",micro:"SimbÃ²l micro",para:"SimbÃ²l pÃ¨ de mÃ²sca",middot:"Punt median",cedil:"Cedilha",sup1:"Exponent 1",ordm:"Indicador ordenal masculin",raquo:"Vergueta francesa tampanta",frac14:"Fraccion un quart",frac12:"Fraccion un miÃ¨g",frac34:"Fraccion tres quarts",iquest:"Punt d'interrogacion inversat",Agrave:"A accent grÃ¨u majuscula",
Aacute:"A accent agut majuscula",Acirc:"A accent circonflÃ¨xe majuscula",Atilde:"A caron majuscula",Auml:"A trÃ¨ma majuscula",Aring:"A redond majuscula",AElig:"Ligatura Ã majuscula",Ccedil:"C cÃ©dille majuscula",Egrave:"E accent grÃ¨u majuscula",Eacute:"E accent agut majuscula",Ecirc:"E accent circonflÃ¨xe majuscula",Euml:"E trÃ¨ma majuscula",Igrave:"I accent grÃ¨u majuscula",Iacute:"I accent agut majuscula",Icirc:"I accent circonflÃ¨xe majuscula",Iuml:"I trÃ¨ma majuscula",ETH:"Letra majuscula islandaise ED",
Ntilde:"N caron majuscula",Ograve:"O accent grÃ¨u majuscula",Oacute:"O accent agut majuscula",Ocirc:"O accent circonflÃ¨xe majuscula",Otilde:"O caron majuscula",Ouml:"O trÃ¨ma majuscula",times:"SimbÃ²l de multiplicacion",Oslash:"O raiat majuscula",Ugrave:"U accent grÃ¨u majuscula",Uacute:"U accent agut majuscula",Ucirc:"U accent circonflÃ¨xe majuscula",Uuml:"U trÃ¨ma majuscula",Yacute:"Y accent agut majuscula",THORN:"Letra islandesa thorn majuscula",szlig:"Letra minuscula alemanda S dur",agrave:"A accent grÃ¨u minuscula",
aacute:"A accent agut minuscula",acirc:"A accent circonflÃ¨xe minuscula",atilde:"A tilda minuscula",auml:"A trÃ¨ma minuscula",aring:"A redond minuscula",aelig:"Ligatura Ã minuscula",ccedil:"C cÃ©dille minuscula",egrave:"E accent grÃ¨u minuscula",eacute:"E accent agut minuscula",ecirc:"E accent circonflÃ¨xe minuscula",euml:"E trÃ¨ma minuscula",igrave:"I accent grÃ¨u minuscula",iacute:"I accent agut minuscula",icirc:"I accent circonflÃ¨xe minuscula",iuml:"i minuscula trÃ¨ma",eth:"Letra minuscula islandaise ED",
ntilde:"N caron minuscula",ograve:"O minuscula accent grÃ¨u",oacute:"O accent agut minuscula",ocirc:"O accent circonflÃ¨xe minuscula",otilde:"O tilda minuscula",ouml:"O trÃ¨ma minuscula",divide:"SimbÃ²l de division",oslash:"O raiat minuscula",ugrave:"U accent grÃ¨u minuscula",uacute:"U accent agut minuscula",ucirc:"U accent circonflÃ¨xe minuscula",uuml:"U trÃ¨ma minuscula",yacute:"Y accent agut minuscula",thorn:"Letra islandaise thorn minuscula",yuml:"Y trÃ¨ma minuscula",OElig:"Ligatura Å majuscula",oelig:"Ligatura Å minuscula",
372:"W accent circonflÃ¨xe majuscula",374:"Y accent circonflÃ¨xe majuscula",373:"W accent circonflÃ¨xe minuscula",375:"Y accent circonflÃ¨xe minuscula",sbquo:"Vergueta simpla tampanta inferior",8219:"Vergueta-virgula superior culbutÃ©",bdquo:"Vergueta-virgula double inferior",hellip:"Punts de suspension",trade:"SimbÃ²l de marca comerciala",9658:"Sageta negra puntant cap a dreita",bull:"GrÃ²s punt median",rarr:"Sageta cap a dreita",rArr:"Sageta dobla cap a dreita",hArr:"Sageta dobla cap a esquÃ¨rra",diams:"Lausange negre",
asymp:"Environ egal"});