ï»¿/*
 Copyright (c) 2003-2019, CKSource - Frederico Knabben. All rights reserved.
 For licensing, see LICENSE.md or https://ckeditor.com/legal/ckeditor-oss-license
*/
CKEDITOR.plugins.setLang("specialchar","pl",{euro:"Znak euro",lsquo:"CudzysÅÃ³w pojedynczy otwierajÄcy",rsquo:"CudzysÅÃ³w pojedynczy zamykajÄcy",ldquo:"CudzysÅÃ³w apostrofowy otwierajÄcy",rdquo:"CudzysÅÃ³w apostrofowy zamykajÄcy",ndash:"PÃ³Åpauza",mdash:"Pauza",iexcl:"OdwrÃ³cony wykrzyknik",cent:"Znak centa",pound:"Znak funta",curren:"Znak waluty",yen:"Znak jena",brvbar:"Przerwana pionowa kreska",sect:"Paragraf",uml:"Diereza",copy:"Znak praw autorskich",ordf:"WskaÅºnik rodzaju Å¼eÅskiego liczebnika porzÄdkowego",
laquo:"Lewy cudzysÅÃ³w ostrokÄtny",not:"Znak negacji",reg:"ZastrzeÅ¼ony znak towarowy",macr:"Makron",deg:"Znak stopnia",sup2:"Druga potÄga",sup3:"Trzecia potÄga",acute:"Akcent ostry",micro:"Znak mikro",para:"Znak akapitu",middot:"Kropka Årodkowa",cedil:"Cedylla",sup1:"Pierwsza potÄga",ordm:"WskaÅºnik rodzaju mÄskiego liczebnika porzÄdkowego",raquo:"Prawy cudzysÅÃ³w ostrokÄtny",frac14:"UÅamek zwykÅy jedna czwarta",frac12:"UÅamek zwykÅy jedna druga",frac34:"UÅamek zwykÅy trzy czwarte",iquest:"OdwrÃ³cony znak zapytania",
Agrave:"Wielka litera A z akcentem ciÄÅ¼kim",Aacute:"Wielka litera A z akcentem ostrym",Acirc:"Wielka litera A z akcentem przeciÄgÅym",Atilde:"Wielka litera A z tyldÄ",Auml:"Wielka litera A z dierezÄ",Aring:"Wielka litera A z kÃ³Åkiem",AElig:"Wielka ligatura Ã",Ccedil:"Wielka litera C z cedyllÄ",Egrave:"Wielka litera E z akcentem ciÄÅ¼kim",Eacute:"Wielka litera E z akcentem ostrym",Ecirc:"Wielka litera E z akcentem przeciÄgÅym",Euml:"Wielka litera E z dierezÄ",Igrave:"Wielka litera I z akcentem ciÄÅ¼kim",
Iacute:"Wielka litera I z akcentem ostrym",Icirc:"Wielka litera I z akcentem przeciÄgÅym",Iuml:"Wielka litera I z dierezÄ",ETH:"Wielka litera Eth",Ntilde:"Wielka litera N z tyldÄ",Ograve:"Wielka litera O z akcentem ciÄÅ¼kim",Oacute:"Wielka litera O z akcentem ostrym",Ocirc:"Wielka litera O z akcentem przeciÄgÅym",Otilde:"Wielka litera O z tyldÄ",Ouml:"Wielka litera O z dierezÄ",times:"Znak mnoÅ¼enia wektorowego",Oslash:"Wielka litera O z przekreÅleniem",Ugrave:"Wielka litera U z akcentem ciÄÅ¼kim",Uacute:"Wielka litera U z akcentem ostrym",
Ucirc:"Wielka litera U z akcentem przeciÄgÅym",Uuml:"Wielka litera U z dierezÄ",Yacute:"Wielka litera Y z akcentem ostrym",THORN:"Wielka litera Thorn",szlig:"MaÅa litera ostre s (eszet)",agrave:"MaÅa litera a z akcentem ciÄÅ¼kim",aacute:"MaÅa litera a z akcentem ostrym",acirc:"MaÅa litera a z akcentem przeciÄgÅym",atilde:"MaÅa litera a z tyldÄ",auml:"MaÅa litera a z dierezÄ",aring:"MaÅa litera a z kÃ³Åkiem",aelig:"MaÅa ligatura Ã¦",ccedil:"MaÅa litera c z cedyllÄ",egrave:"MaÅa litera e z akcentem ciÄÅ¼kim",
eacute:"MaÅa litera e z akcentem ostrym",ecirc:"MaÅa litera e z akcentem przeciÄgÅym",euml:"MaÅa litera e z dierezÄ",igrave:"MaÅa litera i z akcentem ciÄÅ¼kim",iacute:"MaÅa litera i z akcentem ostrym",icirc:"MaÅa litera i z akcentem przeciÄgÅym",iuml:"MaÅa litera i z dierezÄ",eth:"MaÅa litera eth",ntilde:"MaÅa litera n z tyldÄ",ograve:"MaÅa litera o z akcentem ciÄÅ¼kim",oacute:"MaÅa litera o z akcentem ostrym",ocirc:"MaÅa litera o z akcentem przeciÄgÅym",otilde:"MaÅa litera o z tyldÄ",ouml:"MaÅa litera o z dierezÄ",
divide:"Anglosaski znak dzielenia",oslash:"MaÅa litera o z przekreÅleniem",ugrave:"MaÅa litera u z akcentem ciÄÅ¼kim",uacute:"MaÅa litera u z akcentem ostrym",ucirc:"MaÅa litera u z akcentem przeciÄgÅym",uuml:"MaÅa litera u z dierezÄ",yacute:"MaÅa litera y z akcentem ostrym",thorn:"MaÅa litera thorn",yuml:"MaÅa litera y z dierezÄ",OElig:"Wielka ligatura OE",oelig:"MaÅa ligatura oe",372:"Wielka litera W z akcentem przeciÄgÅym",374:"Wielka litera Y z akcentem przeciÄgÅym",373:"MaÅa litera w z akcentem przeciÄgÅym",
375:"MaÅa litera y z akcentem przeciÄgÅym",sbquo:"Pojedynczy apostrof dolny",8219:"Pojedynczy apostrof gÃ³rny",bdquo:"PodwÃ³jny apostrof dolny",hellip:"Wielokropek",trade:"Znak towarowy",9658:"Czarny wskaÅºnik wskazujÄcy w prawo",bull:"Punktor",rarr:"StrzaÅka w prawo",rArr:"PodwÃ³jna strzaÅka w prawo",hArr:"PodwÃ³jna strzaÅka obustronna",diams:"Czarny znak karo",asymp:"Znak prawie rÃ³wne"});