ï»¿/*
 Copyright (c) 2003-2019, CKSource - Frederico Knabben. All rights reserved.
 For licensing, see LICENSE.md or https://ckeditor.com/legal/ckeditor-oss-license
*/
CKEDITOR.plugins.setLang("specialchar","pt",{euro:"SÃ­mbolo de Euro",lsquo:"Aspa esquerda simples",rsquo:"Aspa direita simples",ldquo:"Aspa esquerda dupla",rdquo:"Aspa direita dupla",ndash:"TravessÃ£o simples",mdash:"TravessÃ£o longo",iexcl:"Ponto de exclamaÃ§Ã£o invertido",cent:"SÃ­mbolo de cÃªntimo",pound:"SÃ­mbolo de Libra",curren:"SÃ­mbolo de Moeda",yen:"SÃ­mbolo de Iene",brvbar:"Barra quebrada",sect:"SÃ­mbolo de secÃ§Ã£o",uml:"Trema",copy:"SÃ­mbolo de direitos de autor",ordf:"Indicador ordinal feminino",laquo:"Aspa esquerda Ã¢ngulo duplo",
not:"NÃ£o sÃ­mbolo",reg:"SÃ­mbolo de registado",macr:"MÃ¡cron",deg:"SÃ­mbolo de graus",sup2:"Expoente 2",sup3:"Expoente 3",acute:"Acento agudo",micro:"SÃ­mbolo de micro",para:"SÃ­mbolo de parÃ¡grafo",middot:"Ponto do meio",cedil:"Cedilha",sup1:"Expoente 1",ordm:"Indicador ordinal masculino",raquo:"Aspas Ã¢ngulo duplo para a direita",frac14:"FraÃ§Ã£o vulgar 1/4",frac12:"FraÃ§Ã£o vulgar 1/2",frac34:"FraÃ§Ã£o vulgar 3/4",iquest:"Ponto de interrogaÃ§Ã£o invertido",Agrave:"Letra maiÃºscula latina A com acento grave",Aacute:"Letra maiÃºscula latina A com acento agudo",
Acirc:"Letra maiÃºscula latina A com circunflexo",Atilde:"Letra maiÃºscula latina A com til",Auml:"Letra maiÃºscula latina A com trema",Aring:"Letra maiÃºscula latina A com sinal diacrÃ­tico",AElig:"Letra maiÃºscula latina Ã",Ccedil:"Letra maiÃºscula latina C com cedilha",Egrave:"Letra maiÃºscula latina E com acento grave",Eacute:"Letra maiÃºscula latina E com acento agudo",Ecirc:"Letra maiÃºscula latina E com circunflexo",Euml:"Letra maiÃºscula latina E com trema",Igrave:"Letra maiÃºscula latina I com acento grave",
Iacute:"Letra maiÃºscula latina I com acento agudo",Icirc:"Letra maiÃºscula latina I com cincunflexo",Iuml:"Letra maiÃºscula latina I com trema",ETH:"Letra maiÃºscula latina Eth (ÃÃ°)",Ntilde:"Letra maiÃºscula latina N com til",Ograve:"Letra maiÃºscula latina O com acento grave",Oacute:"Letra maiÃºscula latina O com acento agudo",Ocirc:"Letra maiÃºscula latina I com circunflexo",Otilde:"Letra maiÃºscula latina O com til",Ouml:"Letra maiÃºscula latina O com trema",times:"SÃ­mbolo de multiplicaÃ§Ã£o",Oslash:"Letra maiÃºscula O com barra",
Ugrave:"Letra maiÃºscula latina U com acento grave",Uacute:"Letra maiÃºscula latina U com acento agudo",Ucirc:"Letra maiÃºscula latina U com circunflexo",Uuml:"Letra maiÃºscula latina E com trema",Yacute:"Letra maiÃºscula latina Y com acento agudo",THORN:"Letra maiÃºscula latina RÃºnico",szlig:"Letra minÃºscula latina s forte",agrave:"Letra minÃºscula latina a com acento grave",aacute:"Letra minÃºscula latina a com acento agudo",acirc:"Letra minÃºscula latina a com circunflexo",atilde:"Letra minÃºscula latina a com til",
auml:"Letra minÃºscula latina a com trema",aring:"Letra minÃºscula latina a com sinal diacrÃ­tico",aelig:"Letra minÃºscula latina Ã¦",ccedil:"Letra minÃºscula latina c com cedilha",egrave:"Letra minÃºscula latina e com acento grave",eacute:"Letra minÃºscula latina e com acento agudo",ecirc:"Letra minÃºscula latina e com circunflexo",euml:"Letra minÃºscula latina e com trema",igrave:"Letra minÃºscula latina i com acento grave",iacute:"Letra minÃºscula latina i com acento agudo",icirc:"Letra minÃºscula latina i com circunflexo",
iuml:"Letra pequena latina i com trema",eth:"Letra minÃºscula latina eth",ntilde:"Letra minÃºscula latina n com til",ograve:"Letra minÃºscula latina o com acento grave",oacute:"Letra minÃºscula latina o com acento agudo",ocirc:"Letra minÃºscula latina o com circunflexo",otilde:"Letra minÃºscula latina o com til",ouml:"Letra minÃºscula latina o com trema",divide:"SÃ­mbolo de divisÃ£o",oslash:"Letra minÃºscula latina o com barra",ugrave:"Letra minÃºscula latina u com acento grave",uacute:"Letra minÃºscula latina u com acento agudo",
ucirc:"Letra minÃºscula latina u com circunflexo",uuml:"Letra minÃºscula latina u com trema",yacute:"Letra minÃºscula latina y com acento agudo",thorn:"Letra minÃºscula latina RÃºnico",yuml:"Letra minÃºscula latina y com trema",OElig:"Ligadura maiÃºscula latina OE",oelig:"Ligadura minÃºscula latina oe",372:"Letra maiÃºscula latina W com circunflexo",374:"Letra maiÃºscula latina Y com circunflexo",373:"Letra minÃºscula latina w com circunflexo",375:"Letra minÃºscula latina y com circunflexo",sbquo:"Aspa Simples inferior-9",
8219:"Aspa simples superior invertida-9",bdquo:"Aspa duplas inferior-9",hellip:"Elipse horizontal ",trade:"SÃ­mbolo de marca registada",9658:"Ponteiro preto direito",bull:"Marca",rarr:"Seta para a direita",rArr:"Seta dupla para a direita",hArr:"Seta dupla direita esquerda",diams:"Naipe diamante preto",asymp:"Quase igual a "});