ï»¿/*
 Copyright (c) 2003-2019, CKSource - Frederico Knabben. All rights reserved.
 For licensing, see LICENSE.md or https://ckeditor.com/legal/ckeditor-oss-license
*/
CKEDITOR.plugins.setLang("specialchar","sq",{euro:"Shenja e Euros",lsquo:"ThonjÃ«za majtas me njÃ« vi",rsquo:"ThonjÃ«za djathtas me njÃ« vi",ldquo:"ThonjÃ«za majtas",rdquo:"ThonjÃ«za djathtas",ndash:"En viza lidhÃ«se",mdash:"Em viza lidhÃ«se",iexcl:"PikÃ«Ã§uditÃ«se e pÃ«rmbysur",cent:"Shenja e Centit",pound:"Shejna e Funtit",curren:"Shenja e valutÃ«s",yen:"Shenja e Jenit",brvbar:"Viza e kÃ«putur",sect:"Shenja e pjesÃ«s",uml:"Diaeresis",copy:"Shenja e tÃ« drejtave tÃ« kopjimit",ordf:"Tregues rendor femror",laquo:"ThonjÃ«z me dy kÃ«nde e kthyer majtas",
not:"Nuk ka shenjÃ«",reg:"Shenja e tÃ« regjistruarit",macr:"Macron",deg:"Shenja e shkallÃ«s",sup2:"Super-skripta dy",sup3:"Super-skripta tre",acute:"Theks i mprehtÃ«",micro:"Shjenja e Mikros",para:"Shenja Pilkrou",middot:"Pika e Mesme",cedil:"Hark nÃ«n shkronja",sup1:"Super-skripta njÃ«",ordm:"Tregues rendor mashkullor",raquo:"ThonjÃ«z me dy kÃ«nde e kthyer djathtas",frac14:"Thyesa njÃ« tÃ« katrat",frac12:"Thyesa njÃ« tÃ« dytat",frac34:"Thyesa tre tÃ« katrat",iquest:"PikÃ«pyetje e pÃ«rmbysur",Agrave:"Shkronja e madhe latine A me theks tÃ« rÃ«ndÃ«",
Aacute:"Shkronja e madhe latine A me theks akute",Acirc:"Shkronja e madhe latine A me theks lakor",Atilde:"Shkronja e madhe latine A me tildÃ«",Auml:"Shkronja e madhe latine A me dy pika",Aring:"Shkronja e madhe latine A me unazÃ« mbi",AElig:"Shkronja e madhe latine Ã",Ccedil:"Shkronja e madhe latine C me hark poshtÃ«",Egrave:"Shkronja e madhe latine E me theks tÃ« rÃ«ndÃ«",Eacute:"Shkronja e madhe latine E me theks akute",Ecirc:"Shkronja e madhe latine E me theks lakor",Euml:"Shkronja e madhe latine E me dy pika",
Igrave:"Shkronja e madhe latine I me theks tÃ« rÃ«ndÃ«",Iacute:"Shkronja e madhe latine I me theks akute",Icirc:"Shkronja e madhe latine I me theks lakor",Iuml:"Shkronja e madhe latine I me dy pika",ETH:"Shkronja e madhe latine Eth",Ntilde:"Shkronja e madhe latine N me tildÃ«",Ograve:"Shkronja e madhe latine O me theks tÃ« rÃ«ndÃ«",Oacute:"Shkronja e madhe latine O me theks akute",Ocirc:"Shkronja e madhe latine O me theks lakor",Otilde:"Shkronja e madhe latine O me tildÃ«",Ouml:"Shkronja e madhe latine O me dy pika",
times:"Shenja e shumÃ«zimit",Oslash:"Shkronja e madhe latine O me vizÃ« nÃ« mes",Ugrave:"Shkronja e madhe latine U me theks tÃ« rÃ«ndÃ«",Uacute:"Shkronja e madhe latine U me theks akute",Ucirc:"Shkronja e madhe latine U me theks lakor",Uuml:"Shkronja e madhe latine U me dy pika",Yacute:"Shkronja e madhe latine Y me theks akute",THORN:"Shkronja e madhe latine Thorn",szlig:"Shkronja e vogÃ« latine s e mprehtÃ«",agrave:"Shkronja e vogÃ« latine a me theks tÃ« rÃ«ndÃ«",aacute:"Shkronja e vogÃ« latine a me theks tÃ« mprehtÃ«",
acirc:"Shkronja e vogÃ«l latine a me theks lakor",atilde:"Shkronja e vogÃ«l latine a me tildÃ«",auml:"Shkronja e vogÃ«l latine a me dy pika",aring:"Shkronja e vogÃ« latine a me unazÃ« mbi",aelig:"Shkronja e vogÃ« latine Ã¦",ccedil:"Shkronja e vogÃ«l latine c me hark poshtÃ«",egrave:"Shkronja e vogÃ« latine e me theks tÃ« rÃ«ndÃ«",eacute:"Shkronja e vogÃ« latine e me theks tÃ« mprehtÃ«",ecirc:"Shkronja e vogÃ«l latine e me theks lakor",euml:"Shkronja e vogÃ«l latine e me dy pika",igrave:"Shkronja e vogÃ« latine i me theks tÃ« rÃ«ndÃ«",
iacute:"Shkronja e vogÃ« latine i me theks tÃ« mprehtÃ«",icirc:"Shkronja e vogÃ«l latine i me theks lakor",iuml:"Shkronja e vogÃ«l latine i me dy pika",eth:"Shkronja e vogÃ« latine eth",ntilde:"Shkronja e vogÃ«l latine n me tildÃ«",ograve:"Shkronja e vogÃ« latine o me theks tÃ« rÃ«ndÃ«",oacute:"Shkronja e vogÃ« latine o me theks tÃ« mprehtÃ«",ocirc:"Shkronja e vogÃ«l latine o me theks lakor",otilde:"Shkronja e vogÃ«l latine o me tildÃ«",ouml:"Shkronja e vogÃ«l latine o me dy pika",divide:"Shenja ndarÃ«se",oslash:"Shkronja e vogÃ«l latine o me vizÃ« nÃ« mes",
ugrave:"Shkronja e vogÃ« latine u me theks tÃ« rÃ«ndÃ«",uacute:"Shkronja e vogÃ« latine u me theks tÃ« mprehtÃ«",ucirc:"Shkronja e vogÃ«l latine u me theks lakor",uuml:"Shkronja e vogÃ«l latine u me dy pika",yacute:"Shkronja e vogÃ« latine y me theks tÃ« mprehtÃ«",thorn:"Shkronja e vogÃ«l latine thorn",yuml:"Shkronja e vogÃ«l latine y me dy pika",OElig:"Shkronja e madhe e bashkuar latine OE",oelig:"Shkronja e vogÃ«l e bashkuar latine oe",372:"Shkronja e madhe latine W me theks lakor",374:"Shkronja e madhe latine Y me theks lakor",
373:"Shkronja e vogÃ«l latine w me theks lakor",375:"Shkronja e vogÃ«l latine y me theks lakor",sbquo:"ThonjÃ«z-9 e vetme poshtÃ«",8219:"ThonjÃ«z-9 lartÃ« e vetme e kthyer nÃ« tÃ« kundÃ«rtÃ«n",bdquo:"ThonjÃ«za-9 poshtÃ«",hellip:"Tri pika horizontale",trade:"Shenja e Simbolit TregtarÃ«",9658:"ShenjÃ« tregues kthyer djathtas-prapa",bull:"Pulla",rarr:"Shigjeta djathtas",rArr:"Shenja tÃ« dyfishta djathtas",hArr:"Shigjeta e dyfishÃ« majtas-djathtas",diams:"Karo me ngjyrÃ« tÃ« zezÃ«",asymp:"Gati e barabar me"});