ï»¿/*
 Copyright (c) 2003-2019, CKSource - Frederico Knabben. All rights reserved.
 For licensing, see LICENSE.md or https://ckeditor.com/legal/ckeditor-oss-license
*/
CKEDITOR.plugins.setLang("specialchar","tr",{euro:"Euro iÅareti",lsquo:"Sol tek tÄ±rnak iÅareti",rsquo:"SaÄ tek tÄ±rnak iÅareti",ldquo:"Sol Ã§ift tÄ±rnak iÅareti",rdquo:"SaÄ Ã§ift tÄ±rnak iÅareti",ndash:"En tire",mdash:"Em tire",iexcl:"Ters Ã¼nlem iÅareti",cent:"Cent iÅareti",pound:"Pound iÅareti",curren:"Para birimi iÅareti",yen:"Yen iÅareti",brvbar:"KÄ±rÄ±k bar",sect:"BÃ¶lÃ¼m iÅareti",uml:"Ä°ki sesli harfin ayrÄ±lmasÄ±",copy:"Telif hakkÄ± iÅareti",ordf:"DiÅil sÄ±ralÄ± gÃ¶sterge",laquo:"Sol-iÅaret Ã§ift aÃ§Ä± tÄ±rnak iÅareti",
not:"Not iÅareti",reg:"KayÄ±tlÄ± iÅareti",macr:"Makron",deg:"Derece iÅareti",sup2:"Ä°kili Ã¼stsimge",sup3:"ÃÃ§lÃ¼ Ã¼stsimge",acute:"Aksan iÅareti",micro:"Mikro iÅareti",para:"Pilcrow iÅareti",middot:"Orta nokta",cedil:"Kedilla",sup1:"Ãstsimge",ordm:"Eril sÄ±ralÄ± gÃ¶sterge",raquo:"SaÄ iÅaret Ã§ift aÃ§Ä± tÄ±rnak iÅareti",frac14:"BayaÄÄ± kesrin dÃ¶rtte biri",frac12:"BayaÄÄ± kesrin bir yarÄ±m",frac34:"BayaÄÄ± kesrin dÃ¶rtte Ã¼Ã§",iquest:"Ters soru iÅareti",Agrave:"AksanlÄ± latin harfi",Aacute:"AÅÄ±rÄ± aksanÄ±yla Latin harfi",
Acirc:"ÃarpÄ±k Latin harfi",Atilde:"Tilde latin harfi",Auml:"Sesli harf ayrÄ±lÄ±mlÄ±Ä± latin harfi",Aring:"HalkalÄ± latin bÃ¼yÃ¼k A harfi",AElig:"Latin bÃ¼yÃ¼k Ã harfi",Ccedil:"Latin bÃ¼yÃ¼k C harfi ile kedilla",Egrave:"AksanlÄ± latin bÃ¼yÃ¼k E harfi",Eacute:"AÅÄ±rÄ± vurgulu latin bÃ¼yÃ¼k E harfi",Ecirc:"ÃarpÄ±k latin bÃ¼yÃ¼k E harfi",Euml:"Sesli harf ayrÄ±lÄ±mlÄ±Ä± latin bÃ¼yÃ¼k E harfi",Igrave:"AksanlÄ± latin bÃ¼yÃ¼k I harfi",Iacute:"AÅÄ±rÄ± aksanlÄ± latin bÃ¼yÃ¼k I harfi",Icirc:"ÃarpÄ±k latin bÃ¼yÃ¼k I harfi",Iuml:"Sesli harf ayrÄ±lÄ±mlÄ±Ä± latin bÃ¼yÃ¼k I harfi",
ETH:"Latin bÃ¼yÃ¼k Eth harfi",Ntilde:"Tildeli latin bÃ¼yÃ¼k N harfi",Ograve:"AksanlÄ± latin bÃ¼yÃ¼k O harfi",Oacute:"AÅÄ±rÄ± aksanlÄ± latin bÃ¼yÃ¼k O harfi",Ocirc:"ÃarpÄ±k latin bÃ¼yÃ¼k O harfi",Otilde:"Tildeli latin bÃ¼yÃ¼k O harfi",Ouml:"Sesli harf ayrÄ±lÄ±mlÄ± latin bÃ¼yÃ¼k O harfi",times:"Ãarpma iÅareti",Oslash:"Vurgulu latin bÃ¼yÃ¼k O harfi",Ugrave:"AksanlÄ± latin bÃ¼yÃ¼k U harfi",Uacute:"AÅÄ±rÄ± aksanlÄ± latin bÃ¼yÃ¼k U harfi",Ucirc:"ÃarpÄ±k latin bÃ¼yÃ¼k U harfi",Uuml:"Sesli harf ayrÄ±lÄ±mlÄ± latin bÃ¼yÃ¼k U harfi",Yacute:"AÅÄ±rÄ± aksanlÄ± latin bÃ¼yÃ¼k Y harfi",
THORN:"Latin bÃ¼yÃ¼k Thorn harfi",szlig:"Latin kÃ¼Ã§Ã¼k keskin s harfi",agrave:"AksanlÄ± latin kÃ¼Ã§Ã¼k a harfi",aacute:"AÅÄ±rÄ± aksanlÄ± latin kÃ¼Ã§Ã¼k a harfi",acirc:"ÃarpÄ±k latin kÃ¼Ã§Ã¼k a harfi",atilde:"Tildeli latin kÃ¼Ã§Ã¼k a harfi",auml:"Sesli harf ayrÄ±lÄ±mlÄ± latin kÃ¼Ã§Ã¼k a harfi",aring:"HalkalÄ± latin kÃ¼Ã§Ã¼k a harfi",aelig:"Latin bÃ¼yÃ¼k Ã¦ harfi",ccedil:"KedillalÄ± latin kÃ¼Ã§Ã¼k c harfi",egrave:"AksanlÄ± latin kÃ¼Ã§Ã¼k e harfi",eacute:"AÅÄ±rÄ± aksanlÄ± latin kÃ¼Ã§Ã¼k e harfi",ecirc:"ÃarpÄ±k latin kÃ¼Ã§Ã¼k e harfi",euml:"Sesli harf ayrÄ±lÄ±mlÄ± latin kÃ¼Ã§Ã¼k e harfi",
igrave:"AksanlÄ± latin kÃ¼Ã§Ã¼k i harfi",iacute:"AÅÄ±rÄ± aksanlÄ± latin kÃ¼Ã§Ã¼k i harfi",icirc:"ÃarpÄ±k latin kÃ¼Ã§Ã¼k i harfi",iuml:"Sesli harf ayrÄ±lÄ±mlÄ± latin kÃ¼Ã§Ã¼k i harfi",eth:"Latin kÃ¼Ã§Ã¼k eth harfi",ntilde:"Tildeli latin kÃ¼Ã§Ã¼k n harfi",ograve:"AksanlÄ± latin kÃ¼Ã§Ã¼k o harfi",oacute:"AÅÄ±rÄ± aksanlÄ± latin kÃ¼Ã§Ã¼k o harfi",ocirc:"ÃarpÄ±k latin kÃ¼Ã§Ã¼k o harfi",otilde:"Tildeli latin kÃ¼Ã§Ã¼k o harfi",ouml:"Sesli harf ayrÄ±lÄ±mlÄ± latin kÃ¼Ã§Ã¼k o harfi",divide:"BÃ¶lme iÅareti",oslash:"Vurgulu latin kÃ¼Ã§Ã¼k o harfi",ugrave:"AksanlÄ± latin kÃ¼Ã§Ã¼k u harfi",
uacute:"AÅÄ±rÄ± aksanlÄ± latin kÃ¼Ã§Ã¼k u harfi",ucirc:"ÃarpÄ±k latin kÃ¼Ã§Ã¼k u harfi",uuml:"Sesli harf ayrÄ±lÄ±mlÄ± latin kÃ¼Ã§Ã¼k u harfi",yacute:"AÅÄ±rÄ± aksanlÄ± latin kÃ¼Ã§Ã¼k y harfi",thorn:"Latin kÃ¼Ã§Ã¼k thorn harfi",yuml:"Sesli harf ayrÄ±lÄ±mlÄ± latin kÃ¼Ã§Ã¼k y harfi",OElig:"Latin bÃ¼yÃ¼k baÄlÄ± OE harfi",oelig:"Latin kÃ¼Ã§Ã¼k baÄlÄ± oe harfi",372:"ÃarpÄ±k latin bÃ¼yÃ¼k W harfi",374:"ÃarpÄ±k latin bÃ¼yÃ¼k Y harfi",373:"ÃarpÄ±k latin kÃ¼Ã§Ã¼k w harfi",375:"ÃarpÄ±k latin kÃ¼Ã§Ã¼k y harfi",sbquo:"Tek dÃ¼ÅÃ¼k-9 tÄ±rnak iÅareti",8219:"Tek yÃ¼ksek-ters-9 tÄ±rnak iÅareti",
bdquo:"Ãift dÃ¼ÅÃ¼k-9 tÄ±rnak iÅareti",hellip:"Yatay elips",trade:"Marka tescili iÅareti",9658:"Siyah saÄ iÅaret iÅaretÃ§isi",bull:"Koyu nokta",rarr:"SaÄa doÄru ok",rArr:"SaÄa doÄru Ã§ift ok",hArr:"Sol, saÄ Ã§ift ok",diams:"Siyah elmas takÄ±mÄ±",asymp:"Hemen hemen eÅit"});