ï»¿/*
 Copyright (c) 2003-2019, CKSource - Frederico Knabben. All rights reserved.
 For licensing, see LICENSE.md or https://ckeditor.com/legal/ckeditor-oss-license
*/
CKEDITOR.plugins.setLang("specialchar","ug",{euro:"ÙØ§ÛØ±Ù Ø¨ÛÙÚ¯ÙØ³Ù",lsquo:"ÙØ§ÙØ§Ú­ Ù¾ÛØ´ Ø³ÙÙ",rsquo:"ÙØ§ÙØ§Ú­ Ù¾ÛØ´ Ø¦ÙÚ­",ldquo:"ÙÙØ´ Ù¾ÛØ´ Ø³ÙÙ",rdquo:"ÙÙØ´ Ù¾ÛØ´ Ø¦ÙÚ­",ndash:"Ø³ÙØ²ÙÙÚÛ",mdash:"Ø³ÙØ²ÙÙ",iexcl:"Ø¦ÛÙØ¯ÛØ´",cent:"ØªÙÙÙÙ Ø¨ÛÙÚ¯ÙØ³Ù",pound:"ÙÙÙØ¯ Ø³ØªÛØ±ÙÙÚ­",curren:"Ù¾ÛÙ Ø¨ÛÙÚ¯ÙØ³Ù",yen:"ÙØ§Ù¾ÙÙÙÙÛ ÙÙÙÙ",brvbar:"Ø¦ÛØ²ÛÙ Ø¨Ø§ÙØ¯Ø§Ù",sect:"Ù¾Ø§Ø±Ø§Ú¯Ø±Ø§Ù Ø¨ÛÙÚ¯ÙØ³Ù",uml:"ØªØ§ÛÛØ´ Ø¦Ø§ÙØ±ÙØ´ Ø¨ÛÙÚ¯ÙØ³Ù",copy:"ÙÛØ´Ø± Ú¾ÙÙÛÙÙ Ø¨ÛÙÚ¯ÙØ³Ù",ordf:"Feminine ordinal indicator",laquo:"ÙÙØ´ ØªÙØ±ÙØ§Ù Ø³ÙÙ",not:"ØºÛÙØ±Ù Ø¨ÛÙÚ¯Û",reg:"Ø®ÛØªÙÛØªÙÛÙ ØªØ§ÛØ§Ø± ÙØ§Ø±ÙÙØ³Ù",macr:"Ø³ÙØ²ÛØ´ Ø¨ÛÙÚ¯ÙØ³Ù",
deg:"Ú¯ÙØ±Ø§Ø¯ÛØ³ Ø¨ÛÙÚ¯ÙØ³Ù",sup2:"ÙÛÙÙØ±Ù Ø¦ÙÙØ¯ÛÙÙØ³ 2",sup3:"ÙÛÙÙØ±Ù Ø¦ÙÙØ¯ÛÙÙØ³ 3",acute:"Ø¦ÛØ±ØºÛ Ø¨ÛÙÚ¯ÙØ³Ù",micro:"Micro sign",para:"Ø¦Ø§Ø¨Ø²Ø§Ø³ Ø¨ÛÙÚ¯ÙØ³Ù",middot:"Ø¦ÙØªØªÛØ±Ø§ ÚÛÙÙØª",cedil:"Ø¦Ø§Ø³ØªÙØºØ§ ÙÙØ´ÛÙÙØ¯ÙØºØ§Ù Ø¨ÛÙÚ¯Û",sup1:"ÙÛÙÙØ±Ù Ø¦ÙÙØ¯ÛÙÙØ³ 1",ordm:"Masculine ordinal indicator",raquo:"ÙÙØ´ ØªÙØ±ÙØ§Ù Ø¦ÙÚ­",frac14:"Ø¦Ø§Ø¯Ø¯ÙÙ ÙÛØ³ÙØ± ØªÛØªØªÙÙ Ø¨ÙØ±",frac12:"Ø¦Ø§Ø¯Ø¯ÙÙ ÙÛØ³ÙØ± Ø¦ÙÙÙÙØ¯ÙÙ Ø¨ÙØ±",frac34:"Ø¦Ø§Ø¯Ø¯ÙÙ ÙÛØ³ÙØ± Ø¦ÛÚØªÙÙ ØªÛØ±Øª",iquest:"Inverted question mark",Agrave:"Latin capital letter A with grave accent",Aacute:"Latin capital letter A with acute accent",
Acirc:"Latin capital letter A with circumflex",Atilde:"Latin capital letter A with tilde",Auml:"Latin capital letter A with diaeresis",Aring:"Latin capital letter A with ring above",AElig:"Latin capital letter Ã",Ccedil:"Latin capital letter C with cedilla",Egrave:"Latin capital letter E with grave accent",Eacute:"Latin capital letter E with acute accent",Ecirc:"Latin capital letter E with circumflex",Euml:"Latin capital letter E with diaeresis",Igrave:"Latin capital letter I with grave accent",Iacute:"Latin capital letter I with acute accent",
Icirc:"Latin capital letter I with circumflex",Iuml:"Latin capital letter I with diaeresis",ETH:"Latin capital letter Eth",Ntilde:"Latin capital letter N with tilde",Ograve:"ÙÙØ´ Ù¾ÛØ´ Ø¦ÙÚ­",Oacute:"Latin capital letter O with acute accent",Ocirc:"Latin capital letter O with circumflex",Otilde:"Latin capital letter O with tilde",Ouml:"Latin capital letter O with diaeresis",times:"Multiplication sign",Oslash:"Latin capital letter O with stroke",Ugrave:"Latin capital letter U with grave accent",Uacute:"Latin capital letter U with acute accent",
Ucirc:"Latin capital letter U with circumflex",Uuml:"Latin capital letter U with diaeresis",Yacute:"Latin capital letter Y with acute accent",THORN:"Latin capital letter Thorn",szlig:"Latin small letter sharp s",agrave:"Latin small letter a with grave accent",aacute:"Latin small letter a with acute accent",acirc:"Latin small letter a with circumflex",atilde:"Latin small letter a with tilde",auml:"Latin small letter a with diaeresis",aring:"Latin small letter a with ring above",aelig:"Latin small letter Ã¦",
ccedil:"Latin small letter c with cedilla",egrave:"Latin small letter e with grave accent",eacute:"Latin small letter e with acute accent",ecirc:"Latin small letter e with circumflex",euml:"Latin small letter e with diaeresis",igrave:"Latin small letter i with grave accent",iacute:"Latin small letter i with acute accent",icirc:"Latin small letter i with circumflex",iuml:"Latin small letter i with diaeresis",eth:"Latin small letter eth",ntilde:"ØªÙÙ ÙÙÙÙØ§Ù Ø³ÙØ¦Ø§Ù Ø¨ÛÙÚ¯ÙØ³Ù",ograve:"Latin small letter o with grave accent",
oacute:"Latin small letter o with acute accent",ocirc:"Latin small letter o with circumflex",otilde:"Latin small letter o with tilde",ouml:"Latin small letter o with diaeresis",divide:"Ø¨ÛÙÛØ´ Ø¨ÛÙÚ¯ÙØ³Ù",oslash:"Latin small letter o with stroke",ugrave:"Latin small letter u with grave accent",uacute:"Latin small letter u with acute accent",ucirc:"Latin small letter u with circumflex",uuml:"Latin small letter u with diaeresis",yacute:"Latin small letter y with acute accent",thorn:"Latin small letter thorn",
yuml:"Latin small letter y with diaeresis",OElig:"Latin capital ligature OE",oelig:"Latin small ligature oe",372:"Latin capital letter W with circumflex",374:"Latin capital letter Y with circumflex",373:"Latin small letter w with circumflex",375:"Latin small letter y with circumflex",sbquo:"Single low-9 quotation mark",8219:"Single high-reversed-9 quotation mark",bdquo:"Double low-9 quotation mark",hellip:"Horizontal ellipsis",trade:"Ø®ÛØªÙÛØªÙÛÙ ØªØ§ÛØ§Ø± ÙØ§Ø±ÙÙØ³Ù Ø¨ÛÙÚ¯ÙØ³Ù",9658:"Black right-pointing pointer",
bull:"Bullet",rarr:"Ø¦ÙÚ­ ÙØ§ Ø¦ÙÙ",rArr:"Ø¦ÙÚ­ ÙÙØ´ Ø³ÙØ²ÙÙ ÙØ§ Ø¦ÙÙ",hArr:"Ø¦ÙÚ­ Ø³ÙÙ ÙÙØ´ Ø³ÙØ²ÙÙ ÙØ§ Ø¦ÙÙ",diams:"Ø¦ÛÙÛÙ ØºÙÚ",asymp:"ØªÛØ®ÙÙÙÛÙ ØªÛÚ­"});