ï»¿/*
 Copyright (c) 2003-2019, CKSource - Frederico Knabben. All rights reserved.
 For licensing, see LICENSE.md or https://ckeditor.com/legal/ckeditor-oss-license
*/
CKEDITOR.plugins.setLang("specialchar","vi",{euro:"KÃ½ hiá»u Euro",lsquo:"Dáº¥u ngoáº·c ÄÆ¡n trÃ¡i",rsquo:"Dáº¥u ngoáº·c ÄÆ¡n pháº£i",ldquo:"Dáº¥u ngoáº·c ÄÃ´i trÃ¡i",rdquo:"Dáº¥u ngoáº·c ÄÃ´i pháº£i",ndash:"Gáº¡ch ngang tiáº¿ng anh",mdash:"Gáº¡ch ngang Em",iexcl:"Chuyá»n Äá»i dáº¥u cháº¥m than",cent:"KÃ½ tá»± tiá»n Má»¹",pound:"KÃ½ tá»± tiá»n Anh",curren:"KÃ½ tá»± tiá»n tá»",yen:"KÃ½ tá»± tiá»n YÃªn Nháº­t",brvbar:"Thanh há»ng",sect:"KÃ½ tá»± khu vá»±c",uml:"Dáº¥u tÃ¡ch ÄÃ´i",copy:"KÃ½ tá»± báº£n quyá»n",ordf:"Pháº§n chá» thá» giá»ng cÃ¡i",laquo:"Chá»n dáº¥u ngoáº·c ÄÃ´i trÃ¡i",not:"KhÃ´ng cÃ³ kÃ½ tá»±",
reg:"KÃ½ tá»± ÄÄng kÃ½",macr:"Dáº¥u nguyÃªn Ã¢m dÃ i",deg:"KÃ½ tá»± Äá»",sup2:"Chá»¯ trá»i lÃªn trÃªn dáº¡ng 2",sup3:"Chá»¯ trá»i lÃªn trÃªn dáº¡ng 3",acute:"Dáº¥u trá»ng Ã¢m",micro:"KÃ½ tá»± micro",para:"KÃ½ tá»± Äoáº¡n vÄn",middot:"Dáº¥u cháº¥m trÃ²n",cedil:"Dáº¥u mÃ³c lÆ°á»i",sup1:"KÃ½ tá»± trá»i lÃªn cáº¥p 1",ordm:"KÃ½ tá»± biá»u hiá»n giá»ng Äá»±c",raquo:"Chá»n dáº¥u ngoáº·c ÄÃ´i pháº£i",frac14:"Tá» lá» má»t pháº§n tÆ°",frac12:"Tá» lá» má»t ná»­a",frac34:"Tá» lá» ba pháº§n tÆ°",iquest:"Chuyá»n Äá»i dáº¥u cháº¥m há»i",Agrave:"KÃ½ tá»± la-tinh viáº¿t hoa A vá»i dáº¥u huyá»n",Aacute:"KÃ½ tá»± la-tinh viáº¿t hoa A vá»i dáº¥u sáº¯c",
Acirc:"KÃ½ tá»± la-tinh viáº¿t hoa A vá»i dáº¥u mÅ©",Atilde:"KÃ½ tá»± la-tinh viáº¿t hoa A vá»i dáº¥u ngÃ£",Auml:"KÃ½ tá»± la-tinh viáº¿t hoa A vá»i dáº¥u hai cháº¥m trÃªn Äáº§u",Aring:"KÃ½ tá»± la-tinh viáº¿t hoa A vá»i biá»u tÆ°á»£ng vÃ²ng trÃ²n trÃªn Äáº§u",AElig:"KÃ½ tá»± la-tinh viáº¿t hoa cá»§a Ã",Ccedil:"KÃ½ tá»± la-tinh viáº¿t hoa C vá»i dáº¥u mÃ³c bÃªn dÆ°á»i",Egrave:"KÃ½ tá»± la-tinh viáº¿t hoa E vá»i dáº¥u huyá»n",Eacute:"KÃ½ tá»± la-tinh viáº¿t hoa E vá»i dáº¥u sáº¯c",Ecirc:"KÃ½ tá»± la-tinh viáº¿t hoa E vá»i dáº¥u mÅ©",Euml:"KÃ½ tá»± la-tinh viáº¿t hoa E vá»i dáº¥u hai cháº¥m trÃªn Äáº§u",
Igrave:"KÃ½ tá»± la-tinh viáº¿t hoa I vá»i dáº¥u huyá»n",Iacute:"KÃ½ tá»± la-tinh viáº¿t hoa I vá»i dáº¥u sáº¯c",Icirc:"KÃ½ tá»± la-tinh viáº¿t hoa I vá»i dáº¥u mÅ©",Iuml:"KÃ½ tá»± la-tinh viáº¿t hoa I vá»i dáº¥u hai cháº¥m trÃªn Äáº§u",ETH:"Viáº¿t hoa cá»§a kÃ½ tá»± Eth",Ntilde:"KÃ½ tá»± la-tinh viáº¿t hoa N vá»i dáº¥u ngÃ£",Ograve:"KÃ½ tá»± la-tinh viáº¿t hoa O vá»i dáº¥u huyá»n",Oacute:"KÃ½ tá»± la-tinh viáº¿t hoa O vá»i dáº¥u sáº¯c",Ocirc:"KÃ½ tá»± la-tinh viáº¿t hoa O vá»i dáº¥u mÅ©",Otilde:"KÃ½ tá»± la-tinh viáº¿t hoa O vá»i dáº¥u ngÃ£",Ouml:"KÃ½ tá»± la-tinh viáº¿t hoa O vá»i dáº¥u hai cháº¥m trÃªn Äáº§u",
times:"KÃ½ tá»± phÃ©p toÃ¡n nhÃ¢n",Oslash:"KÃ½ tá»± la-tinh viáº¿t hoa A vá»i dáº¥u ngÃ£ xuá»ng",Ugrave:"KÃ½ tá»± la-tinh viáº¿t hoa U vá»i dáº¥u huyá»n",Uacute:"KÃ½ tá»± la-tinh viáº¿t hoa U vá»i dáº¥u sáº¯c",Ucirc:"KÃ½ tá»± la-tinh viáº¿t hoa U vá»i dáº¥u mÅ©",Uuml:"KÃ½ tá»± la-tinh viáº¿t hoa U vá»i dáº¥u hai cháº¥m trÃªn Äáº§u",Yacute:"KÃ½ tá»± la-tinh viáº¿t hoa Y vá»i dáº¥u sáº¯c",THORN:"Pháº§n viáº¿t hoa cá»§a kÃ½ tá»± Thorn",szlig:"KÃ½ tá»± viáº¿t nhá» la-tinh cá»§a chá»¯ s",agrave:"KÃ½ tá»± la-tinh thÆ°á»ng vá»i dáº¥u huyá»n",aacute:"KÃ½ tá»± la-tinh thÆ°á»ng vá»i dáº¥u sáº¯c",acirc:"KÃ½ tá»± la-tinh thÆ°á»ng vá»i dáº¥u mÅ©",
atilde:"KÃ½ tá»± la-tinh thÆ°á»ng vá»i dáº¥u ngÃ£",auml:"KÃ½ tá»± la-tinh thÆ°á»ng vá»i dáº¥u hai cháº¥m trÃªn Äáº§u",aring:"KÃ½ tá»± la-tinh viáº¿t thÆ°á»ng vá»i biá»u tÆ°á»£ng vÃ²ng trÃ²n trÃªn Äáº§u",aelig:"KÃ½ tá»± la-tinh viáº¿t thÆ°á»ng cá»§a Ã¦",ccedil:"KÃ½ tá»± la-tinh viáº¿t thÆ°á»ng cá»§a c vá»i dáº¥u mÃ³c bÃªn dÆ°á»i",egrave:"KÃ½ tá»± la-tinh viáº¿t thÆ°á»ng e vá»i dáº¥u huyá»n",eacute:"KÃ½ tá»± la-tinh viáº¿t thÆ°á»ng e vá»i dáº¥u sáº¯c",ecirc:"KÃ½ tá»± la-tinh viáº¿t thÆ°á»ng e vá»i dáº¥u mÅ©",euml:"KÃ½ tá»± la-tinh viáº¿t thÆ°á»ng e vá»i dáº¥u hai cháº¥m trÃªn Äáº§u",igrave:"KÃ½ tá»± la-tinh viáº¿t thÆ°á»ng i vá»i dáº¥u huyá»n",
iacute:"KÃ½ tá»± la-tinh viáº¿t thÆ°á»ng i vá»i dáº¥u sáº¯c",icirc:"KÃ½ tá»± la-tinh viáº¿t thÆ°á»ng i vá»i dáº¥u mÅ©",iuml:"KÃ½ tá»± la-tinh viáº¿t thÆ°á»ng i vá»i dáº¥u hai cháº¥m trÃªn Äáº§u",eth:"KÃ½ tá»± la-tinh viáº¿t thÆ°á»ng cá»§a eth",ntilde:"KÃ½ tá»± la-tinh viáº¿t thÆ°á»ng n vá»i dáº¥u ngÃ£",ograve:"KÃ½ tá»± la-tinh viáº¿t thÆ°á»ng o vá»i dáº¥u huyá»n",oacute:"KÃ½ tá»± la-tinh viáº¿t thÆ°á»ng o vá»i dáº¥u sáº¯c",ocirc:"KÃ½ tá»± la-tinh viáº¿t thÆ°á»ng o vá»i dáº¥u mÅ©",otilde:"KÃ½ tá»± la-tinh viáº¿t thÆ°á»ng o vá»i dáº¥u ngÃ£",ouml:"KÃ½ tá»± la-tinh viáº¿t thÆ°á»ng o vá»i dáº¥u hai cháº¥m trÃªn Äáº§u",
divide:"KÃ½ hiá»u phÃ©p tÃ­nh chia",oslash:"KÃ½ tá»± la-tinh viáº¿t thÆ°á»ng o vá»i dáº¥u ngÃ£",ugrave:"KÃ½ tá»± la-tinh viáº¿t thÆ°á»ng u vá»i dáº¥u huyá»n",uacute:"KÃ½ tá»± la-tinh viáº¿t thÆ°á»ng u vá»i dáº¥u sáº¯c",ucirc:"KÃ½ tá»± la-tinh viáº¿t thÆ°á»ng u vá»i dáº¥u mÅ©",uuml:"KÃ½ tá»± la-tinh viáº¿t thÆ°á»ng u vá»i dáº¥u hai cháº¥m trÃªn Äáº§u",yacute:"KÃ½ tá»± la-tinh viáº¿t thÆ°á»ng y vá»i dáº¥u sáº¯c",thorn:"KÃ½ tá»± la-tinh viáº¿t thÆ°á»ng cá»§a chá»¯ thorn",yuml:"KÃ½ tá»± la-tinh viáº¿t thÆ°á»ng y vá»i dáº¥u hai cháº¥m trÃªn Äáº§u",OElig:"KÃ½ tá»± la-tinh viáº¿t hoa gáº¡ch ná»i OE",oelig:"KÃ½ tá»± la-tinh viáº¿t thÆ°á»ng gáº¡ch ná»i OE",
372:"KÃ½ tá»± la-tinh viáº¿t hoa W vá»i dáº¥u mÅ©",374:"KÃ½ tá»± la-tinh viáº¿t hoa Y vá»i dáº¥u mÅ©",373:"KÃ½ tá»± la-tinh viáº¿t thÆ°á»ng w vá»i dáº¥u mÅ©",375:"KÃ½ tá»± la-tinh viáº¿t thÆ°á»ng y vá»i dáº¥u mÅ©",sbquo:"Dáº¥u ngoáº·c ÄÆ¡n tháº¥p sá»-9",8219:"Dáº¥u ngoáº·c ÄÆ¡n Äáº£o ngÆ°á»£c sá»-9",bdquo:"Gáº¥p ÄÃ´i dáº¥u ngoáº·c ÄÆ¡n sá»-9",hellip:"TÄ©nh dÆ°á»£c chiá»u ngang",trade:"KÃ½ tá»± thÆ°Æ¡ng hiá»u",9658:"KÃ½ tá»± trá» vá» hÆ°á»ng bÃªn pháº£i mÃ u Äen",bull:"KÃ½ hiá»u",rarr:"MÅ©i tÃªn hÆ°á»ng bÃªn pháº£i",rArr:"MÅ©i tÃªn hÆ°á»ng bÃªn pháº£i dáº¡ng ÄÃ´i",hArr:"MÅ©i tÃªn hÆ°á»ng bÃªn trÃ¡i dáº¡ng ÄÃ´i",diams:"KÃ½ hiá»u hÃ¬nh thoi",
asymp:"Gáº§n báº±ng vá»i"});